export const algebraQuestions = [
    // Algebra (50 questions)
    { text: "What is the value of x in the equation 2x + 5 = 15?", options: ["5", "10", "7.5", "20"], correctIndex: 0 },
    { text: "What is the slope of the line y = 3x + 2?", options: ["2", "3", "5", "1"], correctIndex: 1 },
    { text: "What is the result of (x + 3)(x - 3)?", options: ["x² - 9", "x² + 9", "x² - 6x + 9", "x² + 6x - 9"], correctIndex: 0 },
    { text: "What is the quadratic formula?", options: ["x = -b ± √(b² - 4ac) / 2a", "x = b ± √(b² + 4ac) / 2a", "x = -b ± √(b² + 4ac) / a", "x = b ± √(b² - 4ac) / a"], correctIndex: 0 },
    { text: "What is 2³ × 2⁴?", options: ["2⁷", "2¹²", "4⁷", "2⁶"], correctIndex: 0 },
    { text: "What is the y-intercept of y = 4x - 7?", options: ["4", "-7", "7", "-4"], correctIndex: 1 },
    { text: "Simplify: 3x + 2x - x", options: ["6x", "4x", "5x", "2x"], correctIndex: 1 },
    { text: "What is the factored form of x² + 5x + 6?", options: ["(x + 2)(x + 3)", "(x + 1)(x + 6)", "(x - 2)(x - 3)", "(x + 5)(x + 1)"], correctIndex: 0 },
    { text: "What is √(x²)?", options: ["|x|", "x", "x²", "±x"], correctIndex: 0 },
    { text: "Solve for x: 3x - 7 = 20", options: ["9", "13", "27/3", "7"], correctIndex: 0 },
    { text: "What is (a + b)²?", options: ["a² + b²", "a² + 2ab + b²", "a² - 2ab + b²", "2a² + 2b²"], correctIndex: 1 },
    { text: "What is the value of x⁰ (where x ≠ 0)?", options: ["0", "1", "x", "Undefined"], correctIndex: 1 },
    { text: "Simplify: (x³)²", options: ["x⁵", "x⁶", "x⁹", "x"], correctIndex: 1 },
    { text: "What is the solution to |x| = 5?", options: ["5 only", "-5 only", "±5", "No solution"], correctIndex: 2 },
    { text: "What is the inverse operation of addition?", options: ["Division", "Multiplication", "Subtraction", "Exponentiation"], correctIndex: 2 },
    { text: "Solve: x/4 = 12", options: ["3", "16", "48", "8"], correctIndex: 2 },
    { text: "What is 5x - 2x + x?", options: ["3x", "4x", "6x", "8x"], correctIndex: 1 },
    { text: "What is the degree of the polynomial 4x³ + 2x² - 5?", options: ["2", "3", "4", "5"], correctIndex: 1 },
    { text: "Factor: x² - 16", options: ["(x - 4)(x + 4)", "(x - 8)(x + 8)", "(x - 2)(x + 8)", "(x - 4)²"], correctIndex: 0 },
    { text: "What is 2⁻³?", options: ["-8", "-6", "1/8", "1/6"], correctIndex: 2 },
    { text: "Solve: 2(x + 3) = 14", options: ["7", "4", "5.5", "11"], correctIndex: 1 },
    { text: "What is the domain of f(x) = 1/x?", options: ["All real numbers", "All numbers except 0", "Positive numbers only", "Negative numbers only"], correctIndex: 1 },
    { text: "Simplify: 12x/4x", options: ["3", "8", "3x", "8x"], correctIndex: 0 },
    { text: "What is the discriminant of ax² + bx + c = 0?", options: ["b² - 4ac", "b² + 4ac", "-b ± √(b² - 4ac)", "4ac - b²"], correctIndex: 0 },
    { text: "Solve: x² = 25", options: ["5 only", "-5 only", "±5", "No solution"], correctIndex: 2 },
    { text: "What is the slope of a horizontal line?", options: ["1", "Undefined", "0", "-1"], correctIndex: 2 },
    { text: "Expand: 3(x + 4)", options: ["3x + 4", "3x + 12", "x + 12", "3x + 7"], correctIndex: 1 },
    { text: "What is √64?", options: ["8", "32", "4", "16"], correctIndex: 0 },
    { text: "Solve: 5x + 3 = 3x + 11", options: ["4", "7", "2", "8"], correctIndex: 0 },
    { text: "What is (x - y)²?", options: ["x² - y²", "x² + y²", "x² - 2xy + y²", "x² + 2xy - y²"], correctIndex: 2 },
    { text: "What is the slope of a vertical line?", options: ["0", "1", "Undefined", "-1"], correctIndex: 2 },
    { text: "Simplify: x⁵/x²", options: ["x³", "x⁷", "x²·⁵", "x¹⁰"], correctIndex: 0 },
    { text: "What is log₁₀(100)?", options: ["10", "2", "100", "1"], correctIndex: 1 },
    { text: "Solve for x: x/3 + 2 = 5", options: ["9", "21", "7", "15"], correctIndex: 0 },
    { text: "What is the additive inverse of 5?", options: ["1/5", "0", "-5", "5"], correctIndex: 2 },
    { text: "Factor: 2x² + 8x", options: ["2(x² + 4x)", "2x(x + 4)", "x(2x + 8)", "2(x + 4)²"], correctIndex: 1 },
    { text: "What is i² (where i is the imaginary unit)?", options: ["1", "-1", "i", "0"], correctIndex: 1 },
    { text: "Solve: 4x - 2 = 2x + 6", options: ["2", "4", "8", "1"], correctIndex: 1 },
    { text: "What is the multiplicative inverse of 4?", options: ["-4", "4", "1/4", "0"], correctIndex: 2 },
    { text: "Simplify: (2x²)(3x³)", options: ["5x⁵", "6x⁵", "6x⁶", "5x⁶"], correctIndex: 1 },
    { text: "What type of function is y = x²?", options: ["Linear", "Exponential", "Quadratic", "Logarithmic"], correctIndex: 2 },
    { text: "Solve: x² - 4x + 4 = 0", options: ["x = 2", "x = 4", "x = ±2", "x = -4"], correctIndex: 0 },
    { text: "What is the vertex form of a parabola?", options: ["y = ax² + bx + c", "y = a(x - h)² + k", "y = mx + b", "y = a(x + h)² - k"], correctIndex: 1 },
    { text: "Evaluate: (-2)³", options: ["6", "-6", "8", "-8"], correctIndex: 3 },
    { text: "What is the range of f(x) = x²?", options: ["All real numbers", "y ≥ 0", "x ≥ 0", "y > 0"], correctIndex: 1 },
    { text: "Solve: 3x + 2 = 2x + 7", options: ["5", "9", "3", "4"], correctIndex: 0 },
    { text: "What is log₂(8)?", options: ["2", "3", "4", "8"], correctIndex: 1 },
    { text: "Simplify: ∛27", options: ["9", "3", "27", "6"], correctIndex: 1 },
    { text: "What is the sum of the roots of x² - 5x + 6 = 0?", options: ["6", "-5", "5", "1"], correctIndex: 2 },
    { text: "Factor completely: x³ - x", options: ["x(x² - 1)", "x(x - 1)(x + 1)", "(x - 1)(x² + 1)", "x²(x - 1)"], correctIndex: 1 },
];
