export const ancient_egyptQuestions = [

    // Ancient Egypt (50 questions)
    { text: "What river was central to ancient Egyptian civilization?", options: ["Tigris", "Nile", "Euphrates", "Jordan"], correctIndex: 1 },
    { text: "What were pyramids used for?", options: ["Temples", "Tombs for pharaohs", "Palaces", "Fortresses"], correctIndex: 1 },
    { text: "What is a pharaoh?", options: ["Priest", "Egyptian king", "General", "Merchant"], correctIndex: 1 },
    { text: "What is the Great Pyramid of Giza also called?", options: ["Pyramid of Khafre", "Pyramid of Khufu", "Pyramid of Menkaure", "Pyramid of Djoser"], correctIndex: 1 },
    { text: "What is the Sphinx?", options: ["Temple", "Statue with human head and lion body", "Pyramid", "Obelisk"], correctIndex: 1 },
    { text: "What writing system did ancient Egyptians use?", options: ["Cuneiform", "Hieroglyphics", "Alphabet", "Sanskrit"], correctIndex: 1 },
    { text: "What was mummification?", options: ["Burial ritual", "Preserving bodies", "Prayer ceremony", "Coronation"], correctIndex: 1 },
    { text: "What was the purpose of canopic jars?", options: ["Water storage", "Storing organs", "Food preservation", "Religious offerings"], correctIndex: 1 },
    { text: "Who was the sun god in Egyptian mythology?", options: ["Osiris", "Ra", "Anubis", "Horus"], correctIndex: 1 },
    { text: "What is the Valley of the Kings?", options: ["Royal palace", "Burial site for pharaohs", "Temple complex", "Ancient city"], correctIndex: 1 },
    { text: "Who was Tutankhamun?", options: ["Pyramid builder", "Boy pharaoh with famous tomb", "General", "High priest"], correctIndex: 1 },
    { text: "What was papyrus used for?", options: ["Food", "Paper/writing material", "Clothing", "Building"], correctIndex: 1 },
    { text: "What was the Rosetta Stone?", options: ["Weapon", "Key to deciphering hieroglyphics", "Religious artifact", "Crown jewel"], correctIndex: 1 },
    { text: "Who was the god of the afterlife?", options: ["Ra", "Osiris", "Set", "Thoth"], correctIndex: 1 },
    { text: "What was the Book of the Dead?", options: ["History book", "Funerary texts", "Law code", "Medical text"], correctIndex: 1 },
    { text: "Who was Cleopatra?", options: ["Queen of Egypt", "Last pharaoh of Egypt", "Priestess", "General"], correctIndex: 1 },
    { text: "What god had a jackal head?", options: ["Ra", "Anubis", "Horus", "Set"], correctIndex: 1 },
    { text: "What were scarabs?", options: ["Weapons", "Sacred beetle amulets", "Food", "Buildings"], correctIndex: 1 },
    { text: "What is a sarcophagus?", options: ["Temple", "Stone coffin", "Crown", "Weapon"], correctIndex: 1 },
    { text: "Who built the Great Pyramid?", options: ["Tutankhamun", "Khufu", "Ramses II", "Cleopatra"], correctIndex: 1 },
    { text: "What caused the annual Nile flooding?", options: ["Ocean tides", "Monsoon rains", "Earthquakes", "Dams"], correctIndex: 1 },
    { text: "What was Upper and Lower Egypt?", options: ["Mountains and valleys", "Two regions of Egypt", "Social classes", "Time periods"], correctIndex: 1 },
    { text: "What was a mastaba?", options: ["Food", "Early rectangular tomb", "Temple", "Palace"], correctIndex: 1 },
    { text: "Who unified Upper and Lower Egypt?", options: ["Tutankhamun", "Narmer (Menes)", "Ramses II", "Cleopatra"], correctIndex: 1 },
    { text: "What goddess had a cat head?", options: ["Isis", "Bastet", "Hathor", "Sekhmet"], correctIndex: 1 },
    { text: "What was the purpose of the pyramids' alignment?", options: ["Random", "Astronomical/religious significance", "Defensive", "Decorative"], correctIndex: 1 },
    { text: "What were obelisks?", options: ["Weapons", "Tall stone monuments", "Tombs", "Boats"], correctIndex: 1 },
    { text: "Who was Ramses II?", options: ["Minor ruler", "Powerful pharaoh and builder", "Foreign conqueror", "High priest"], correctIndex: 1 },
    { text: "What was the purpose of shabtis?", options: ["Currency", "Servant figures for afterlife", "Weapons", "Jewelry"], correctIndex: 1 },
    { text: "What color was the Egyptian crown of Upper Egypt?", options: ["Red", "White", "Blue", "Gold"], correctIndex: 1 },
    { text: "What was Karnak?", options: ["City", "Temple complex", "Pyramid", "Palace"], correctIndex: 1 },
    { text: "Who was Hatshepsut?", options: ["Male pharaoh", "Female pharaoh", "Queen consort", "Priestess"], correctIndex: 1 },
    { text: "What was the purpose of the false door in tombs?", options: ["Escape route", "Spirit passage to afterlife", "Ventilation", "Decoration"], correctIndex: 1 },
    { text: "What god had a falcon head?", options: ["Anubis", "Horus", "Thoth", "Set"], correctIndex: 1 },
    { text: "What was ancient Egypt's main crop?", options: ["Rice", "Wheat", "Corn", "Barley only"], correctIndex: 1 },
    { text: "What was the Sed festival?", options: ["Harvest celebration", "Pharaoh's jubilee", "New Year", "Religious pilgrimage"], correctIndex: 1 },
    { text: "What material were most Egyptian statues made from?", options: ["Wood", "Stone", "Bronze", "Clay"], correctIndex: 1 },
    { text: "Who was Nefertiti?", options: ["Pharaoh", "Queen and wife of Akhenaten", "Goddess", "General"], correctIndex: 1 },
    { text: "What was the ankh symbol?", options: ["Death", "Life", "War", "Wealth"], correctIndex: 1 },
    { text: "What god was associated with wisdom and writing?", options: ["Ra", "Thoth", "Osiris", "Ptah"], correctIndex: 1 },
    { text: "What was the purpose of amulets?", options: ["Currency", "Protection and power", "Decoration only", "Weapons"], correctIndex: 1 },
    { text: "What conquered Egypt in 30 BC?", options: ["Persia", "Rome", "Greece", "Babylon"], correctIndex: 1 },
    { text: "What was natron used for?", options: ["Food", "Drying bodies in mummification", "Building", "Currency"], correctIndex: 1 },
    { text: "What was the sistrum?", options: ["Weapon", "Musical instrument", "Crown", "Tool"], correctIndex: 1 },
    { text: "Who discovered King Tut's tomb?", options: ["Napoleon", "Howard Carter", "Champollion", "Petrie"], correctIndex: 1 },
    { text: "What were ushabti figures?", options: ["Gods", "Servant figures for afterlife", "Pharaohs", "Animals"], correctIndex: 1 },
    { text: "What was Ma'at?", options: ["Goddess of truth and order", "Weapon", "Crown", "City"], correctIndex: 0 },
    { text: "What was the crook and flail?", options: ["Farming tools", "Symbols of pharaoh's power", "Weapons", "Religious texts"], correctIndex: 1 },
    { text: "What period is considered Egypt's golden age?", options: ["Old Kingdom", "New Kingdom", "Middle Kingdom", "Late Period"], correctIndex: 1 },
    { text: "What was the purpose of tomb paintings?", options: ["Decoration only", "Guide and provide for afterlife", "Historical record", "Advertising"], correctIndex: 1 },
];
