export const ancient_romeQuestions = [

    // Ancient Rome (50 questions)
    { text: "Who was the first Roman Emperor?", options: ["Julius Caesar", "Augustus", "Nero", "Tiberius"], correctIndex: 1 },
    { text: "What year was Rome founded according to legend?", options: ["509 BC", "753 BC", "27 BC", "476 AD"], correctIndex: 1 },
    { text: "Who were Romulus and Remus?", options: ["Emperors", "Legendary founders", "Generals", "Senators"], correctIndex: 1 },
    { text: "What was the Roman Republic?", options: ["Monarchy", "Democracy", "Representative government", "Dictatorship"], correctIndex: 2 },
    { text: "Who crossed the Rubicon and started a civil war?", options: ["Augustus", "Julius Caesar", "Mark Antony", "Pompey"], correctIndex: 1 },
    { text: "What year did the Roman Republic become an Empire?", options: ["509 BC", "44 BC", "27 BC", "476 AD"], correctIndex: 2 },
    { text: "What was the Colosseum used for?", options: ["Senate meetings", "Gladiator fights", "Temple worship", "Market"], correctIndex: 1 },
    { text: "Who was the last Western Roman Emperor?", options: ["Nero", "Constantine", "Romulus Augustulus", "Diocletian"], correctIndex: 2 },
    { text: "What were the Punic Wars fought against?", options: ["Greece", "Carthage", "Egypt", "Gaul"], correctIndex: 1 },
    { text: "Who was the famous Carthaginian general?", options: ["Scipio", "Hannibal", "Spartacus", "Vercingetorix"], correctIndex: 1 },
    { text: "What was a Roman legion?", options: ["Government body", "Military unit", "Religious group", "Trade guild"], correctIndex: 1 },
    { text: "Who was emperor when Rome burned in 64 AD?", options: ["Caligula", "Nero", "Claudius", "Vespasian"], correctIndex: 1 },
    { text: "What language did ancient Romans speak?", options: ["Greek", "Latin", "Italian", "Etruscan"], correctIndex: 1 },
    { text: "What was the Pax Romana?", options: ["Civil war", "Period of peace", "Religious festival", "Military campaign"], correctIndex: 1 },
    { text: "Who was the Roman god of war?", options: ["Jupiter", "Mars", "Neptune", "Apollo"], correctIndex: 1 },
    { text: "What were aqueducts used for?", options: ["Defense", "Transportation", "Water supply", "Communication"], correctIndex: 2 },
    { text: "Who led a famous slave rebellion?", options: ["Crassus", "Spartacus", "Pompey", "Cicero"], correctIndex: 1 },
    { text: "What was the Roman Senate?", options: ["Military force", "Advisory council", "Religious body", "Trade organization"], correctIndex: 1 },
    { text: "Who was Julius Caesar's adopted heir?", options: ["Mark Antony", "Augustus", "Brutus", "Pompey"], correctIndex: 1 },
    { text: "What year did Julius Caesar die?", options: ["509 BC", "27 BC", "44 BC", "14 AD"], correctIndex: 2 },
    { text: "What was the Forum?", options: ["Arena", "Public square", "Temple", "Palace"], correctIndex: 1 },
    { text: "Who was Rome's first Christian emperor?", options: ["Nero", "Constantine", "Theodosius", "Augustus"], correctIndex: 1 },
    { text: "What were gladiators?", options: ["Soldiers", "Fighters for entertainment", "Senators", "Priests"], correctIndex: 1 },
    { text: "What was a toga?", options: ["Building", "Garment", "Weapon", "Currency"], correctIndex: 1 },
    { text: "Who was the Roman goddess of love?", options: ["Juno", "Venus", "Diana", "Minerva"], correctIndex: 1 },
    { text: "What year did the Western Roman Empire fall?", options: ["27 BC", "313 AD", "476 AD", "1453 AD"], correctIndex: 2 },
    { text: "What was Hadrian's Wall?", options: ["City wall", "Border fortification", "Aqueduct", "Temple"], correctIndex: 1 },
    { text: "Who was Mark Antony's famous lover?", options: ["Livia", "Cleopatra", "Octavia", "Agrippina"], correctIndex: 1 },
    { text: "What was the Praetorian Guard?", options: ["Naval force", "Emperor's bodyguards", "Senate police", "Border patrol"], correctIndex: 1 },
    { text: "What does 'Veni, Vidi, Vici' mean?", options: ["Live, Laugh, Love", "I came, I saw, I conquered", "Strength and Honor", "All roads lead to Rome"], correctIndex: 1 },
    { text: "Who were the patricians?", options: ["Slaves", "Upper class", "Soldiers", "Foreigners"], correctIndex: 1 },
    { text: "What was Pompeii destroyed by?", options: ["Earthquake", "Mount Vesuvius eruption", "Flood", "War"], correctIndex: 1 },
    { text: "Who were the plebeians?", options: ["Nobles", "Common people", "Slaves", "Priests"], correctIndex: 1 },
    { text: "What was the Circus Maximus?", options: ["Theater", "Chariot racing stadium", "Temple", "Bath house"], correctIndex: 1 },
    { text: "Who wrote the Aeneid?", options: ["Homer", "Virgil", "Ovid", "Cicero"], correctIndex: 1 },
    { text: "What were the Twelve Tables?", options: ["Furniture", "Early Roman laws", "Religious texts", "Military strategies"], correctIndex: 1 },
    { text: "Who was the emperor known for his cruelty and madness?", options: ["Augustus", "Caligula", "Trajan", "Marcus Aurelius"], correctIndex: 1 },
    { text: "What was a consul in ancient Rome?", options: ["Priest", "Highest elected official", "Military rank", "Slave owner"], correctIndex: 1 },
    { text: "What did SPQR stand for?", options: ["Senate People Queen Rome", "Senatus Populusque Romanus", "Special Power Quintus Rome", "Strong Proud Quick Romans"], correctIndex: 1 },
    { text: "Who was the philosopher-emperor?", options: ["Nero", "Marcus Aurelius", "Caligula", "Commodus"], correctIndex: 1 },
    { text: "What was the Pantheon?", options: ["Palace", "Temple to all gods", "Arena", "Market"], correctIndex: 1 },
    { text: "Who defeated Mark Antony at Actium?", options: ["Caesar", "Octavian", "Brutus", "Pompey"], correctIndex: 1 },
    { text: "What were Roman baths used for?", options: ["Religion only", "Socializing and bathing", "Military training", "Government meetings"], correctIndex: 1 },
    { text: "Who was the tribune who challenged the aristocracy?", options: ["Cicero", "Gracchus brothers", "Cato", "Sulla"], correctIndex: 1 },
    { text: "What was the Ides of March?", options: ["Festival", "Date Caesar was assassinated", "Battle", "Holiday"], correctIndex: 1 },
    { text: "What was a Roman villa?", options: ["Temple", "Country house", "Government building", "Arena"], correctIndex: 1 },
    { text: "Who conquered Gaul (France)?", options: ["Augustus", "Julius Caesar", "Pompey", "Crassus"], correctIndex: 1 },
    { text: "What were Roman roads famous for?", options: ["Being curved", "Engineering and durability", "Being short", "Being temporary"], correctIndex: 1 },
    { text: "Who was the general who said 'Carthage must be destroyed'?", options: ["Scipio", "Cato the Elder", "Hannibal", "Fabius"], correctIndex: 1 },
    { text: "What religion did Rome adopt in the 4th century AD?", options: ["Judaism", "Christianity", "Islam", "Zoroastrianism"], correctIndex: 1 },
];
