export const architectureQuestions = [

    // Architecture (50 questions)
    { text: "Who designed the Guggenheim Museum in Bilbao?", options: ["Zaha Hadid", "Frank Gehry", "Norman Foster", "Rem Koolhaas"], correctIndex: 1 },
    { text: "What is the Parthenon an example of?", options: ["Roman architecture", "Greek architecture", "Egyptian architecture", "Byzantine architecture"], correctIndex: 1 },
    { text: "Who designed Fallingwater?", options: ["Le Corbusier", "Frank Lloyd Wright", "Mies van der Rohe", "Walter Gropius"], correctIndex: 1 },
    { text: "What style is Notre-Dame Cathedral?", options: ["Romanesque", "Gothic", "Baroque", "Renaissance"], correctIndex: 1 },
    { text: "What does CAD stand for?", options: ["Computer Aided Design", "Creative Art Development", "Calculated Architecture Drawing", "Central Architectural Database"], correctIndex: 0 },
    { text: "Who designed the Sydney Opera House?", options: ["Frank Gehry", "Jørn Utzon", "Zaha Hadid", "Santiago Calatrava"], correctIndex: 1 },
    { text: "What is a flying buttress?", options: ["Roof ornament", "External support structure", "Window type", "Door design"], correctIndex: 1 },
    { text: "Who said 'Less is more'?", options: ["Frank Lloyd Wright", "Mies van der Rohe", "Le Corbusier", "Louis Kahn"], correctIndex: 1 },
    { text: "What is the Bauhaus?", options: ["Building type", "German design school", "Architectural style", "Construction method"], correctIndex: 1 },
    { text: "Who designed the Barcelona Pavilion?", options: ["Antoni Gaudí", "Mies van der Rohe", "Le Corbusier", "Walter Gropius"], correctIndex: 1 },
    { text: "What is a cantilever?", options: ["Support column", "Projecting beam", "Roof type", "Window style"], correctIndex: 1 },
    { text: "Who designed the Sagrada Família?", options: ["Mies van der Rohe", "Antoni Gaudí", "Le Corbusier", "Frank Gehry"], correctIndex: 1 },
    { text: "What is the oculus?", options: ["Window type", "Circular opening", "Dome", "Arch"], correctIndex: 1 },
    { text: "Who designed Villa Savoye?", options: ["Frank Lloyd Wright", "Le Corbusier", "Mies van der Rohe", "Walter Gropius"], correctIndex: 1 },
    { text: "What architectural order has scrolled capitals?", options: ["Doric", "Ionic", "Corinthian", "Tuscan"], correctIndex: 1 },
    { text: "Who designed the Seagram Building?", options: ["Frank Lloyd Wright", "Mies van der Rohe", "Le Corbusier", "Philip Johnson"], correctIndex: 1 },
    { text: "What is a clerestory?", options: ["Ground floor", "High windows", "Basement", "Roof garden"], correctIndex: 1 },
    { text: "Who designed the Chrysler Building?", options: ["Frank Lloyd Wright", "William Van Alen", "Louis Sullivan", "Cass Gilbert"], correctIndex: 1 },
    { text: "What is brutalism characterized by?", options: ["Ornate details", "Raw concrete", "Glass facades", "Wooden structures"], correctIndex: 1 },
    { text: "Who designed the TWA Terminal at JFK?", options: ["Frank Lloyd Wright", "Eero Saarinen", "Mies van der Rohe", "Philip Johnson"], correctIndex: 1 },
    { text: "What is a facade?", options: ["Interior wall", "Building's face/front", "Roof", "Foundation"], correctIndex: 1 },
    { text: "Who designed the Glass House?", options: ["Mies van der Rohe", "Philip Johnson", "Frank Lloyd Wright", "Walter Gropius"], correctIndex: 1 },
    { text: "What is a corbel?", options: ["Window type", "Projecting support", "Door handle", "Roof tile"], correctIndex: 1 },
    { text: "Who designed Habitat 67?", options: ["Louis Kahn", "Moshe Safdie", "I.M. Pei", "Tadao Ando"], correctIndex: 1 },
    { text: "What is the Pantheon's dome made of?", options: ["Wood", "Concrete", "Steel", "Glass"], correctIndex: 1 },
    { text: "Who designed the Louvre Pyramid?", options: ["Norman Foster", "I.M. Pei", "Richard Rogers", "Renzo Piano"], correctIndex: 1 },
    { text: "What is a spandrel?", options: ["Roof type", "Space between arches", "Column base", "Window frame"], correctIndex: 1 },
    { text: "Who designed the Pompidou Centre?", options: ["Norman Foster", "Richard Rogers and Renzo Piano", "Zaha Hadid", "Rem Koolhaas"], correctIndex: 1 },
    { text: "What is a pediment?", options: ["Foundation", "Triangular gable", "Column", "Arch"], correctIndex: 1 },
    { text: "Who designed the Guggenheim Museum in New York?", options: ["Mies van der Rohe", "Frank Lloyd Wright", "Le Corbusier", "Louis Kahn"], correctIndex: 1 },
    { text: "What is a portico?", options: ["Window", "Covered entrance", "Roof", "Chimney"], correctIndex: 1 },
    { text: "Who designed the Shard in London?", options: ["Norman Foster", "Renzo Piano", "Zaha Hadid", "Richard Rogers"], correctIndex: 1 },
    { text: "What is an atrium?", options: ["Basement", "Central open space", "Roof terrace", "Side entrance"], correctIndex: 1 },
    { text: "Who is known for parametric architecture?", options: ["Frank Gehry", "Zaha Hadid", "Norman Foster", "Tadao Ando"], correctIndex: 1 },
    { text: "What is a vault in architecture?", options: ["Safe room", "Arched ceiling", "Foundation", "Window type"], correctIndex: 1 },
    { text: "Who designed the Farnsworth House?", options: ["Frank Lloyd Wright", "Mies van der Rohe", "Philip Johnson", "Le Corbusier"], correctIndex: 1 },
    { text: "What is a colonnade?", options: ["Single column", "Row of columns", "Arch", "Dome"], correctIndex: 1 },
    { text: "Who designed the CCTV Headquarters in Beijing?", options: ["Zaha Hadid", "Rem Koolhaas", "Norman Foster", "Herzog & de Meuron"], correctIndex: 1 },
    { text: "What is a mansard roof?", options: ["Flat roof", "Four-sided gambrel roof", "Dome", "Pitched roof"], correctIndex: 1 },
    { text: "Who designed the National Congress of Brazil?", options: ["Frank Lloyd Wright", "Oscar Niemeyer", "Le Corbusier", "Louis Kahn"], correctIndex: 1 },
    { text: "What is a cornice?", options: ["Door frame", "Horizontal projection at top", "Floor trim", "Window sill"], correctIndex: 1 },
    { text: "Who designed the Kimbell Art Museum?", options: ["Mies van der Rohe", "Louis Kahn", "Philip Johnson", "I.M. Pei"], correctIndex: 1 },
    { text: "What is a baldachin?", options: ["Floor pattern", "Canopy over altar", "Wall decoration", "Window type"], correctIndex: 1 },
    { text: "Who designed the Vitra Fire Station?", options: ["Frank Gehry", "Zaha Hadid", "Rem Koolhaas", "Norman Foster"], correctIndex: 1 },
    { text: "What is organic architecture?", options: ["Green buildings", "Harmony with nature", "Vegetated facades", "Wooden structures"], correctIndex: 1 },
    { text: "Who designed the Millau Viaduct?", options: ["Calatrava", "Norman Foster", "Zaha Hadid", "Renzo Piano"], correctIndex: 1 },
    { text: "What is a porte-cochère?", options: ["Main entrance", "Covered vehicle entrance", "Side door", "Service entrance"], correctIndex: 1 },
    { text: "Who designed the Salk Institute?", options: ["Frank Lloyd Wright", "Louis Kahn", "Mies van der Rohe", "I.M. Pei"], correctIndex: 1 },
    { text: "What is a quoin?", options: ["Roof tile", "Corner stone", "Window frame", "Door hinge"], correctIndex: 1 },
    { text: "Who designed Casa Batlló?", options: ["Le Corbusier", "Antoni Gaudí", "Mies van der Rohe", "Oscar Niemeyer"], correctIndex: 1 },
];
