export const art_movementsQuestions = [

    // Art Movements (50 questions)
    { text: "What movement focused on dreams and the unconscious?", options: ["Cubism", "Surrealism", "Impressionism", "Realism"], correctIndex: 1 },
    { text: "Who founded Cubism with Picasso?", options: ["Matisse", "Braque", "Léger", "Gris"], correctIndex: 1 },
    { text: "What movement used geometric shapes and primary colors?", options: ["Impressionism", "De Stijl", "Fauvism", "Expressionism"], correctIndex: 1 },
    { text: "What movement emphasized emotion over realism?", options: ["Realism", "Expressionism", "Naturalism", "Academicism"], correctIndex: 1 },
    { text: "Who wrote the Futurist Manifesto?", options: ["Salvador Dalí", "Filippo Marinetti", "Umberto Boccioni", "Carlo Carrà"], correctIndex: 1 },
    { text: "What movement used wild, bright colors?", options: ["Realism", "Fauvism", "Minimalism", "Tonalism"], correctIndex: 1 },
    { text: "What does Dada mean?", options: ["Father", "Nonsense/anti-art", "Revolution", "Freedom"], correctIndex: 1 },
    { text: "Who was a leading Pop Art artist?", options: ["Jackson Pollock", "Andy Warhol", "Mark Rothko", "Willem de Kooning"], correctIndex: 1 },
    { text: "What movement focused on industrial subjects?", options: ["Romanticism", "Futurism", "Impressionism", "Symbolism"], correctIndex: 1 },
    { text: "What is Abstract Expressionism known for?", options: ["Realistic portraits", "Spontaneous, gestural painting", "Geometric shapes", "Religious themes"], correctIndex: 1 },
    { text: "Who led the Pre-Raphaelite Brotherhood?", options: ["John Ruskin", "Dante Gabriel Rossetti and others", "William Morris", "Edward Burne-Jones"], correctIndex: 1 },
    { text: "What movement rejected ornament in design?", options: ["Art Nouveau", "Modernism", "Baroque", "Rococo"], correctIndex: 1 },
    { text: "What movement used optical illusions?", options: ["Impressionism", "Op Art", "Pop Art", "Cubism"], correctIndex: 1 },
    { text: "Who was a major Surrealist artist?", options: ["Monet", "Salvador Dalí", "Renoir", "Cézanne"], correctIndex: 1 },
    { text: "What movement emphasized simplicity and reduction?", options: ["Baroque", "Minimalism", "Maximalism", "Rococo"], correctIndex: 1 },
    { text: "What is Art Nouveau characterized by?", options: ["Straight lines", "Organic, flowing lines", "Geometric shapes", "Minimal decoration"], correctIndex: 1 },
    { text: "Who painted 'I and the Village' (Surrealist work)?", options: ["Dalí", "Marc Chagall", "Magritte", "Miró"], correctIndex: 1 },
    { text: "What movement portrayed everyday life realistically?", options: ["Romanticism", "Realism", "Symbolism", "Impressionism"], correctIndex: 1 },
    { text: "What movement used photomontage and collage?", options: ["Impressionism", "Dada", "Realism", "Classicism"], correctIndex: 1 },
    { text: "Who was a leading Fauvist?", options: ["Picasso", "Henri Matisse", "Monet", "Van Gogh"], correctIndex: 1 },
    { text: "What movement emphasized individual emotion in landscape?", options: ["Classicism", "Romanticism", "Realism", "Naturalism"], correctIndex: 1 },
    { text: "What movement used everyday objects as art?", options: ["Impressionism", "Conceptual Art", "Realism", "Symbolism"], correctIndex: 1 },
    { text: "Who was a major Color Field painter?", options: ["Pollock", "Mark Rothko", "Picasso", "Dalí"], correctIndex: 1 },
    { text: "What movement rebelled against rationalism?", options: ["Realism", "Romanticism", "Classicism", "Naturalism"], correctIndex: 1 },
    { text: "What is Neo-Plasticism associated with?", options: ["Baroque", "De Stijl/Mondrian", "Cubism", "Surrealism"], correctIndex: 1 },
    { text: "Who led the Arts and Crafts movement?", options: ["John Ruskin", "William Morris", "Charles Rennie Mackintosh", "Gustav Stickley"], correctIndex: 1 },
    { text: "What movement used automatic drawing?", options: ["Realism", "Surrealism", "Cubism", "Impressionism"], correctIndex: 1 },
    { text: "What movement emphasized classical Greek/Roman ideals?", options: ["Romanticism", "Neoclassicism", "Baroque", "Gothic"], correctIndex: 1 },
    { text: "Who was associated with Action Painting?", options: ["Warhol", "Jackson Pollock", "Rothko", "Mondrian"], correctIndex: 1 },
    { text: "What movement used found objects (readymades)?", options: ["Impressionism", "Dada", "Realism", "Baroque"], correctIndex: 1 },
    { text: "What is Bauhaus known for?", options: ["Ornate decoration", "Form follows function", "Religious art", "Landscape painting"], correctIndex: 1 },
    { text: "Who wrote 'The Manifesto of Surrealism'?", options: ["Salvador Dalí", "André Breton", "Max Ernst", "Man Ray"], correctIndex: 1 },
    { text: "What movement emphasized local subject matter?", options: ["International Style", "Regionalism", "Globalism", "Universalism"], correctIndex: 1 },
    { text: "What is Suprematism characterized by?", options: ["Realism", "Basic geometric forms", "Natural forms", "Ornate details"], correctIndex: 1 },
    { text: "Who founded Suprematism?", options: ["Kandinsky", "Kazimir Malevich", "Mondrian", "Rodchenko"], correctIndex: 1 },
    { text: "What movement used commercial imagery?", options: ["Impressionism", "Pop Art", "Abstract Expressionism", "Surrealism"], correctIndex: 1 },
    { text: "What is Pointillism also called?", options: ["Cubism", "Divisionism", "Fauvism", "Tonalism"], correctIndex: 1 },
    { text: "Who painted in the Hudson River School style?", options: ["Winslow Homer", "Thomas Cole", "Mary Cassatt", "James Whistler"], correctIndex: 1 },
    { text: "What movement emphasized dramatic light and shadow?", options: ["Impressionism", "Baroque", "Minimalism", "Art Nouveau"], correctIndex: 1 },
    { text: "What is Constructivism associated with?", options: ["France", "Russia", "Italy", "Germany"], correctIndex: 1 },
    { text: "Who was a major Symbolist artist?", options: ["Monet", "Gustave Moreau", "Renoir", "Degas"], correctIndex: 1 },
    { text: "What movement celebrated consumer culture?", options: ["Realism", "Pop Art", "Romanticism", "Symbolism"], correctIndex: 1 },
    { text: "What is Vorticism?", options: ["Italian movement", "British movement emphasizing energy", "French movement", "American movement"], correctIndex: 1 },
    { text: "Who was associated with the Ashcan School?", options: ["Whistler", "Robert Henri", "Thomas Eakins", "Winslow Homer"], correctIndex: 1 },
    { text: "What movement focused on peasant and working-class subjects?", options: ["Romanticism", "Social Realism", "Impressionism", "Symbolism"], correctIndex: 1 },
    { text: "What is Orphism known for?", options: ["Monochrome", "Colorful abstraction", "Realism", "Minimalism"], correctIndex: 1 },
    { text: "Who led the Nabis group?", options: ["Monet", "Paul Sérusier", "Renoir", "Cézanne"], correctIndex: 1 },
    { text: "What movement emphasized the 'spiritual in art'?", options: ["Realism", "Abstract Art (Kandinsky)", "Pop Art", "Minimalism"], correctIndex: 1 },
    { text: "What is Tonalism characterized by?", options: ["Bright colors", "Muted, atmospheric tones", "Geometric shapes", "Bold lines"], correctIndex: 1 },
    { text: "Who was a major Precisionist?", options: ["Pollock", "Charles Sheeler", "Rothko", "De Kooning"], correctIndex: 1 },
];
