export const artQuestions = [

    // Art
    { text: "Who painted the Mona Lisa?", options: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1 },
    { text: "Which art movement did Salvador Dalí belong to?", options: ["Impressionism", "Surrealism", "Cubism", "Baroque"], correctIndex: 1 },
    { text: "In which city is the Sistine Chapel located?", options: ["Florence", "Venice", "Vatican City", "Rome"], correctIndex: 2 },
    { text: "Who painted 'The Starry Night'?", options: ["Claude Monet", "Vincent van Gogh", "Edvard Munch", "Paul Cézanne"], correctIndex: 1 },
    { text: "What is the primary color that forms the complement of blue?", options: ["Green", "Orange", "Red", "Yellow"], correctIndex: 1 },
    { text: "Which famous sculpture by Michelangelo depicts a biblical hero?", options: ["The Thinker", "David", "Venus de Milo", "The Kiss"], correctIndex: 1 },
    { text: "Which artist is known for painting 'The Persistence of Memory' with melting clocks?", options: ["Pablo Picasso", "Salvador Dalí", "Claude Monet", "Vincent van Gogh"], correctIndex: 1 },
    { text: "What material is Auguste Rodin's sculpture 'The Thinker' made of?", options: ["Bronze", "Marble", "Clay", "Wood"], correctIndex: 0 },
    { text: "Who painted the ceiling of the Sistine Chapel?", options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"], correctIndex: 1 },
    { text: "Which visual technique creates the optical illusion of depth on a flat surface?", options: ["Chiaroscuro", "Sfumato", "Foreshortening", "Trompe-l'œil"], correctIndex: 3 },
    { text: "Which artist is known for the 'Campbell's Soup Cans' series?", options: ["Andy Warhol", "Roy Lichtenstein", "Keith Haring", "Jean-Michel Basquiat"], correctIndex: 0 },
    { text: "Which art movement, associated with everyday consumer objects, emerged in the 1960s?", options: ["Minimalism", "Pop Art", "Conceptual Art", "Abstract Expressionism"], correctIndex: 1 },
    { text: "Which artist painted 'Girl with a Pearl Earring'?", options: ["Rembrandt", "Vermeer", "Caravaggio", "Rubens"], correctIndex: 1 },
    { text: "What is the painting technique of applying thin, transparent layers of paint called?", options: ["Impasto", "Glazing", "Scumbling", "Drybrush"], correctIndex: 1 },
    { text: "Which artist is known for the 'Water Lilies' series of paintings?", options: ["Edgar Degas", "Pierre-Auguste Renoir", "Claude Monet", "Camille Pissarro"], correctIndex: 2 },
    { text: "Which early 20th-century movement emphasized fragmented geometric forms?", options: ["Surrealism", "Cubism", "Futurism", "Dadaism"], correctIndex: 1 },
    { text: "Who painted 'The Scream'?", options: ["Edvard Munch", "Vincent van Gogh", "Paul Gauguin", "Henri Matisse"], correctIndex: 0 },
    { text: "What is the technique of applying very thick paint to create texture called?", options: ["Sfumato", "Chiaroscuro", "Impasto", "Glazing"], correctIndex: 2 },
    { text: "Which artist painted 'Guernica' as a reaction to the Spanish Civil War?", options: ["Salvador Dalí", "Pablo Picasso", "Joan Miró", "Juan Gris"], correctIndex: 1 },
    { text: "Which art movement did Jackson Pollock belong to?", options: ["Impressionism", "Pop Art", "Abstract Expressionism", "Minimalism"], correctIndex: 2 },
    { text: "Which American artist is known for creating large-scale mobile sculptures?", options: ["Alexander Calder", "Constantin Brâncuși", "Henry Moore", "Barbara Hepworth"], correctIndex: 0 },
    { text: "In which country did the Renaissance begin?", options: ["France", "England", "Netherlands", "Italy"], correctIndex: 3 },
    { text: "What is the art of decorating surfaces with small pieces of tile or glass called?", options: ["Fresco", "Mosaic", "Inlay", "Marquetry"], correctIndex: 1 },
    { text: "Who painted 'Impression, Sunrise', which gave Impressionism its name?", options: ["Edgar Degas", "Pierre-Auguste Renoir", "Claude Monet", "Camille Pissarro"], correctIndex: 2 },
    { text: "What is a fresco?", options: ["A painting applied to wet plaster", "A type of relief sculpture", "A watercolor technique", "A drawing on toned paper"], correctIndex: 0 },
    { text: "Which artist is famously known for having cut off his own ear?", options: ["Paul Gauguin", "Claude Monet", "Vincent van Gogh", "Pablo Picasso"], correctIndex: 2 },
    { text: "Which museum in Paris houses the Mona Lisa?", options: ["The Metropolitan Museum", "Uffizi Gallery", "The Louvre", "Musée d'Orsay"], correctIndex: 2 },
    { text: "What does the art term 'chiaroscuro' refer to?", options: ["Use of bright colors", "Contrast of light and dark", "Geometric composition", "Aerial perspective"], correctIndex: 1 },
    { text: "Which art movement rejected traditional forms in favor of chance and absurdity?", options: ["Surrealism", "Dadaism", "Cubism", "Futurism"], correctIndex: 1 },
    { text: "What is a sculptor's small preliminary model called?", options: ["Maquette", "Patina", "Armature", "Bas-relief"], correctIndex: 0 },
    { text: "Which artist is known for his 'Blue Period' and 'Rose Period'?", options: ["Salvador Dalí", "Henri Matisse", "Pablo Picasso", "Georges Braque"], correctIndex: 2 },
    { text: "Who is often called the 'father of modern art'?", options: ["Claude Monet", "Paul Cézanne", "Édouard Manet", "Edgar Degas"], correctIndex: 1 },
    { text: "What is the primary medium used in traditional watercolor painting?", options: ["Oil and pigment", "Pigment suspended in water", "Acrylic polymer", "Egg tempera"], correctIndex: 1 },
    { text: "Who designed the Eiffel Tower?", options: ["Auguste Rodin", "Gustave Eiffel", "Charles Garnier", "Hector Guimard"], correctIndex: 1 },
    { text: "What is the art technique of placing small dots of color side by side to create an image called?", options: ["Stippling", "Hatching", "Pointillism", "Sfumato"], correctIndex: 2 },
    { text: "Which artist painted the 'Sunflowers' series?", options: ["Paul Gauguin", "Edgar Degas", "Vincent van Gogh", "Paul Cézanne"], correctIndex: 2 },
    { text: "What is the term for a painting or drawing of an outdoor natural scene?", options: ["Still life", "Portrait", "Landscape", "Genre painting"], correctIndex: 2 },
    { text: "Which Renaissance movement featured elongated, distorted figures and unconventional compositions?", options: ["Baroque", "Mannerism", "Neoclassicism", "Rococo"], correctIndex: 1 },
    { text: "Which Japanese art form involves folding paper into decorative shapes?", options: ["Ikebana", "Bonsai", "Origami", "Calligraphy"], correctIndex: 2 },
    { text: "What is the study of beauty and artistic taste called?", options: ["Aesthetics", "Iconography", "Hermeneutics", "Semiotics"], correctIndex: 0 },
    { text: "Which artist painted 'The Birth of Venus'?", options: ["Raphael", "Leonardo da Vinci", "Michelangelo", "Sandro Botticelli"], correctIndex: 3 },
    { text: "What is printmaking?", options: ["Painting directly on glass", "Reproducing images by pressing an inked surface onto paper", "Sculpting with a chisel", "Weaving decorative tapestries"], correctIndex: 1 },
    { text: "Which artist is associated with the development of Abstract art alongside the Bauhaus movement?", options: ["Gustav Klimt", "Wassily Kandinsky", "Paul Klee", "Egon Schiele"], correctIndex: 1 },
    { text: "What type of art involves suspending or arranging objects within a gallery space for viewers to walk through?", options: ["Land art", "Assemblage", "Performance art", "Installation art"], correctIndex: 3 },
    { text: "Who painted 'The Last Supper'?", options: ["Raphael", "Michelangelo", "Leonardo da Vinci", "Titian"], correctIndex: 2 },
    { text: "Which art movement is characterized by visible brushstrokes and the capture of fleeting light?", options: ["Expressionism", "Romanticism", "Impressionism", "Realism"], correctIndex: 2 },
    { text: "What is the art of creating images by arranging cut pieces of paper or other materials called?", options: ["Collage", "Montage", "Assemblage", "Papier-mâché"], correctIndex: 0 },
    { text: "In which century did the High Renaissance flourish in Italy?", options: ["13th", "14th", "15th–16th", "17th"], correctIndex: 2 },
    { text: "Which Flemish Baroque artist is known for large, dramatic religious and mythological paintings?", options: ["Rembrandt van Rijn", "Johannes Vermeer", "Peter Paul Rubens", "Jan van Eyck"], correctIndex: 2 },
    { text: "What is the technique of applying Leonardo da Vinci's soft, hazy transitions between light and shadow called?", options: ["Chiaroscuro", "Sfumato", "Impasto", "Scumbling"], correctIndex: 1 },
];
