export const artQuestions = [
  // Art
    { text: "Who painted the Mona Lisa?", options: ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], correctIndex: 1 },
    { text: "Which art movement did Salvador Dalí belong to?", options: ["Impressionism", "Surrealism", "Cubism", "Baroque"], correctIndex: 1 },
    { text: "In which city is the Sistine Chapel located?", options: ["Florence", "Venice", "Vatican City", "Rome"], correctIndex: 2 },
    { text: "Who painted The Starry Night?", options: ["Claude Monet", "Vincent van Gogh", "Edvard Munch", "Paul Cézanne"], correctIndex: 1 },
    { text: "What is the primary color that complements blue?", options: ["Green", "Orange", "Red", "Yellow"], correctIndex: 1 },
    { text: "What is the name of the famous sculpture by Michelangelo depicting a biblical figure?", options: ["The Thinker", "David", "Venus de Milo", "The Kiss"], correctIndex: 1 },
    { text: "Which artist is known for painting 'The Persistence of Memory' with melting clocks?", options: ["Pablo Picasso", "Salvador Dalí", "Claude Monet", "Vincent van Gogh"], correctIndex: 1 },
    { text: "What material is the sculpture 'The Thinker' by Auguste Rodin made of?", options: ["Bronze", "Marble", "Clay", "Wood"], correctIndex: 0 },
    { text: "Which art movement is characterized by bold colors and visible brushstrokes?", options: ["Impressionism", "Cubism", "Expressionism", "Realism"], correctIndex: 0 },
    { text: "Who painted the ceiling of the Sistine Chapel?", options: ["Leonardo da Vinci", "Michelangelo", "Raphael", "Donatello"], correctIndex: 1 },
    { text: "What is the name of the art technique that creates an optical illusion of depth?", options: ["Chiaroscuro", "Sfumato", "Foreshortening", "Trompe-l'œil"], correctIndex: 3 },
    { text: "Which artist is known for the 'Campbell's Soup Cans' series?", options: ["Andy Warhol", "Roy Lichtenstein", "Keith Haring", "Jean-Michel Basquiat"], correctIndex: 0 },
    { text: "What is the name of the art movement that emerged in the 1960s and used everyday objects as art?", options: ["Minimalism", "Pop Art", "Conceptual Art", "Abstract Expressionism"], correctIndex: 1 },
    { text: "Which artist painted 'Girl with a Pearl Earring'?", options: ["Rembrandt", "Vermeer", "Caravaggio", "Rubens"], correctIndex: 1 },
    { text: "What is the name of the art technique that involves applying paint in thin layers to create a translucent effect?", options: ["Impasto", "Glazing", "Scumbling", "Drybrush"], correctIndex: 1 },
    { text: "Which artist is known for the 'Water Lilies' series?", options: ["Edgar Degas", "Pierre-Auguste Renoir", "Claude Monet", "Camille Pissarro"], correctIndex: 2 },
    { text: "What is the name of the art movement that emerged in the early 20th century and emphasized geometric shapes and fragmented forms?", options: ["Surrealism", "Cubism", "Futurism", "Dadaism"], correctIndex: 1 },
    { text: "Which artist painted 'The Scream'?", options: ["Edvard Munch", "Vincent van Gogh", "Paul Gauguin", "Henri Matisse"], correctIndex: 0 },
    { text: "What is the name of the art technique that involves applying thick layers of paint to create texture?", options: ["Sfumato", "Chiaroscuro", "Impasto", "Glazing"], correctIndex: 2 },
    { text: "Which artist is known for the 'Guernica' painting?", options: ["Salvador Dalí", "Pablo Picasso", "Joan Miró", "Juan Gris"], correctIndex: 1 },
    { text: "What is the name of the art movement that emerged in the 1960s and used everyday objects as art?", options: ["Minimalism", "Pop Art", "Conceptual Art", "Abstract Expressionism"], correctIndex: 1 },
    { text: "Which artist painted 'Girl with a Pearl Earring'?", options: ["Rembrandt", "Vermeer", "Caravaggio", "Rubens"], correctIndex: 1 },
    { text: "What is the name of the art technique that involves applying paint in thin layers to create a translucent effect?", options: ["Impasto", "Glazing", "Scumbling", "Drybrush"], correctIndex: 1 },
    { text: "Which artist is known for the 'Water Lilies' series?", options: ["Edgar Degas", "Pierre-Auguste Renoir", "Claude Monet", "Camille Pissarro"], correctIndex: 2 },
    { text: "What is the name of the art movement that emerged in the early 20th century and emphasized geometric shapes and fragmented forms?", options: ["Surrealism", "Cubism", "Futurism", "Dadaism"], correctIndex: 1 },
    { text: "Which artist painted 'The Scream'?", options: ["Edvard Munch", "Vincent van Gogh", "Paul Gauguin", "Henri Matisse"], correctIndex: 0 },
    { text: "What is the name of the art technique that involves applying thick layers of paint to create texture?", options: ["Sfumato", "Chiaroscuro", "Impasto", "Glazing"], correctIndex: 2 },
    { text: "Which artist is known for the 'Guernica' painting?", options: ["Salvador Dalí", "Pablo Picasso", "Joan Miró", "Juan Gris"], correctIndex: 1 },
];
