export const astronomyQuestions = [

    //Astronomy
    { text: "What planet was removed from our planet list?", options: ["Earth", "Mercury", "Pluto", "Mars"], correctIndex: 2 },
    { text: "What is the largest planet in our solar system?", options: ["Saturn", "Jupiter", "Neptune", "Uranus"], correctIndex: 1 },
    { text: "What galaxy is Earth located in?", options: ["Andromeda", "Milky Way", "Triangulum", "Whirlpool"], correctIndex: 1 },
    { text: "What is the closest star to Earth?", options: ["Proxima Centauri", "Alpha Centauri", "The Sun", "Sirius"], correctIndex: 2 },
    { text: "What is a group of stars that form a pattern called?", options: ["Galaxy", "Nebula", "Constellation", "Cluster"], correctIndex: 2 },
    { text: "What planet is known as the Red Planet?", options: ["Mars", "Venus", "Jupiter", "Mercury"], correctIndex: 0 },
    { text: "What is the hottest planet in our solar system?", options: ["Mercury", "Mars", "Venus", "Jupiter"], correctIndex: 2 },
    { text: "What term describes a dying star that has collapsed?", options: ["White dwarf", "Red giant", "Black hole", "Supernova"], correctIndex: 2 },
    { text: "How many moons does Mars have?", options: ["1", "2", "3", "0"], correctIndex: 1 },
    { text: "What is the largest moon of Saturn?", options: ["Europa", "Ganymede", "Titan", "Io"], correctIndex: 2 },
    { text: "What is the name of Earth's moon?", options: ["Luna", "Selene", "The Moon", "All of these"], correctIndex: 3 },
    { text: "What force keeps planets in orbit around the Sun?", options: ["Magnetism", "Gravity", "Inertia", "Friction"], correctIndex: 1 },
    { text: "What is a light-year?", options: ["A unit of time", "A unit of speed", "A unit of distance", "A unit of mass"], correctIndex: 2 },
    { text: "What planet has the most moons?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], correctIndex: 1 },
    { text: "What is the smallest planet in our solar system?", options: ["Mars", "Mercury", "Pluto", "Venus"], correctIndex: 1 },
    { text: "What is the name of the first artificial satellite?", options: ["Apollo 11", "Sputnik 1", "Explorer 1", "Vanguard 1"], correctIndex: 1 },
    { text: "What is a comet made of?", options: ["Pure rock", "Metal", "Ice and dust", "Gas only"], correctIndex: 2 },
    { text: "What is the Great Red Spot on Jupiter?", options: ["A crater", "A moon", "A storm", "A volcano"], correctIndex: 2 },
    { text: "What is the asteroid belt located between?", options: ["Earth and Mars", "Mars and Jupiter", "Jupiter and Saturn", "Saturn and Uranus"], correctIndex: 1 },
    { text: "What type of galaxy is the Milky Way?", options: ["Elliptical", "Irregular", "Spiral", "Lenticular"], correctIndex: 2 },
    { text: "What is the name of the first person in space?", options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"], correctIndex: 2 },
    { text: "What planet is known for its rings?", options: ["Jupiter", "Uranus", "Neptune", "Saturn"], correctIndex: 3 },
    { text: "What is the coldest planet in our solar system?", options: ["Neptune", "Pluto", "Uranus", "Saturn"], correctIndex: 2 },
    { text: "What is a supernova?", options: ["A new star", "An exploding star", "A black hole", "A planet"], correctIndex: 1 },
    { text: "What is the name of our nearest galaxy?", options: ["Triangulum", "Whirlpool", "Andromeda", "Sombrero"], correctIndex: 2 },
    { text: "What is the Sun classified as?", options: ["A planet", "A star", "A moon", "An asteroid"], correctIndex: 1 },
    { text: "How long does it take Earth to orbit the Sun?", options: ["24 hours", "30 days", "365 days", "12 months"], correctIndex: 2 },
    { text: "What is the Hubble Space Telescope used for?", options: ["Weather monitoring", "Observing space", "Communication", "GPS navigation"], correctIndex: 1 },
    { text: "What is a pulsar?", options: ["A rotating neutron star", "A type of comet", "A red giant", "A planet"], correctIndex: 0 },
    { text: "What is the Kuiper Belt?", options: ["A region of asteroids", "A region of comets and icy bodies", "A type of galaxy", "A constellation"], correctIndex: 1 },
    { text: "What planet rotates on its side?", options: ["Saturn", "Neptune", "Uranus", "Jupiter"], correctIndex: 2 },
    { text: "What is the name of the rover that landed on Mars in 2021?", options: ["Curiosity", "Opportunity", "Perseverance", "Spirit"], correctIndex: 2 },
    { text: "What is solar wind?", options: ["Wind on the Sun", "Particles from the Sun", "Storms on Earth", "Meteor showers"], correctIndex: 1 },
    { text: "What is the name of Jupiter's largest moon?", options: ["Titan", "Europa", "Ganymede", "Callisto"], correctIndex: 2 },
    { text: "What causes a lunar eclipse?", options: ["Moon blocks the Sun", "Earth blocks sunlight to Moon", "Sun blocks the Moon", "Mars blocks the Sun"], correctIndex: 1 },
    { text: "What is dark matter?", options: ["Black holes", "Invisible matter", "Dark energy", "Dead stars"], correctIndex: 1 },
    { text: "What is the temperature at the Sun's core?", options: ["1 million degrees", "15 million degrees", "100,000 degrees", "50 million degrees"], correctIndex: 1 },
    { text: "What is a meteor called when it hits Earth?", options: ["Asteroid", "Comet", "Meteorite", "Shooting star"], correctIndex: 2 },
    { text: "What is the name of the telescope launched in 2021?", options: ["Hubble", "Kepler", "James Webb", "Spitzer"], correctIndex: 2 },
    { text: "What planet has the fastest orbit around the Sun?", options: ["Mercury", "Venus", "Earth", "Mars"], correctIndex: 0 },
    { text: "What is a nebula?", options: ["A dead star", "A cloud of gas and dust", "A type of planet", "A black hole"], correctIndex: 1 },
    { text: "What is the Oort Cloud?", options: ["A region of comets", "A type of nebula", "A galaxy", "A star cluster"], correctIndex: 0 },
    { text: "What causes the auroras (Northern/Southern Lights)?", options: ["Lightning", "Solar wind particles", "Moon's gravity", "Comets"], correctIndex: 1 },
    { text: "What is the main component of the Sun?", options: ["Helium", "Oxygen", "Hydrogen", "Carbon"], correctIndex: 2 },
    { text: "What is the name of the first human to walk on the Moon?", options: ["Buzz Aldrin", "Yuri Gagarin", "Neil Armstrong", "Michael Collins"], correctIndex: 2 },
    { text: "What planet has a day longer than its year?", options: ["Mercury", "Venus", "Mars", "Jupiter"], correctIndex: 1 },
    { text: "What is the name of the largest volcano in the solar system?", options: ["Mount Everest", "Mauna Kea", "Olympus Mons", "Kilimanjaro"], correctIndex: 2 },
    { text: "What is a binary star system?", options: ["One star", "Two stars orbiting each other", "Three stars", "A dead star"], correctIndex: 1 },
    { text: "What mission first landed humans on the Moon?", options: ["Apollo 13", "Apollo 11", "Gemini 8", "Mercury 7"], correctIndex: 1 },
    { text: "What is the escape velocity of Earth?", options: ["5 km/s", "11.2 km/s", "20 km/s", "30 km/s"], correctIndex: 1 },
    { text: "What is Pluto classified as now?", options: ["Planet", "Asteroid", "Dwarf planet", "Moon"], correctIndex: 2 },
    { text: "What is the name of Saturn's largest ring?", options: ["A Ring", "B Ring", "C Ring", "D Ring"], correctIndex: 1 },
    { text: "What is the brightest star in the night sky?", options: ["Polaris", "Betelgeuse", "Sirius", "Vega"], correctIndex: 2 },
    { text: "What is the Goldilocks Zone?", options: ["A region on Mars", "Habitable zone around a star", "Center of galaxy", "Asteroid belt"], correctIndex: 1 },
    { text: "What spacecraft has traveled the farthest from Earth?", options: ["Apollo 11", "Voyager 1", "New Horizons", "Cassini"], correctIndex: 1 },
    { text: "What is the name of the first space station?", options: ["ISS", "Skylab", "Mir", "Salyut 1"], correctIndex: 3 },
    { text: "What phenomenon occurs when a star's light bends around a massive object?", options: ["Reflection", "Refraction", "Gravitational lensing", "Diffraction"], correctIndex: 2 },
    { text: "What is the name of the theory explaining the universe's origin?", options: ["Steady State", "Inflation", "Big Bang", "Multiverse"], correctIndex: 2 },
    { text: "What is the name of Neptune's largest moon?", options: ["Titan", "Europa", "Triton", "Oberon"], correctIndex: 2 },
    { text: "What is cosmic microwave background radiation?", options: ["Heat from stars", "Radiation from black holes", "Afterglow of Big Bang", "Solar radiation"], correctIndex: 2 },
    { text: "What is the name of the largest known star?", options: ["Betelgeuse", "UY Scuti", "VY Canis Majoris", "Antares"], correctIndex: 1 },
    { text: "What is a quasar?", options: ["A type of planet", "An extremely bright active galactic nucleus", "A constellation", "A type of comet"], correctIndex: 1 },
    { text: "What is the speed of light?", options: ["300,000 km/s", "150,000 km/s", "500,000 km/s", "1,000,000 km/s"], correctIndex: 0 },
    { text: "What is the name of the first American in space?", options: ["John Glenn", "Alan Shepard", "Neil Armstrong", "Buzz Aldrin"], correctIndex: 1 },
    { text: "What is a white dwarf?", options: ["A young star", "The remnant of a dead star", "A type of planet", "A galaxy"], correctIndex: 1 },
    { text: "What causes tides on Earth?", options: ["Sun's heat", "Earth's rotation", "Moon's gravity", "Wind"], correctIndex: 2 },
    { text: "What is the name of the brightest planet in our night sky?", options: ["Mars", "Venus", "Jupiter", "Saturn"], correctIndex: 1 },
    { text: "What is antimatter?", options: ["Dark matter", "Matter with opposite properties", "Empty space", "Energy"], correctIndex: 1 },
    { text: "What is a red giant?", options: ["A young star", "An aging, expanding star", "A type of planet", "A nebula"], correctIndex: 1 },
    { text: "What is the name of the mission that landed on a comet?", options: ["Voyager", "Cassini", "Rosetta", "New Horizons"], correctIndex: 2 },
    { text: "What is the age of the universe approximately?", options: ["4.5 billion years", "10 billion years", "13.8 billion years", "20 billion years"], correctIndex: 2 },
    { text: "What is a brown dwarf?", options: ["A failed star", "A type of planet", "A dead star", "A galaxy"], correctIndex: 0 },
    { text: "What is the name of the first woman in space?", options: ["Sally Ride", "Mae Jemison", "Valentina Tereshkova", "Eileen Collins"], correctIndex: 2 },
    { text: "What is interstellar space?", options: ["Space inside a star", "Space between stars", "Space between planets", "Space inside galaxies only"], correctIndex: 1 },
    { text: "What is the name of Mars' largest moon?", options: ["Deimos", "Phobos", "Europa", "Titan"], correctIndex: 1 },
    { text: "What is the Chandrasekhar limit?", options: ["Speed limit in space", "Maximum mass of white dwarf", "Distance to nearest star", "Size of black hole"], correctIndex: 1 },
    { text: "What is a gamma-ray burst?", options: ["Solar flare", "Extremely energetic explosion", "Asteroid impact", "Comet tail"], correctIndex: 1 },
    { text: "What is the Drake Equation used for?", options: ["Calculating planet orbits", "Estimating intelligent civilizations", "Measuring star brightness", "Finding black holes"], correctIndex: 1 },
    { text: "What is the name of the spacecraft that studied Pluto?", options: ["Voyager 2", "Cassini", "New Horizons", "Pioneer 10"], correctIndex: 2 },
    { text: "What is a planetary nebula?", options: ["A forming planet", "Ejected outer layers of a dying star", "A type of galaxy", "A comet"], correctIndex: 1 },
    { text: "What is the Schwarzschild radius?", options: ["Size of a star", "Event horizon of black hole", "Distance to nearest galaxy", "Orbit of planets"], correctIndex: 1 },
    { text: "What is cosmic inflation?", options: ["Expansion of universe", "Rapid expansion after Big Bang", "Growth of stars", "Formation of galaxies"], correctIndex: 1 },
    { text: "What is the name of the largest asteroid?", options: ["Pallas", "Vesta", "Ceres", "Eros"], correctIndex: 2 },
    { text: "What is the International Space Station's orbital period?", options: ["24 hours", "12 hours", "90 minutes", "6 hours"], correctIndex: 2 },
    { text: "What is the name of the first spacecraft to leave the solar system?", options: ["Pioneer 10", "Voyager 1", "New Horizons", "Voyager 2"], correctIndex: 1 },
    { text: "What is stellar nucleosynthesis?", options: ["Star formation", "Element creation in stars", "Star death", "Nuclear fusion"], correctIndex: 1 },
    { text: "What is the Great Attractor?", options: ["Black hole", "Gravitational anomaly pulling galaxies", "Largest star", "Biggest planet"], correctIndex: 1 },
    { text: "What is the name of the first exoplanet discovered?", options: ["Kepler-452b", "51 Pegasi b", "Proxima b", "TRAPPIST-1e"], correctIndex: 1 },
    { text: "What is Hawking radiation?", options: ["Solar radiation", "Radiation from black holes", "Cosmic rays", "Gamma rays"], correctIndex: 1 },
    { text: "What is the name of the largest impact crater on Earth?", options: ["Chicxulub", "Vredefort", "Meteor Crater", "Sudbury Basin"], correctIndex: 1 },
    { text: "What is a magnetar?", options: ["Magnetic planet", "Neutron star with strong magnetic field", "Type of asteroid", "Charged comet"], correctIndex: 1 },
    { text: "What is the observable universe's diameter approximately?", options: ["13.8 billion light-years", "46 billion light-years", "93 billion light-years", "200 billion light-years"], correctIndex: 2 },
    { text: "What is dark energy?", options: ["Energy in black holes", "Mysterious force accelerating expansion", "Solar energy", "Nuclear energy"], correctIndex: 1 },
    { text: "What is a Trojan asteroid?", options: ["Asteroid near Mars", "Asteroid sharing planet's orbit", "Asteroid in belt", "Asteroid near Moon"], correctIndex: 1 },
    { text: "What is the name of the mission that first orbited Jupiter?", options: ["Voyager 1", "Pioneer 10", "Galileo", "Juno"], correctIndex: 2 },
    { text: "What is the heliosphere?", options: ["Sun's atmosphere", "Bubble created by solar wind", "Solar system", "Sun's core"], correctIndex: 1 },
    { text: "What is a tidal lock?", options: ["Ocean tides", "Same face always toward planet", "Locked orbit", "Gravitational pull"], correctIndex: 1 },
    { text: "What is the Fermi Paradox?", options: ["Time travel paradox", "Why we haven't found aliens", "Black hole paradox", "Universe expansion"], correctIndex: 1 },
    { text: "What is the name of the largest known structure in the universe?", options: ["Great Wall", "Hercules-Corona Borealis Great Wall", "Sloan Great Wall", "Giant Void"], correctIndex: 1 },
];
