export const biologyQuestions = [
    // Biology (50 questions)
    { text: "What is the powerhouse of the cell?", options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi apparatus"], correctIndex: 1 },
    { text: "What is the process plants use to make food?", options: ["Respiration", "Photosynthesis", "Fermentation", "Digestion"], correctIndex: 1 },
    { text: "What is DNA?", options: ["A protein", "Deoxyribonucleic acid", "A carbohydrate", "An enzyme"], correctIndex: 1 },
    { text: "What is the basic unit of life?", options: ["Atom", "Cell", "Tissue", "Organ"], correctIndex: 1 },
    { text: "What are organisms that make their own food called?", options: ["Heterotrophs", "Autotrophs", "Decomposers", "Consumers"], correctIndex: 1 },
    { text: "What is the study of heredity?", options: ["Ecology", "Genetics", "Anatomy", "Physiology"], correctIndex: 1 },
    { text: "What is mitosis?", options: ["Cell death", "Cell division", "Cell fusion", "Cell respiration"], correctIndex: 1 },
    { text: "What is the largest organ in the human body?", options: ["Liver", "Skin", "Brain", "Heart"], correctIndex: 1 },
    { text: "What is osmosis?", options: ["Active transport", "Water movement across membrane", "Protein synthesis", "Cell division"], correctIndex: 1 },
    { text: "What kingdom do mushrooms belong to?", options: ["Plantae", "Fungi", "Animalia", "Protista"], correctIndex: 1 },
    { text: "What is homeostasis?", options: ["Cell division", "Maintaining stable internal conditions", "Energy production", "Reproduction"], correctIndex: 1 },
    { text: "What is the function of ribosomes?", options: ["Energy production", "Protein synthesis", "DNA storage", "Waste removal"], correctIndex: 1 },
    { text: "What is natural selection?", options: ["Random mutation", "Survival of the fittest", "Artificial breeding", "Genetic engineering"], correctIndex: 1 },
    { text: "What are the building blocks of proteins?", options: ["Nucleotides", "Amino acids", "Fatty acids", "Sugars"], correctIndex: 1 },
    { text: "What is an ecosystem?", options: ["A single species", "Community and environment", "A food chain", "A habitat only"], correctIndex: 1 },
    { text: "What is cellular respiration?", options: ["Breathing", "Converting glucose to ATP", "Photosynthesis", "Cell division"], correctIndex: 1 },
    { text: "What is a chromosome?", options: ["A protein", "DNA structure containing genes", "A cell organelle", "An enzyme"], correctIndex: 1 },
    { text: "What is the role of chloroplasts?", options: ["Protein synthesis", "Photosynthesis", "Respiration", "DNA storage"], correctIndex: 1 },
    { text: "What is biodiversity?", options: ["One species", "Variety of life", "Population size", "Habitat area"], correctIndex: 1 },
    { text: "What is a virus?", options: ["Living cell", "Non-living infectious agent", "Bacterium", "Fungus"], correctIndex: 1 },
    { text: "What is ATP?", options: ["A protein", "Energy currency of cell", "A vitamin", "An enzyme"], correctIndex: 1 },
    { text: "What is meiosis?", options: ["Mitosis", "Cell division producing gametes", "Fertilization", "Mutation"], correctIndex: 1 },
    { text: "What is the function of the nucleus?", options: ["Energy production", "Houses DNA", "Protein synthesis", "Waste removal"], correctIndex: 1 },
    { text: "What are prokaryotes?", options: ["Cells with nucleus", "Cells without nucleus", "Viruses", "Proteins"], correctIndex: 1 },
    { text: "What is symbiosis?", options: ["Competition", "Close relationship between species", "Predation", "Parasitism only"], correctIndex: 1 },
    { text: "What is evolution?", options: ["Individual change", "Change in species over time", "Extinction", "Migration"], correctIndex: 1 },
    { text: "What is the cell membrane's function?", options: ["Energy production", "Controls what enters/exits cell", "Protein synthesis", "DNA storage"], correctIndex: 1 },
    { text: "What is a mutation?", options: ["Normal variation", "Change in DNA sequence", "Cell division", "Reproduction"], correctIndex: 1 },
    { text: "What is taxonomy?", options: ["Study of cells", "Classification of organisms", "Study of evolution", "Study of ecosystems"], correctIndex: 1 },
    { text: "What is an enzyme?", options: ["DNA molecule", "Biological catalyst", "Carbohydrate", "Lipid"], correctIndex: 1 },
    { text: "What is a food chain?", options: ["Restaurant menu", "Energy transfer sequence", "Nutrient cycle", "Habitat"], correctIndex: 1 },
    { text: "What is diffusion?", options: ["Active transport", "Passive movement from high to low concentration", "Cell division", "Respiration"], correctIndex: 1 },
    { text: "What is binary fission?", options: ["Sexual reproduction", "Asexual reproduction in bacteria", "Mitosis", "Meiosis"], correctIndex: 1 },
    { text: "What is the Golgi apparatus function?", options: ["DNA storage", "Packaging and shipping proteins", "Energy production", "Photosynthesis"], correctIndex: 1 },
    { text: "What are extremophiles?", options: ["Extinct species", "Organisms in extreme conditions", "Large animals", "Tropical species"], correctIndex: 1 },
    { text: "What is a phenotype?", options: ["Genetic code", "Observable characteristics", "DNA sequence", "Chromosome number"], correctIndex: 1 },
    { text: "What is the endoplasmic reticulum?", options: ["Cell wall", "Network for protein/lipid synthesis", "Energy producer", "DNA storage"], correctIndex: 1 },
    { text: "What is adaptive radiation?", options: ["Mutation", "Diversification from common ancestor", "Extinction", "Migration"], correctIndex: 1 },
    { text: "What are vesicles?", options: ["Large organelles", "Small membrane sacs", "Proteins", "Enzymes"], correctIndex: 1 },
    { text: "What is carrying capacity?", options: ["Animal strength", "Maximum population an environment can support", "Migration distance", "Food availability"], correctIndex: 1 },
    { text: "What is a lysosome?", options: ["Energy producer", "Digestive organelle", "Protein synthesizer", "DNA storage"], correctIndex: 1 },
    { text: "What is coevolution?", options: ["Extinction", "Two species evolving together", "Individual evolution", "Rapid evolution"], correctIndex: 1 },
    { text: "What is active transport?", options: ["Passive diffusion", "Energy-requiring movement", "Osmosis", "Respiration"], correctIndex: 1 },
    { text: "What is a trophic level?", options: ["Ocean depth", "Feeding position in food chain", "Temperature zone", "Soil layer"], correctIndex: 1 },
    { text: "What are peroxisomes?", options: ["Energy producers", "Organelles breaking down toxins", "Protein makers", "DNA carriers"], correctIndex: 1 },
    { text: "What is succession in ecology?", options: ["Animal migration", "Gradual ecosystem change", "Extinction", "Food chain"], correctIndex: 1 },
    { text: "What is a plasmid?", options: ["Large chromosome", "Small circular DNA", "Protein", "Enzyme"], correctIndex: 1 },
    { text: "What is the founder effect?", options: ["First discovery", "Genetic drift from small population", "Natural selection", "Mutation"], correctIndex: 1 },
    { text: "What is chemosynthesis?", options: ["Using light for energy", "Using chemicals for energy", "Respiration", "Digestion"], correctIndex: 1 },
    { text: "What is genetic drift?", options: ["Natural selection", "Random genetic changes", "Mutation rate", "Gene flow"], correctIndex: 1 },
];
