export const botanyQuestions = [

    // Botany (50 questions)
    { text: "What is photosynthesis?", options: ["Respiration", "Plants making food from light", "Water absorption", "Root growth"], correctIndex: 1 },
    { text: "What part of the plant conducts photosynthesis?", options: ["Roots", "Leaves", "Stem", "Flowers"], correctIndex: 1 },
    { text: "What is chlorophyll?", options: ["Root structure", "Green pigment", "Flower part", "Stem tissue"], correctIndex: 1 },
    { text: "What is the male part of a flower?", options: ["Pistil", "Stamen", "Petal", "Sepal"], correctIndex: 1 },
    { text: "What is the female part of a flower?", options: ["Stamen", "Pistil", "Petal", "Anther"], correctIndex: 1 },
    { text: "What is xylem?", options: ["Root hair", "Tissue transporting water", "Flower part", "Leaf cell"], correctIndex: 1 },
    { text: "What is phloem?", options: ["Flower", "Tissue transporting nutrients", "Root", "Stem"], correctIndex: 1 },
    { text: "What are stomata?", options: ["Flowers", "Leaf pores for gas exchange", "Roots", "Seeds"], correctIndex: 1 },
    { text: "What is a monocot?", options: ["Two seed leaves", "One seed leaf", "No seed leaves", "Three seed leaves"], correctIndex: 1 },
    { text: "What is a dicot?", options: ["One seed leaf", "Two seed leaves", "No seed leaves", "Three seed leaves"], correctIndex: 1 },
    { text: "What is pollination?", options: ["Seed dispersal", "Transfer of pollen", "Water absorption", "Photosynthesis"], correctIndex: 1 },
    { text: "What is germination?", options: ["Flowering", "Seed sprouting", "Leaf falling", "Fruit ripening"], correctIndex: 1 },
    { text: "What is tropism?", options: ["Plant disease", "Growth response to stimulus", "Reproduction", "Photosynthesis"], correctIndex: 1 },
    { text: "What is phototropism?", options: ["Response to gravity", "Growth toward light", "Response to water", "Response to touch"], correctIndex: 1 },
    { text: "What is the ovary in a flower?", options: ["Male part", "Contains ovules", "Petal", "Stamen"], correctIndex: 1 },
    { text: "What are cotyledons?", options: ["Flowers", "Seed leaves", "Roots", "Stems"], correctIndex: 1 },
    { text: "What is a rhizome?", options: ["Flower", "Underground stem", "Root", "Leaf"], correctIndex: 1 },
    { text: "What is transpiration?", options: ["Respiration", "Water loss through leaves", "Photosynthesis", "Germination"], correctIndex: 1 },
    { text: "What are guard cells?", options: ["Protective layer", "Control stomata opening", "Root cells", "Flower cells"], correctIndex: 1 },
    { text: "What is a gymnosperm?", options: ["Flowering plant", "Naked seed plant", "Fern", "Moss"], correctIndex: 1 },
    { text: "What is an angiosperm?", options: ["Conifer", "Flowering plant", "Fern", "Moss"], correctIndex: 1 },
    { text: "What is cambium?", options: ["Flower", "Growth tissue", "Root tip", "Leaf vein"], correctIndex: 1 },
    { text: "What is a deciduous plant?", options: ["Evergreen", "Sheds leaves seasonally", "Never loses leaves", "No leaves"], correctIndex: 1 },
    { text: "What is the petal function?", options: ["Photosynthesis", "Attract pollinators", "Water absorption", "Support"], correctIndex: 1 },
    { text: "What is a sepal?", options: ["Petal", "Protective leaf under flower", "Stamen", "Pistil"], correctIndex: 1 },
    { text: "What is apical meristem?", options: ["Root side", "Growing tip tissue", "Flower", "Leaf base"], correctIndex: 1 },
    { text: "What is a tuber?", options: ["Flower", "Underground storage stem", "Root", "Leaf"], correctIndex: 1 },
    { text: "What is cellulose?", options: ["Protein", "Plant cell wall component", "Sugar", "Vitamin"], correctIndex: 1 },
    { text: "What is the cuticle on a leaf?", options: ["Vein", "Waxy protective layer", "Chloroplast", "Stomata"], correctIndex: 1 },
    { text: "What are root hairs?", options: ["Stem projections", "Increase absorption surface", "Flower parts", "Leaf veins"], correctIndex: 1 },
    { text: "What is a bulb?", options: ["Flower", "Underground storage structure", "Stem", "Root"], correctIndex: 1 },
    { text: "What is double fertilization?", options: ["Two pollen grains", "Two sperm fertilize egg and central cell", "Two eggs", "Two seeds"], correctIndex: 1 },
    { text: "What is the pericarp?", options: ["Seed coat", "Fruit wall", "Flower part", "Root tissue"], correctIndex: 1 },
    { text: "What is a node?", options: ["Root tip", "Point where leaf attaches to stem", "Flower center", "Seed"], correctIndex: 1 },
    { text: "What is an internode?", options: ["Flower", "Stem section between nodes", "Root section", "Leaf vein"], correctIndex: 1 },
    { text: "What is a compound leaf?", options: ["Single blade", "Multiple leaflets", "No leaf", "Modified leaf"], correctIndex: 1 },
    { text: "What is photoperiodism?", options: ["Light intensity", "Response to day length", "Color absorption", "Temperature response"], correctIndex: 1 },
    { text: "What is senescence?", options: ["Growth", "Aging and death", "Flowering", "Germination"], correctIndex: 1 },
    { text: "What is a tendril?", options: ["Root", "Climbing structure", "Flower", "Seed"], correctIndex: 1 },
    { text: "What is the endosperm?", options: ["Seed coat", "Nutrient tissue in seed", "Root", "Stem"], correctIndex: 1 },
    { text: "What is vegetative reproduction?", options: ["Sexual", "Asexual plant reproduction", "Seed formation", "Pollination"], correctIndex: 1 },
    { text: "What is lignin?", options: ["Pigment", "Woody tissue strengthener", "Sugar", "Protein"], correctIndex: 1 },
    { text: "What is a bract?", options: ["Root", "Modified leaf near flower", "Stem", "True petal"], correctIndex: 1 },
    { text: "What is the palisade mesophyll?", options: ["Root tissue", "Leaf photosynthetic layer", "Stem tissue", "Flower part"], correctIndex: 1 },
    { text: "What is abscission?", options: ["Growth", "Leaf/fruit shedding", "Flowering", "Rooting"], correctIndex: 1 },
    { text: "What is a drupe?", options: ["Dry fruit", "Fleshy fruit with stone", "Multiple fruit", "Aggregate fruit"], correctIndex: 1 },
    { text: "What are lenticels?", options: ["Leaves", "Pores in bark", "Roots", "Flowers"], correctIndex: 1 },
    { text: "What is vernalization?", options: ["Spring growth", "Cold period needed for flowering", "Fall dormancy", "Summer growth"], correctIndex: 1 },
    { text: "What is etiolation?", options: ["Normal growth", "Pale elongated growth in darkness", "Flowering", "Root growth"], correctIndex: 1 },
    { text: "What is a corm?", options: ["Root", "Short underground stem", "Flower", "Leaf"], correctIndex: 1 },
];
