export const calculusQuestions = [

    // Calculus (50 questions)
    { text: "What is the derivative of x²?", options: ["x", "2x", "x²", "2"], correctIndex: 1 },
    { text: "What is the derivative of a constant?", options: ["1", "The constant", "0", "x"], correctIndex: 2 },
    { text: "What is the integral of 1 dx?", options: ["0", "1", "x + C", "x"], correctIndex: 2 },
    { text: "What is the power rule for derivatives?", options: ["d/dx(xⁿ) = nxⁿ⁻¹", "d/dx(xⁿ) = xⁿ⁺¹", "d/dx(xⁿ) = nxⁿ", "d/dx(xⁿ) = xⁿ/n"], correctIndex: 0 },
    { text: "What is the derivative of sin(x)?", options: ["-cos(x)", "cos(x)", "-sin(x)", "tan(x)"], correctIndex: 1 },
    { text: "What is the derivative of cos(x)?", options: ["sin(x)", "-sin(x)", "-cos(x)", "tan(x)"], correctIndex: 1 },
    { text: "What is the derivative of eˣ?", options: ["xeˣ⁻¹", "eˣ", "eˣ/x", "ln(x)"], correctIndex: 1 },
    { text: "What is ∫x dx?", options: ["x²", "x²/2 + C", "2x + C", "x + C"], correctIndex: 1 },
    { text: "What is the fundamental theorem of calculus about?", options: ["Derivatives only", "Integration only", "Connection between derivatives and integrals", "Limits"], correctIndex: 2 },
    { text: "What is the derivative of ln(x)?", options: ["1/x", "x", "eˣ", "ln(x)/x"], correctIndex: 0 },
    { text: "What is lim(x→0) of sin(x)/x?", options: ["0", "1", "∞", "Undefined"], correctIndex: 1 },
    { text: "What is the chain rule?", options: ["d/dx[f(g(x))] = f'(x)g'(x)", "d/dx[f(g(x))] = f'(g(x))·g'(x)", "d/dx[f(g(x))] = f'(x) + g'(x)", "d/dx[f(g(x))] = f(x)·g'(x)"], correctIndex: 1 },
    { text: "What is the derivative of x³?", options: ["3x²", "x²", "3x", "x³/3"], correctIndex: 0 },
    { text: "What is ∫eˣ dx?", options: ["eˣ/x + C", "xeˣ + C", "eˣ + C", "eˣ⁺¹ + C"], correctIndex: 2 },
    { text: "What is the product rule?", options: ["(fg)' = f'g'", "(fg)' = f'g + fg'", "(fg)' = f' + g'", "(fg)' = fg"], correctIndex: 1 },
    { text: "What is the derivative of tan(x)?", options: ["sec(x)", "sec²(x)", "cos²(x)", "csc²(x)"], correctIndex: 1 },
    { text: "What does a derivative represent?", options: ["Area", "Volume", "Rate of change", "Distance"], correctIndex: 2 },
    { text: "What is ∫cos(x) dx?", options: ["-sin(x) + C", "sin(x) + C", "cos(x) + C", "-cos(x) + C"], correctIndex: 1 },
    { text: "What is the quotient rule?", options: ["(f/g)' = (f'g - fg')/g²", "(f/g)' = f'/g'", "(f/g)' = (f'g + fg')/g²", "(f/g)' = f'g/g'"], correctIndex: 0 },
    { text: "What is the second derivative a measure of?", options: ["Slope", "Concavity", "Area", "Volume"], correctIndex: 1 },
    { text: "What is ∫sin(x) dx?", options: ["cos(x) + C", "-cos(x) + C", "sin(x) + C", "-sin(x) + C"], correctIndex: 1 },
    { text: "What is the derivative of 5x?", options: ["5", "5x", "x", "0"], correctIndex: 0 },
    { text: "What is a critical point?", options: ["Where f'(x) = 0 or undefined", "Where f(x) = 0", "Where f''(x) = 0", "Maximum point only"], correctIndex: 0 },
    { text: "What is ∫x² dx?", options: ["2x + C", "x³ + C", "x³/3 + C", "x² + C"], correctIndex: 2 },
    { text: "What is the derivative of √x?", options: ["1/√x", "1/(2√x)", "2√x", "√x/2"], correctIndex: 1 },
    { text: "What does an integral represent geometrically?", options: ["Slope", "Rate of change", "Area under curve", "Tangent line"], correctIndex: 2 },
    { text: "What is lim(x→∞) of 1/x?", options: ["1", "∞", "0", "-1"], correctIndex: 2 },
    { text: "What is the derivative of x⁴?", options: ["4x³", "x³", "4x⁴", "x⁴/4"], correctIndex: 0 },
    { text: "What is integration by parts based on?", options: ["Chain rule", "Product rule", "Quotient rule", "Power rule"], correctIndex: 1 },
    { text: "What is the derivative of 1/x?", options: ["1/x²", "-1/x²", "1", "-1"], correctIndex: 1 },
    { text: "What is L'Hôpital's rule used for?", options: ["Finding derivatives", "Finding integrals", "Evaluating indeterminate limits", "Finding maxima"], correctIndex: 2 },
    { text: "What is the mean value theorem about?", options: ["Average values", "Existence of tangent parallel to secant", "Integration", "Limits"], correctIndex: 1 },
    { text: "What is ∫1/x dx?", options: ["x + C", "ln|x| + C", "1/x² + C", "eˣ + C"], correctIndex: 1 },
    { text: "What is the derivative of x?", options: ["0", "1", "x", "2x"], correctIndex: 1 },
    { text: "What is a local maximum?", options: ["Highest point overall", "Highest in neighborhood", "Where f'(x) = 0", "Where f''(x) > 0"], correctIndex: 1 },
    { text: "What is the derivative of 3x²?", options: ["3x", "6x", "x²", "3"], correctIndex: 1 },
    { text: "What is ∫2x dx?", options: ["2x² + C", "x² + C", "2x + C", "x²/2 + C"], correctIndex: 1 },
    { text: "What indicates a function is increasing?", options: ["f'(x) < 0", "f'(x) > 0", "f''(x) > 0", "f(x) > 0"], correctIndex: 1 },
    { text: "What is the derivative of x⁵?", options: ["5x⁴", "x⁴", "5x⁵", "x⁵/5"], correctIndex: 0 },
    { text: "What is an inflection point?", options: ["Where f'(x) = 0", "Where f''(x) = 0 and changes sign", "Maximum point", "Minimum point"], correctIndex: 1 },
    { text: "What is the derivative of 7?", options: ["7", "7x", "1", "0"], correctIndex: 3 },
    { text: "What is ∫0 dx?", options: ["0", "x", "1", "C"], correctIndex: 3 },
    { text: "What is the derivative of eˣ²?", options: ["2xeˣ²", "eˣ²", "2eˣ", "xeˣ²"], correctIndex: 0 },
    { text: "What does f''(x) > 0 indicate?", options: ["Decreasing", "Increasing", "Concave up", "Concave down"], correctIndex: 2 },
    { text: "What is the derivative of ln(2x)?", options: ["1/2x", "1/x", "2/x", "ln(2)"], correctIndex: 1 },
    { text: "What is ∫x³ dx?", options: ["3x² + C", "x⁴ + C", "x⁴/4 + C", "x³ + C"], correctIndex: 2 },
    { text: "What is the derivative of x²+3x+5?", options: ["2x+3", "x+3", "2x+8", "3x"], correctIndex: 0 },
    { text: "What is an antiderivative?", options: ["Derivative", "Integral", "Limit", "Function"], correctIndex: 1 },
    { text: "What is the derivative of csc(x)?", options: ["-csc(x)cot(x)", "csc(x)cot(x)", "-sec(x)tan(x)", "csc²(x)"], correctIndex: 0 },
    { text: "What is Rolle's theorem a special case of?", options: ["Chain rule", "Product rule", "Mean value theorem", "Fundamental theorem"], correctIndex: 2 },
];
