export const chemistryQuestions = [

    // Chemistry (50 questions)
    { text: "What is the chemical symbol for water?", options: ["H2O", "CO2", "O2", "H2O2"], correctIndex: 0 },
    { text: "What is the atomic number of carbon?", options: ["4", "6", "8", "12"], correctIndex: 1 },
    { text: "What is the smallest unit of an element?", options: ["Molecule", "Atom", "Compound", "Cell"], correctIndex: 1 },
    { text: "What is H2O2?", options: ["Water", "Hydrogen peroxide", "Hydrochloric acid", "Oxygen"], correctIndex: 1 },
    { text: "What is the pH of pure water?", options: ["0", "7", "14", "10"], correctIndex: 1 },
    { text: "What is table salt chemically?", options: ["NaCl", "KCl", "CaCl2", "MgCl2"], correctIndex: 0 },
    { text: "What is an acid?", options: ["pH above 7", "pH below 7", "pH exactly 7", "No pH"], correctIndex: 1 },
    { text: "What is the most abundant element in the universe?", options: ["Oxygen", "Hydrogen", "Carbon", "Nitrogen"], correctIndex: 1 },
    { text: "What is a covalent bond?", options: ["Electron transfer", "Electron sharing", "No electrons", "Ion attraction"], correctIndex: 1 },
    { text: "What is the chemical symbol for gold?", options: ["Go", "Au", "Gd", "Ag"], correctIndex: 1 },
    { text: "What is an ionic bond?", options: ["Electron sharing", "Electron transfer", "No electrons", "Weak attraction"], correctIndex: 1 },
    { text: "What is the periodic table?", options: ["Time chart", "Element organization", "Chemical reactions", "Lab equipment"], correctIndex: 1 },
    { text: "What is a catalyst?", options: ["Reactant", "Speeds reaction without being consumed", "Product", "Inhibitor"], correctIndex: 1 },
    { text: "What is the chemical symbol for iron?", options: ["Ir", "Fe", "In", "I"], correctIndex: 1 },
    { text: "What state of matter is plasma?", options: ["Solid", "Fourth state", "Liquid", "Gas"], correctIndex: 1 },
    { text: "What is an isotope?", options: ["Different element", "Same element, different neutrons", "Ion", "Molecule"], correctIndex: 1 },
    { text: "What is the charge of a proton?", options: ["Negative", "Positive", "Neutral", "Variable"], correctIndex: 1 },
    { text: "What is the charge of an electron?", options: ["Positive", "Negative", "Neutral", "Variable"], correctIndex: 1 },
    { text: "What is the charge of a neutron?", options: ["Positive", "Neutral", "Negative", "Variable"], correctIndex: 1 },
    { text: "What is Avogadro's number approximately?", options: ["6.02 × 10²³", "3.14", "9.8", "1.6 × 10⁻¹⁹"], correctIndex: 0 },
    { text: "What is oxidation?", options: ["Gain of electrons", "Loss of electrons", "No change", "Gain of protons"], correctIndex: 1 },
    { text: "What is reduction?", options: ["Loss of electrons", "Gain of electrons", "No change", "Loss of protons"], correctIndex: 1 },
    { text: "What is the chemical symbol for silver?", options: ["Si", "Ag", "Au", "Al"], correctIndex: 1 },
    { text: "What is a molecule?", options: ["Single atom", "Two or more atoms bonded", "Ion", "Element"], correctIndex: 1 },
    { text: "What is the noble gas in the first period?", options: ["Neon", "Helium", "Argon", "Krypton"], correctIndex: 1 },
    { text: "What is the chemical formula for methane?", options: ["CH4", "CO2", "C2H6", "CH3OH"], correctIndex: 0 },
    { text: "What is an exothermic reaction?", options: ["Absorbs heat", "Releases heat", "No heat change", "Requires light"], correctIndex: 1 },
    { text: "What is an endothermic reaction?", options: ["Releases heat", "Absorbs heat", "No heat change", "Produces light"], correctIndex: 1 },
    { text: "What is the most electronegative element?", options: ["Oxygen", "Fluorine", "Chlorine", "Nitrogen"], correctIndex: 1 },
    { text: "What is the chemical symbol for sodium?", options: ["So", "Na", "S", "N"], correctIndex: 1 },
    { text: "What is a base?", options: ["pH below 7", "pH above 7", "pH exactly 7", "Acid"], correctIndex: 1 },
    { text: "What is the valence shell?", options: ["Innermost shell", "Outermost electron shell", "Nucleus", "Core"], correctIndex: 1 },
    { text: "What is the chemical formula for carbon dioxide?", options: ["CO", "CO2", "C2O", "CO3"], correctIndex: 1 },
    { text: "What is sublimation?", options: ["Liquid to gas", "Solid to gas", "Gas to liquid", "Solid to liquid"], correctIndex: 1 },
    { text: "What is the chemical symbol for potassium?", options: ["Po", "K", "P", "Pt"], correctIndex: 1 },
    { text: "What is a polymer?", options: ["Single molecule", "Large molecule from repeating units", "Atom", "Ion"], correctIndex: 1 },
    { text: "What is the chemical formula for ammonia?", options: ["NH3", "NH4", "N2H", "N2H4"], correctIndex: 0 },
    { text: "What is electronegativity?", options: ["Positive charge", "Ability to attract electrons", "Number of electrons", "Atomic size"], correctIndex: 1 },
    { text: "What is the chemical symbol for mercury?", options: ["Me", "Hg", "Mc", "Mr"], correctIndex: 1 },
    { text: "What is a mole in chemistry?", options: ["Animal", "6.02×10²³ particles", "Weight unit", "Volume unit"], correctIndex: 1 },
    { text: "What is the chemical formula for glucose?", options: ["C6H12O6", "C12H22O11", "CH4", "C2H6O"], correctIndex: 0 },
    { text: "What is a solution?", options: ["Pure substance", "Homogeneous mixture", "Heterogeneous mixture", "Element"], correctIndex: 1 },
    { text: "What is the chemical symbol for lead?", options: ["Le", "Pb", "Ld", "L"], correctIndex: 1 },
    { text: "What is an alloy?", options: ["Pure metal", "Metal mixture", "Non-metal", "Gas"], correctIndex: 1 },
    { text: "What is the chemical formula for sulfuric acid?", options: ["HCl", "H2SO4", "HNO3", "H3PO4"], correctIndex: 1 },
    { text: "What is atomic mass?", options: ["Protons only", "Protons plus neutrons", "Electrons", "Neutrons only"], correctIndex: 1 },
    { text: "What is the chemical symbol for copper?", options: ["Co", "Cu", "Cp", "Ce"], correctIndex: 1 },
    { text: "What is activation energy?", options: ["Product energy", "Energy needed to start reaction", "Final energy", "No energy"], correctIndex: 1 },
    { text: "What is the chemical formula for ozone?", options: ["O2", "O3", "O4", "O"], correctIndex: 1 },
    { text: "What is Le Chatelier's principle about?", options: ["Elements", "Equilibrium shifts", "Bonding", "Atomic structure"], correctIndex: 1 },
];
