export const cinematographyQuestions = [

    // Cinematography (50 questions)
    { text: "What does a cinematographer do?", options: ["Direct actors", "Manage camera and lighting", "Edit footage", "Write scripts"], correctIndex: 1 },
    { text: "What is the golden hour in cinematography?", options: ["Noon", "Hour after sunrise/before sunset", "Midnight", "Mid-afternoon"], correctIndex: 1 },
    { text: "What is a long take?", options: ["Telephoto shot", "Extended continuous shot", "Wide shot", "Time-lapse"], correctIndex: 1 },
    { text: "Who was cinematographer for 'Blade Runner'?", options: ["Roger Deakins", "Jordan Cronenweth", "Vittorio Storaro", "Gordon Willis"], correctIndex: 1 },
    { text: "What is depth of field?", options: ["Camera angle", "Area in focus", "Lens type", "Lighting setup"], correctIndex: 1 },
    { text: "What does ASC stand for?", options: ["Association of Screen Cameras", "American Society of Cinematographers", "Advanced Shooting Collective", "Artistic Scene Creators"], correctIndex: 1 },
    { text: "What is a Dutch angle?", options: ["Overhead shot", "Tilted camera angle", "Low angle", "Eye level"], correctIndex: 1 },
    { text: "Who shot 'The Revenant'?", options: ["Roger Deakins", "Emmanuel Lubezki", "Robert Richardson", "Janusz Kamiński"], correctIndex: 1 },
    { text: "What is chiaroscuro lighting?", options: ["Flat lighting", "Strong contrast light/dark", "Soft diffused light", "Natural light only"], correctIndex: 1 },
    { text: "What is the 180-degree rule?", options: ["Camera rotation", "Spatial relationship consistency", "Lighting angle", "Lens aperture"], correctIndex: 1 },
    { text: "Who was cinematographer for 'The Godfather'?", options: ["Vittorio Storaro", "Gordon Willis", "Conrad Hall", "Haskell Wexler"], correctIndex: 1 },
    { text: "What is a key light?", options: ["Background light", "Main light source", "Fill light", "Rim light"], correctIndex: 1 },
    { text: "What is rack focus?", options: ["Shaky camera", "Shifting focus between subjects", "Zoom in", "Pan shot"], correctIndex: 1 },
    { text: "Who shot most Coen Brothers films?", options: ["Robert Elswit", "Roger Deakins", "Emmanuel Lubezki", "Janusz Kamiński"], correctIndex: 1 },
    { text: "What is motivated lighting?", options: ["Director's choice", "Light justified by source in scene", "Random lighting", "Studio lighting"], correctIndex: 1 },
    { text: "What does aspect ratio mean?", options: ["Camera size", "Width to height ratio", "Lens type", "Film speed"], correctIndex: 1 },
    { text: "Who was Spielberg's frequent cinematographer?", options: ["Roger Deakins", "Janusz Kamiński", "Robert Richardson", "Dante Spinotti"], correctIndex: 1 },
    { text: "What is three-point lighting?", options: ["Three cameras", "Key, fill, and back light", "Three scenes", "Three angles"], correctIndex: 1 },
    { text: "What is a dolly shot?", options: ["Handheld movement", "Camera on moving platform", "Stationary shot", "Aerial shot"], correctIndex: 1 },
    { text: "Who shot 'Apocalypse Now'?", options: ["Gordon Willis", "Vittorio Storaro", "Conrad Hall", "Sven Nykvist"], correctIndex: 1 },
    { text: "What is high-key lighting?", options: ["Intense shadows", "Bright, low contrast", "Natural light", "Colored lights"], correctIndex: 1 },
    { text: "What is a Steadicam?", options: ["Tripod", "Stabilized camera mount", "Drone", "Fixed camera"], correctIndex: 1 },
    { text: "Who was Bergman's cinematographer?", options: ["Vittorio Storaro", "Sven Nykvist", "Gordon Willis", "Conrad Hall"], correctIndex: 1 },
    { text: "What is low-key lighting?", options: ["Bright and even", "High contrast with shadows", "Natural daylight", "No lighting"], correctIndex: 1 },
    { text: "What is a crane shot?", options: ["Handheld", "Camera on crane/jib", "Ground level", "Underwater"], correctIndex: 1 },
    { text: "Who shot 'Days of Heaven'?", options: ["Gordon Willis", "Néstor Almendros", "Vittorio Storaro", "Haskell Wexler"], correctIndex: 1 },
    { text: "What is practical lighting?", options: ["Studio lights", "Visible light sources in scene", "Natural light", "Reflectors"], correctIndex: 1 },
    { text: "What is a tracking shot?", options: ["Stationary camera", "Camera follows subject", "Zoom shot", "Tilt shot"], correctIndex: 1 },
    { text: "Who was cinematographer for '1917'?", options: ["Emmanuel Lubezki", "Roger Deakins", "Robert Richardson", "Hoyte van Hoytema"], correctIndex: 1 },
    { text: "What is a prime lens?", options: ["Zoom lens", "Fixed focal length", "Wide angle only", "Telephoto only"], correctIndex: 1 },
    { text: "What is fill light?", options: ["Main light", "Softens shadows", "Background light", "Colored light"], correctIndex: 1 },
    { text: "Who shot 'In the Mood for Love'?", options: ["Roger Deakins", "Christopher Doyle", "Vittorio Storaro", "Rodrigo Prieto"], correctIndex: 1 },
    { text: "What is anamorphic format?", options: ["Square frame", "Widescreen aspect ratio", "Standard ratio", "Vertical format"], correctIndex: 1 },
    { text: "What is back light used for?", options: ["Main illumination", "Separating subject from background", "Filling shadows", "Coloring scene"], correctIndex: 1 },
    { text: "Who shot 'There Will Be Blood'?", options: ["Roger Deakins", "Robert Elswit", "Emmanuel Lubezki", "Janusz Kamiński"], correctIndex: 1 },
    { text: "What is naturalistic lighting?", options: ["Studio setup", "Mimicking real light sources", "Artificial only", "No lighting"], correctIndex: 1 },
    { text: "What is a whip pan?", options: ["Slow pan", "Fast pan creating blur", "Tilt up", "Stationary shot"], correctIndex: 1 },
    { text: "Who shot 'The Tree of Life'?", options: ["Roger Deakins", "Emmanuel Lubezki", "Robert Richardson", "Hoyte van Hoytema"], correctIndex: 1 },
    { text: "What is film grain?", options: ["Camera shake", "Texture from film particles", "Lens flare", "Color grading"], correctIndex: 1 },
    { text: "What is a zoom lens?", options: ["Fixed focal length", "Variable focal length", "Wide angle only", "Macro only"], correctIndex: 1 },
    { text: "Who shot 'Schindler's List'?", options: ["Roger Deakins", "Janusz Kamiński", "Vittorio Storaro", "Conrad Hall"], correctIndex: 1 },
    { text: "What is color temperature?", options: ["Camera heat", "Warmth/coolness of light", "Film speed", "Lens coating"], correctIndex: 1 },
    { text: "What is a matte box?", options: ["Storage container", "Lens accessory for filters", "Tripod head", "Camera bag"], correctIndex: 1 },
    { text: "Who shot 'Birdman'?", options: ["Roger Deakins", "Emmanuel Lubezki", "Robert Richardson", "Rodrigo Prieto"], correctIndex: 1 },
    { text: "What is lens flare?", options: ["Focus problem", "Light scattering in lens", "Dirt on lens", "Camera malfunction"], correctIndex: 1 },
    { text: "What is an establishing shot?", options: ["Close-up", "Wide shot showing location", "Medium shot", "Extreme close-up"], correctIndex: 1 },
    { text: "Who shot 'Gravity'?", options: ["Roger Deakins", "Emmanuel Lubezki", "Wally Pfister", "Hoyte van Hoytema"], correctIndex: 1 },
    { text: "What is film speed/ISO?", options: ["Playback speed", "Light sensitivity", "Frame rate", "Shutter speed"], correctIndex: 1 },
    { text: "What is a canted frame?", options: ["Straight horizon", "Tilted frame", "Vertical frame", "Square frame"], correctIndex: 1 },
    { text: "Who shot 'Skyfall'?", options: ["Emmanuel Lubezki", "Roger Deakins", "Robert Richardson", "Janusz Kamiński"], correctIndex: 1 },
];
