export const cold_warQuestions = [

    // Cold War (50 questions)
    { text: "What years are generally considered the Cold War?", options: ["1939-1945", "1947-1991", "1914-1918", "1950-1975"], correctIndex: 1 },
    { text: "What were the two main superpowers?", options: ["France and Britain", "USA and Soviet Union", "China and Japan", "Germany and Italy"], correctIndex: 1 },
    { text: "What does 'Cold War' mean?", options: ["Winter warfare", "Conflict without direct fighting", "Nuclear winter", "Arctic battles"], correctIndex: 1 },
    { text: "What was the Iron Curtain?", options: ["Military weapon", "Division between East and West Europe", "Soviet flag", "Border wall"], correctIndex: 1 },
    { text: "What was NATO?", options: ["Soviet alliance", "Western military alliance", "Trade agreement", "UN agency"], correctIndex: 1 },
    { text: "What was the Warsaw Pact?", options: ["Peace treaty", "Soviet alliance", "Trade deal", "Border agreement"], correctIndex: 1 },
    { text: "What was the Berlin Wall?", options: ["Ancient wall", "Division between East and West Berlin", "Defensive fortification", "Art installation"], correctIndex: 1 },
    { text: "What year was the Berlin Wall built?", options: ["1945", "1961", "1975", "1989"], correctIndex: 1 },
    { text: "What was the Marshall Plan?", options: ["Military strategy", "US aid to rebuild Europe", "Soviet policy", "Peace treaty"], correctIndex: 1 },
    { text: "What was the Cuban Missile Crisis?", options: ["Invasion", "Nuclear standoff", "Trade embargo", "Revolution"], correctIndex: 1 },
    { text: "What year did the Berlin Wall fall?", options: ["1985", "1989", "1991", "1995"], correctIndex: 1 },
    { text: "What was McCarthyism?", options: ["Economic policy", "Anti-communist witch hunts", "Foreign policy", "Military strategy"], correctIndex: 1 },
    { text: "What was the Space Race?", options: ["Athletic competition", "Competition for space supremacy", "Car racing", "Arms race"], correctIndex: 1 },
    { text: "Who was the first person in space?", options: ["Neil Armstrong", "Yuri Gagarin", "John Glenn", "Buzz Aldrin"], correctIndex: 1 },
    { text: "What was détente?", options: ["Increased tension", "Easing of tensions", "War declaration", "Alliance"], correctIndex: 1 },
    { text: "What was the Truman Doctrine?", options: ["Economic plan", "Policy to contain communism", "Trade agreement", "Military alliance"], correctIndex: 1 },
    { text: "What was the Korean War's outcome?", options: ["US victory", "Stalemate/division at 38th parallel", "Communist victory", "UN takeover"], correctIndex: 1 },
    { text: "What was the Vietnam War about?", options: ["Trade dispute", "Containing communism", "Border conflict", "Religious war"], correctIndex: 1 },
    { text: "What was MAD?", options: ["Angry diplomacy", "Mutually Assured Destruction", "Military Aid Deal", "Missile Attack Defense"], correctIndex: 1 },
    { text: "Who was the Soviet leader during the Cuban Missile Crisis?", options: ["Stalin", "Khrushchev", "Brezhnev", "Gorbachev"], correctIndex: 1 },
    { text: "What was the domino theory?", options: ["Game strategy", "If one country falls to communism, others will follow", "Economic theory", "Military tactic"], correctIndex: 1 },
    { text: "What was glasnost?", options: ["Secrecy", "Openness/transparency", "Military buildup", "Economic reform"], correctIndex: 1 },
    { text: "What was perestroika?", options: ["Military policy", "Economic restructuring", "Foreign policy", "Cultural program"], correctIndex: 1 },
    { text: "Who was the last Soviet leader?", options: ["Stalin", "Khrushchev", "Gorbachev", "Yeltsin"], correctIndex: 2 },
    { text: "What was the Prague Spring?", options: ["Music festival", "Reform movement in Czechoslovakia", "Military operation", "Trade fair"], correctIndex: 1 },
    { text: "What was the Suez Crisis about?", options: ["Trade", "Control of Suez Canal", "Religious conflict", "Border dispute"], correctIndex: 1 },
    { text: "What was SALT?", options: ["Trade agreement", "Arms limitation talks", "Peace treaty", "Economic plan"], correctIndex: 1 },
    { text: "What was the Bay of Pigs?", options: ["Beach resort", "Failed invasion of Cuba", "Naval battle", "Trade port"], correctIndex: 1 },
    { text: "Who was US President during most of the 1980s Cold War?", options: ["Carter", "Reagan", "Bush Sr.", "Nixon"], correctIndex: 1 },
    { text: "What was the Berlin Airlift?", options: ["Military operation", "Supplying West Berlin by air", "Evacuation", "Bombing campaign"], correctIndex: 1 },
    { text: "What was the U-2 incident?", options: ["Rock concert", "Spy plane shot down", "Submarine accident", "Diplomatic meeting"], correctIndex: 1 },
    { text: "What did the Soviet Union do in Afghanistan in 1979?", options: ["Trade mission", "Invaded", "Withdrew", "Made peace"], correctIndex: 1 },
    { text: "What was the purpose of the hotline between Washington and Moscow?", options: ["Trade", "Direct communication to prevent war", "Cultural exchange", "Spying"], correctIndex: 1 },
    { text: "What was Radio Free Europe?", options: ["Music station", "US-funded broadcasts to Eastern Europe", "Soviet radio", "Trade channel"], correctIndex: 1 },
    { text: "What was the Solidarity movement?", options: ["Soviet program", "Polish labor union/resistance", "NATO initiative", "UN mission"], correctIndex: 1 },
    { text: "What was the Strategic Defense Initiative (SDI)?", options: ["Trade policy", "Missile defense system", "Spy network", "Economic plan"], correctIndex: 1 },
    { text: "What happened in Hungary in 1956?", options: ["Trade fair", "Uprising crushed by Soviets", "Peace treaty", "Independence"], correctIndex: 1 },
    { text: "What was the Sino-Soviet Split?", options: ["Peace treaty", "Break between China and USSR", "Military alliance", "Trade agreement"], correctIndex: 1 },
    { text: "What was the Non-Aligned Movement?", options: ["Military alliance", "Nations not aligned with either superpower", "Trade bloc", "UN committee"], correctIndex: 1 },
    { text: "What was the Kitchen Debate?", options: ["Cooking competition", "Nixon-Khrushchev discussion", "Trade negotiation", "Food shortage"], correctIndex: 1 },
    { text: "What year did the Soviet Union dissolve?", options: ["1985", "1989", "1991", "1995"], correctIndex: 2 },
    { text: "What was the Rosenberg trial about?", options: ["Murder", "Espionage", "Theft", "Fraud"], correctIndex: 1 },
    { text: "What was the Red Scare?", options: ["Disease outbreak", "Fear of communism", "Economic crisis", "Natural disaster"], correctIndex: 1 },
    { text: "What was the Apollo-Soyuz mission?", options: ["Space race victory", "Joint US-Soviet space mission", "Military operation", "Satellite launch"], correctIndex: 1 },
    { text: "What was the Brezhnev Doctrine?", options: ["Economic theory", "Soviet right to intervene in socialist countries", "Peace initiative", "Trade policy"], correctIndex: 1 },
    { text: "What was the Test Ban Treaty?", options: ["Education agreement", "Limited nuclear testing", "Trade deal", "Military pact"], correctIndex: 1 },
    { text: "What was the purpose of the CIA during the Cold War?", options: ["Domestic policing", "Intelligence and covert operations", "Trade regulation", "Economic planning"], correctIndex: 1 },
    { text: "What was the Yalta Conference about?", options: ["Trade", "Post-WWII Europe division", "Arms control", "Cultural exchange"], correctIndex: 1 },
    { text: "What was containment policy?", options: ["Expansion", "Stopping spread of communism", "Isolation", "Free trade"], correctIndex: 1 },
    { text: "What symbolized the end of the Cold War?", options: ["Treaty signing", "Berlin Wall falling", "Space cooperation", "Trade agreement"], correctIndex: 1 },
];
