export const countriesQuestions = [

    // Countries (50 questions)
    { text: "What is the most populous country in the world?", options: ["India", "China", "United States", "Indonesia"], correctIndex: 0 },
    { text: "What is the largest country by land area?", options: ["Canada", "Russia", "China", "United States"], correctIndex: 1 },
    { text: "What country has the most time zones?", options: ["Russia", "France", "United States", "China"], correctIndex: 1 },
    { text: "What country is known as the Land of the Rising Sun?", options: ["China", "Japan", "Thailand", "Vietnam"], correctIndex: 1 },
    { text: "What is the smallest country in the world?", options: ["Monaco", "Vatican City", "San Marino", "Liechtenstein"], correctIndex: 1 },
    { text: "What country has the longest coastline?", options: ["Russia", "Canada", "Indonesia", "Australia"], correctIndex: 1 },
    { text: "What country is home to the ancient city of Petra?", options: ["Egypt", "Jordan", "Syria", "Lebanon"], correctIndex: 1 },
    { text: "What country is the Great Barrier Reef in?", options: ["Indonesia", "Australia", "Philippines", "Fiji"], correctIndex: 1 },
    { text: "What country is Mount Everest in?", options: ["India", "Nepal", "China", "Bhutan"], correctIndex: 1 },
    { text: "What country is home to the Amazon rainforest (largest portion)?", options: ["Colombia", "Brazil", "Peru", "Venezuela"], correctIndex: 1 },
    { text: "What country is known for tulips and windmills?", options: ["Belgium", "Netherlands", "Denmark", "Germany"], correctIndex: 1 },
    { text: "What country has the most pyramids?", options: ["Egypt", "Sudan", "Mexico", "Peru"], correctIndex: 1 },
    { text: "What country is Machu Picchu in?", options: ["Bolivia", "Peru", "Ecuador", "Colombia"], correctIndex: 1 },
    { text: "What country is the Taj Mahal in?", options: ["Pakistan", "India", "Bangladesh", "Nepal"], correctIndex: 1 },
    { text: "What country is known for fjords?", options: ["Sweden", "Norway", "Finland", "Iceland"], correctIndex: 1 },
    { text: "What country is Angkor Wat in?", options: ["Thailand", "Cambodia", "Vietnam", "Laos"], correctIndex: 1 },
    { text: "What country has the most islands?", options: ["Indonesia", "Sweden", "Finland", "Norway"], correctIndex: 1 },
    { text: "What country is the Sahara Desert mostly in?", options: ["Egypt", "Algeria", "Libya", "Morocco"], correctIndex: 1 },
    { text: "What country is Transylvania in?", options: ["Bulgaria", "Romania", "Hungary", "Serbia"], correctIndex: 1 },
    { text: "What country is famous for its neutral status?", options: ["Sweden", "Switzerland", "Austria", "Finland"], correctIndex: 1 },
    { text: "What country is home to the Serengeti?", options: ["Kenya", "Tanzania", "South Africa", "Botswana"], correctIndex: 1 },
    { text: "What country is both in Europe and Asia?", options: ["Russia", "Turkey", "Kazakhstan", "All of these"], correctIndex: 3 },
    { text: "What country has the most UNESCO World Heritage Sites?", options: ["China", "Italy", "Spain", "France"], correctIndex: 1 },
    { text: "What country is the Galapagos Islands part of?", options: ["Colombia", "Ecuador", "Peru", "Chile"], correctIndex: 1 },
    { text: "What country is Bali in?", options: ["Thailand", "Indonesia", "Malaysia", "Philippines"], correctIndex: 1 },
    { text: "What country is Dracula associated with?", options: ["Bulgaria", "Romania", "Hungary", "Serbia"], correctIndex: 1 },
    { text: "What country is the world's leading coffee producer?", options: ["Colombia", "Brazil", "Vietnam", "Ethiopia"], correctIndex: 1 },
    { text: "What country is Stonehenge in?", options: ["Ireland", "England", "Scotland", "Wales"], correctIndex: 1 },
    { text: "What country is home to Victoria Falls?", options: ["South Africa", "Zambia and Zimbabwe", "Botswana", "Namibia"], correctIndex: 1 },
    { text: "What country has a maple leaf on its flag?", options: ["Austria", "Canada", "Lebanon", "Poland"], correctIndex: 1 },
    { text: "What country is Timbuktu in?", options: ["Niger", "Mali", "Mauritania", "Senegal"], correctIndex: 1 },
    { text: "What country is home to Chernobyl?", options: ["Russia", "Ukraine", "Belarus", "Poland"], correctIndex: 1 },
    { text: "What country is the Parthenon in?", options: ["Italy", "Greece", "Turkey", "Cyprus"], correctIndex: 1 },
    { text: "What country is K2 (second highest mountain) in?", options: ["Nepal", "Pakistan", "India", "China"], correctIndex: 1 },
    { text: "What country is the Atacama Desert in?", options: ["Peru", "Chile", "Argentina", "Bolivia"], correctIndex: 1 },
    { text: "What country has the most lakes?", options: ["Finland", "Canada", "Sweden", "Russia"], correctIndex: 1 },
    { text: "What country is Casablanca in?", options: ["Algeria", "Morocco", "Tunisia", "Libya"], correctIndex: 1 },
    { text: "What country is the Dead Sea bordered by?", options: ["Israel", "Jordan", "Palestine", "All of these"], correctIndex: 3 },
    { text: "What country is the Leaning Tower of Pisa in?", options: ["France", "Italy", "Spain", "Greece"], correctIndex: 1 },
    { text: "What country is home to the Giant's Causeway?", options: ["Scotland", "Northern Ireland", "Ireland", "Wales"], correctIndex: 1 },
    { text: "What country invented pasta?", options: ["Greece", "Italy", "China", "Turkey"], correctIndex: 1 },
    { text: "What country is Mount Kilimanjaro in?", options: ["Kenya", "Tanzania", "Uganda", "Ethiopia"], correctIndex: 1 },
    { text: "What country is Auschwitz in?", options: ["Germany", "Poland", "Czech Republic", "Austria"], correctIndex: 1 },
    { text: "What country is home to the komodo dragon?", options: ["Thailand", "Indonesia", "Malaysia", "Philippines"], correctIndex: 1 },
    { text: "What country has a dragon on its flag?", options: ["China", "Bhutan", "Wales", "Both B and C"], correctIndex: 3 },
    { text: "What country is Drakensberg Mountains in?", options: ["Kenya", "South Africa", "Zimbabwe", "Namibia"], correctIndex: 1 },
    { text: "What country is home to the Okavango Delta?", options: ["Zambia", "Botswana", "Zimbabwe", "Namibia"], correctIndex: 1 },
    { text: "What country is the Colosseum in?", options: ["Greece", "Italy", "Turkey", "Spain"], correctIndex: 1 },
    { text: "What country is home to Patagonia?", options: ["Chile", "Argentina", "Both A and B", "Uruguay"], correctIndex: 2 },
    { text: "What country is the Hermitage Museum in?", options: ["Poland", "Russia", "Ukraine", "Finland"], correctIndex: 1 },
];
