export const earth_scienceQuestions = [

    // Earth Science (50 questions)
    { text: "What are the three types of rocks?", options: ["Hard, soft, medium", "Igneous, sedimentary, metamorphic", "Old, new, ancient", "Big, small, medium"], correctIndex: 1 },
    { text: "What causes earthquakes?", options: ["Wind", "Tectonic plate movement", "Ocean currents", "Volcanoes only"], correctIndex: 1 },
    { text: "What is the outermost layer of Earth?", options: ["Mantle", "Crust", "Core", "Lithosphere"], correctIndex: 1 },
    { text: "What is the study of weather called?", options: ["Geology", "Meteorology", "Astronomy", "Oceanography"], correctIndex: 1 },
    { text: "What is the water cycle?", options: ["Ocean currents", "Continuous movement of water", "River flow", "Tides"], correctIndex: 1 },
    { text: "What scale measures earthquake magnitude?", options: ["Beaufort", "Richter", "Celsius", "Mohs"], correctIndex: 1 },
    { text: "What is erosion?", options: ["Rock formation", "Wearing away of Earth's surface", "Volcanic activity", "Earthquake damage"], correctIndex: 1 },
    { text: "What is the Ring of Fire?", options: ["Desert region", "Volcanic/earthquake zone", "Forest fire area", "Ocean current"], correctIndex: 1 },
    { text: "What are fossils?", options: ["Living organisms", "Preserved remains of organisms", "Rocks", "Minerals"], correctIndex: 1 },
    { text: "What is the Mohs scale?", options: ["Temperature", "Mineral hardness", "Earthquake strength", "Wind speed"], correctIndex: 1 },
    { text: "What is weathering?", options: ["Predicting weather", "Breaking down of rocks", "Wind patterns", "Ocean waves"], correctIndex: 1 },
    { text: "What is the mantle?", options: ["Outermost layer", "Layer between crust and core", "Center of Earth", "Atmosphere"], correctIndex: 1 },
    { text: "What is a glacier?", options: ["Lake", "Large mass of ice", "Mountain", "Valley"], correctIndex: 1 },
    { text: "What is magma called when it reaches the surface?", options: ["Rock", "Lava", "Ash", "Steam"], correctIndex: 1 },
    { text: "What is the Pangaea?", options: ["Ocean", "Ancient supercontinent", "Mountain range", "Volcano"], correctIndex: 1 },
    { text: "What is plate tectonics?", options: ["Dinner plates", "Theory of crustal plate movement", "Ocean floor", "Atmosphere layers"], correctIndex: 1 },
    { text: "What is a tsunami?", options: ["Hurricane", "Large ocean wave from earthquake", "Tornado", "Flood"], correctIndex: 1 },
    { text: "What is the lithosphere?", options: ["Atmosphere", "Rigid outer layer of Earth", "Ocean", "Core"], correctIndex: 1 },
    { text: "What is sediment?", options: ["Lava", "Particles deposited by water/wind", "Mineral", "Rock type"], correctIndex: 1 },
    { text: "What causes tides?", options: ["Wind", "Moon's gravitational pull", "Earth's rotation only", "Ocean currents"], correctIndex: 1 },
    { text: "What is the asthenosphere?", options: ["Atmosphere layer", "Plastic layer in upper mantle", "Ocean floor", "Crust"], correctIndex: 1 },
    { text: "What is a mineral?", options: ["Living thing", "Naturally occurring inorganic solid", "Rock", "Fossil"], correctIndex: 1 },
    { text: "What is a fault line?", options: ["Border", "Fracture in Earth's crust", "River", "Mountain"], correctIndex: 1 },
    { text: "What is groundwater?", options: ["Rain", "Water beneath Earth's surface", "Ocean water", "River water"], correctIndex: 1 },
    { text: "What is the core made of primarily?", options: ["Rock", "Iron and nickel", "Silicon", "Carbon"], correctIndex: 1 },
    { text: "What is a stratovolcano?", options: ["Flat volcano", "Steep composite volcano", "Shield volcano", "Dormant volcano"], correctIndex: 1 },
    { text: "What is continental drift?", options: ["Ocean currents", "Movement of continents", "Wind patterns", "Tides"], correctIndex: 1 },
    { text: "What is a delta?", options: ["Triangle symbol", "Sediment deposit at river mouth", "Mountain", "Valley"], correctIndex: 1 },
    { text: "What is the hydrosphere?", options: ["Atmosphere", "All water on Earth", "Land", "Core"], correctIndex: 1 },
    { text: "What is subduction?", options: ["Mountain building", "One plate sliding under another", "Erosion", "Volcanic eruption"], correctIndex: 1 },
    { text: "What is a stalactite?", options: ["Floor formation", "Ceiling formation in cave", "Mineral", "Fossil"], correctIndex: 1 },
    { text: "What is the Coriolis effect?", options: ["Gravity", "Deflection of moving objects on rotating Earth", "Magnetism", "Tides"], correctIndex: 1 },
    { text: "What is loess?", options: ["Rock type", "Wind-deposited sediment", "Lava", "Ice"], correctIndex: 1 },
    { text: "What are convection currents?", options: ["Ocean waves", "Heat-driven circulation in mantle", "Wind", "Rivers"], correctIndex: 1 },
    { text: "What is a geyser?", options: ["Waterfall", "Hot spring that erupts", "River", "Lake"], correctIndex: 1 },
    { text: "What is the geologic time scale?", options: ["Daily weather", "Earth's history timeline", "Lunar cycle", "Tidal chart"], correctIndex: 1 },
    { text: "What is an aquifer?", options: ["Ocean", "Underground water-bearing rock", "River", "Lake"], correctIndex: 1 },
    { text: "What is metamorphism?", options: ["Erosion", "Rock transformation by heat/pressure", "Volcanic activity", "Weathering"], correctIndex: 1 },
    { text: "What is a moraine?", options: ["Ocean current", "Glacial debris deposit", "Mountain", "Valley"], correctIndex: 1 },
    { text: "What is the Beaufort scale?", options: ["Earthquake strength", "Wind speed", "Temperature", "Humidity"], correctIndex: 1 },
    { text: "What is an oxbow lake?", options: ["Mountain lake", "Curved lake from old river meander", "Crater lake", "Glacial lake"], correctIndex: 1 },
    { text: "What is isostasy?", options: ["Mountain formation", "Equilibrium of Earth's crust", "Erosion", "Volcanism"], correctIndex: 1 },
    { text: "What is a seamount?", options: ["Land mountain", "Underwater mountain", "Valley", "Plateau"], correctIndex: 1 },
    { text: "What is permafrost?", options: ["Frozen waterfall", "Permanently frozen ground", "Glacier", "Ice cap"], correctIndex: 1 },
    { text: "What is a rift valley?", options: ["Mountain range", "Valley from tectonic plates separating", "River valley", "Glacier valley"], correctIndex: 1 },
    { text: "What is carbonation in weathering?", options: ["Heating", "Chemical weathering by carbonic acid", "Physical breakdown", "Wind erosion"], correctIndex: 1 },
    { text: "What is a batholith?", options: ["Surface rock", "Large underground igneous formation", "Sediment", "Fossil"], correctIndex: 1 },
    { text: "What is the abyssal plain?", options: ["Mountain top", "Deep ocean floor", "Continental shelf", "Beach"], correctIndex: 1 },
    { text: "What is diagenesis?", options: ["Erosion", "Transformation of sediment to rock", "Melting", "Weathering"], correctIndex: 1 },
    { text: "What is a nunatak?", options: ["Mountain peak protruding through ice", "Valley", "River", "Ocean feature"], correctIndex: 0 },
];
