export const famous_artQuestions = [

    // Famous Paintings & Sculptures (50 questions)
    { text: "Who painted the Mona Lisa?", options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], correctIndex: 1 },
    { text: "Where is the Mona Lisa displayed?", options: ["Uffizi Gallery", "Louvre Museum", "British Museum", "Metropolitan Museum"], correctIndex: 1 },
    { text: "Who painted 'Starry Night'?", options: ["Monet", "Van Gogh", "Picasso", "Dalí"], correctIndex: 1 },
    { text: "Who sculpted 'David'?", options: ["Donatello", "Michelangelo", "Bernini", "Rodin"], correctIndex: 1 },
    { text: "Who painted the Sistine Chapel ceiling?", options: ["Leonardo", "Michelangelo", "Raphael", "Botticelli"], correctIndex: 1 },
    { text: "Who painted 'The Scream'?", options: ["Kandinsky", "Munch", "Klimt", "Schiele"], correctIndex: 1 },
    { text: "Who painted 'Guernica'?", options: ["Dalí", "Picasso", "Miró", "Gris"], correctIndex: 1 },
    { text: "Who painted 'The Persistence of Memory' with melting clocks?", options: ["Picasso", "Dalí", "Magritte", "Ernst"], correctIndex: 1 },
    { text: "Who painted 'The Birth of Venus'?", options: ["Leonardo", "Botticelli", "Titian", "Raphael"], correctIndex: 1 },
    { text: "Who painted 'Girl with a Pearl Earring'?", options: ["Rembrandt", "Vermeer", "Hals", "Van Dyck"], correctIndex: 1 },
    { text: "Who sculpted 'The Thinker'?", options: ["Michelangelo", "Rodin", "Donatello", "Bernini"], correctIndex: 1 },
    { text: "Who painted 'The Last Supper'?", options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Caravaggio"], correctIndex: 1 },
    { text: "Who painted 'American Gothic'?", options: ["Hopper", "Wood", "Whistler", "Cassatt"], correctIndex: 1 },
    { text: "Who painted 'The Kiss'?", options: ["Monet", "Klimt", "Schiele", "Munch"], correctIndex: 1 },
    { text: "Who painted 'Nighthawks'?", options: ["Wood", "Hopper", "Pollock", "Rothko"], correctIndex: 1 },
    { text: "Who created Campbell's Soup Cans?", options: ["Lichtenstein", "Warhol", "Hockney", "Johns"], correctIndex: 1 },
    { text: "Who painted 'The Garden of Earthly Delights'?", options: ["Bruegel", "Bosch", "Van Eyck", "Memling"], correctIndex: 1 },
    { text: "Who sculpted 'The Kiss' (sculpture)?", options: ["Michelangelo", "Rodin", "Bernini", "Canova"], correctIndex: 1 },
    { text: "Who painted 'Las Meninas'?", options: ["Goya", "Velázquez", "El Greco", "Murillo"], correctIndex: 1 },
    { text: "Who painted 'The Creation of Adam'?", options: ["Leonardo", "Michelangelo", "Raphael", "Botticelli"], correctIndex: 1 },
    { text: "Who painted 'Liberty Leading the People'?", options: ["David", "Delacroix", "Géricault", "Ingres"], correctIndex: 1 },
    { text: "Who painted 'The Night Watch'?", options: ["Vermeer", "Rembrandt", "Hals", "Rubens"], correctIndex: 1 },
    { text: "Who sculpted the Statue of Liberty?", options: ["Rodin", "Bartholdi", "Eiffel", "Claudel"], correctIndex: 1 },
    { text: "Who painted 'Christina's World'?", options: ["Hopper", "Wyeth", "Pollock", "Rothko"], correctIndex: 1 },
    { text: "Who painted 'A Sunday Afternoon on the Island of La Grande Jatte'?", options: ["Monet", "Seurat", "Signac", "Pissarro"], correctIndex: 1 },
    { text: "Who painted 'The Great Wave off Kanagawa'?", options: ["Hiroshige", "Hokusai", "Utamaro", "Kuniyoshi"], correctIndex: 1 },
    { text: "Who painted 'The Arnolfini Portrait'?", options: ["Bosch", "Van Eyck", "Memling", "Van der Weyden"], correctIndex: 1 },
    { text: "Who painted 'The Son of Man' (man with apple)?", options: ["Dalí", "Magritte", "Ernst", "Tanguy"], correctIndex: 1 },
    { text: "Who painted 'Whistler's Mother'?", options: ["Cassatt", "Whistler", "Sargent", "Homer"], correctIndex: 1 },
    { text: "Who painted 'The School of Athens'?", options: ["Leonardo", "Raphael", "Michelangelo", "Titian"], correctIndex: 1 },
    { text: "Who created 'Fountain' (urinal sculpture)?", options: ["Dalí", "Duchamp", "Picasso", "Brancusi"], correctIndex: 1 },
    { text: "Who painted 'Olympia'?", options: ["Monet", "Manet", "Renoir", "Degas"], correctIndex: 1 },
    { text: "Who sculpted 'Pietà'?", options: ["Donatello", "Michelangelo", "Bernini", "Canova"], correctIndex: 1 },
    { text: "Who painted 'The Third of May 1808'?", options: ["Velázquez", "Goya", "El Greco", "Zurbarán"], correctIndex: 1 },
    { text: "Who painted 'Irises'?", options: ["Monet", "Van Gogh", "Cézanne", "Gauguin"], correctIndex: 1 },
    { text: "Who painted 'Composition with Red, Blue, and Yellow'?", options: ["Kandinsky", "Mondrian", "Malevich", "Klee"], correctIndex: 1 },
    { text: "Who painted 'The Hay Wain'?", options: ["Turner", "Constable", "Gainsborough", "Reynolds"], correctIndex: 1 },
    { text: "Who painted 'Bal du moulin de la Galette'?", options: ["Monet", "Renoir", "Degas", "Pissarro"], correctIndex: 1 },
    { text: "Who painted 'Number 1A, 1948' (drip painting)?", options: ["Rothko", "Pollock", "De Kooning", "Kline"], correctIndex: 1 },
    { text: "Who painted 'The Raft of the Medusa'?", options: ["Delacroix", "Géricault", "David", "Ingres"], correctIndex: 1 },
    { text: "Who painted 'Saturn Devouring His Son'?", options: ["Velázquez", "Goya", "El Greco", "Ribera"], correctIndex: 1 },
    { text: "Who sculpted 'The Gates of Hell'?", options: ["Michelangelo", "Rodin", "Bernini", "Donatello"], correctIndex: 1 },
    { text: "Who painted 'At the Moulin Rouge'?", options: ["Degas", "Toulouse-Lautrec", "Renoir", "Manet"], correctIndex: 1 },
    { text: "Who painted 'The Two Fridas'?", options: ["O'Keeffe", "Kahlo", "Cassatt", "Carr"], correctIndex: 1 },
    { text: "Who painted 'Broadway Boogie Woogie'?", options: ["Kandinsky", "Mondrian", "Klee", "Albers"], correctIndex: 1 },
    { text: "Who painted 'Bathers at Asnières'?", options: ["Monet", "Seurat", "Cézanne", "Renoir"], correctIndex: 1 },
    { text: "Who painted 'The Fighting Temeraire'?", options: ["Constable", "Turner", "Blake", "Reynolds"], correctIndex: 1 },
    { text: "Who painted 'No. 61 (Rust and Blue)'?", options: ["Pollock", "Rothko", "Newman", "Still"], correctIndex: 1 },
    { text: "Who painted 'Self-Portrait with Thorn Necklace and Hummingbird'?", options: ["Cassatt", "Kahlo", "O'Keeffe", "Neel"], correctIndex: 1 },
    { text: "Who painted 'Dance at Le Moulin de la Galette'?", options: ["Monet", "Renoir", "Degas", "Caillebotte"], correctIndex: 1 },
];
