export const foodQuestions = [

    // Food (50 questions)
    { text: "What is the main ingredient in hummus?", options: ["Lentils", "Chickpeas", "Black beans", "Peas"], correctIndex: 1 },
    { text: "What is sushi traditionally wrapped in?", options: ["Lettuce", "Seaweed (nori)", "Rice paper", "Banana leaf"], correctIndex: 1 },
    { text: "What is the main ingredient in guacamole?", options: ["Tomatoes", "Avocado", "Peppers", "Onions"], correctIndex: 1 },
    { text: "What vitamin is abundant in citrus fruits?", options: ["Vitamin A", "Vitamin C", "Vitamin D", "Vitamin K"], correctIndex: 1 },
    { text: "What is tofu made from?", options: ["Chickpeas", "Soybeans", "Wheat", "Rice"], correctIndex: 1 },
    { text: "What gives bread its rise?", options: ["Sugar", "Yeast", "Salt", "Butter"], correctIndex: 1 },
    { text: "What is the main ingredient in traditional Japanese miso soup?", options: ["Rice", "Fermented soybean paste", "Seaweed only", "Fish"], correctIndex: 1 },
    { text: "What is gelatin made from?", options: ["Plants", "Animal collagen", "Seaweed", "Fruit pectin"], correctIndex: 1 },
    { text: "What spice is derived from the crocus flower?", options: ["Turmeric", "Saffron", "Paprika", "Cinnamon"], correctIndex: 1 },
    { text: "What is the main ingredient in a traditional Greek moussaka?", options: ["Potato", "Eggplant", "Zucchini", "Cabbage"], correctIndex: 1 },
    { text: "What is umami?", options: ["Sweet taste", "Fifth basic taste (savory)", "Spicy", "Bitter"], correctIndex: 1 },
    { text: "What is caramelization?", options: ["Adding caramel", "Browning sugar through heat", "Melting", "Freezing"], correctIndex: 1 },
    { text: "What is the difference between baking soda and baking powder?", options: ["Same thing", "Baking powder contains acid", "Color", "Size"], correctIndex: 1 },
    { text: "What is quinoa?", options: ["Rice variety", "Seed/pseudocereal", "Bean", "Grain"], correctIndex: 1 },
    { text: "What is the main ingredient in traditional Indian dal?", options: ["Rice", "Lentils", "Chickpeas", "Wheat"], correctIndex: 1 },
    { text: "What is gluten?", options: ["Sugar", "Protein in wheat", "Fat", "Vitamin"], correctIndex: 1 },
    { text: "What is the difference between stock and broth?", options: ["No difference", "Stock uses bones, broth uses meat", "Color only", "Temperature"], correctIndex: 1 },
    { text: "What is clarified butter called in Indian cuisine?", options: ["Butter oil", "Ghee", "Desi", "Makhan"], correctIndex: 1 },
    { text: "What is the main ingredient in tahini?", options: ["Chickpeas", "Sesame seeds", "Sunflower seeds", "Peanuts"], correctIndex: 1 },
    { text: "What is kombucha?", options: ["Tea", "Fermented tea drink", "Mushroom", "Seaweed"], correctIndex: 1 },
    { text: "What is the Maillard reaction?", options: ["Caramelization", "Browning of proteins and sugars", "Fermentation", "Rising"], correctIndex: 1 },
    { text: "What is kimchi?", options: ["Japanese dish", "Korean fermented vegetables", "Chinese noodles", "Thai curry"], correctIndex: 1 },
    { text: "What is the main difference between white and brown rice?", options: ["Color only", "Brown has bran and germ", "Size", "Taste only"], correctIndex: 1 },
    { text: "What is pesto traditionally made with?", options: ["Spinach", "Basil", "Parsley", "Cilantro"], correctIndex: 1 },
    { text: "What is the main ingredient in falafel?", options: ["Lentils", "Chickpeas or fava beans", "Black beans", "Peas"], correctIndex: 1 },
    { text: "What is tempeh?", options: ["Tofu", "Fermented soybean cake", "Seaweed", "Mushroom"], correctIndex: 1 },
    { text: "What is a roux?", options: ["Sauce", "Flour and fat mixture", "Spice blend", "Bread"], correctIndex: 1 },
    { text: "What is the main ingredient in traditional aioli?", options: ["Mayonnaise", "Garlic and oil", "Butter", "Cream"], correctIndex: 1 },
    { text: "What is the difference between jam and jelly?", options: ["Sugar content", "Jam has fruit pieces, jelly is smooth", "Color", "No difference"], correctIndex: 1 },
    { text: "What is nutritional yeast?", options: ["Baking yeast", "Deactivated yeast with B vitamins", "Live yeast", "Bread starter"], correctIndex: 1 },
    { text: "What is the smoke point of oil?", options: ["Color change", "Temperature it starts smoking", "Boiling point", "Freezing point"], correctIndex: 1 },
    { text: "What is seitan made from?", options: ["Soybeans", "Wheat gluten", "Rice", "Mushrooms"], correctIndex: 1 },
    { text: "What is the main ingredient in traditional pho broth?", options: ["Chicken", "Beef bones", "Pork", "Fish"], correctIndex: 1 },
    { text: "What is the difference between Dutch process and natural cocoa?", options: ["Origin", "Alkalization treatment", "Sugar content", "Color only"], correctIndex: 1 },
    { text: "What is sumac?", options: ["Herb", "Spice from berries", "Salt", "Pepper"], correctIndex: 1 },
    { text: "What is the main ingredient in traditional carbonara sauce?", options: ["Cream", "Eggs and cheese", "Butter", "Oil"], correctIndex: 1 },
    { text: "What is a bouquet garni?", options: ["Garnish", "Herb bundle", "Sauce", "Bread"], correctIndex: 1 },
    { text: "What is the main difference between sorbet and sherbet?", options: ["Temperature", "Sherbet contains dairy", "Color", "Sugar content"], correctIndex: 1 },
    { text: "What is harissa?", options: ["Cheese", "North African chili paste", "Bread", "Rice dish"], correctIndex: 1 },
    { text: "What is the main ingredient in traditional baba ganoush?", options: ["Chickpeas", "Eggplant", "Zucchini", "Peppers"], correctIndex: 1 },
    { text: "What is rendered fat from duck or goose called?", options: ["Lard", "Confit", "Tallow", "Schmaltz"], correctIndex: 1 },
    { text: "What is the difference between parsley varieties?", options: ["Color", "Flat-leaf vs curly", "Size only", "No difference"], correctIndex: 1 },
    { text: "What is zaatar?", options: ["Grain", "Middle Eastern spice blend", "Bread", "Cheese"], correctIndex: 1 },
    { text: "What is the main ingredient in traditional hollandaise sauce?", options: ["Cream", "Egg yolk and butter", "Oil", "Cheese"], correctIndex: 1 },
    { text: "What is the difference between cake flour and all-purpose flour?", options: ["Color", "Protein content", "Brand", "No difference"], correctIndex: 1 },
    { text: "What is mirin?", options: ["Soy sauce", "Sweet rice wine", "Vinegar", "Sake"], correctIndex: 1 },
    { text: "What is the main characteristic of extra virgin olive oil?", options: ["Color", "Cold-pressed, low acidity", "Brand", "Price"], correctIndex: 1 },
    { text: "What is the main ingredient in traditional tzatziki?", options: ["Sour cream", "Greek yogurt", "Mayonnaise", "Cream cheese"], correctIndex: 1 },
    { text: "What is the purpose of resting dough?", options: ["Cooling", "Gluten relaxation", "Rising only", "Drying"], correctIndex: 1 },
    { text: "What is the difference between stock and au jus?", options: ["No difference", "Au jus is meat drippings", "Color", "Thickness"], correctIndex: 1 },
];
