export const forensicsQuestions = [

    // Forensics (50 questions)
    { text: "What is forensic science?", options: ["Study of forests", "Science applied to law", "Medical science", "Computer science"], correctIndex: 1 },
    { text: "What is DNA profiling used for?", options: ["Dating fossils", "Identifying individuals", "Weather prediction", "Plant classification"], correctIndex: 1 },
    { text: "What is rigor mortis?", options: ["Death certificate", "Stiffening after death", "Cause of death", "Crime scene"], correctIndex: 1 },
    { text: "What is a fingerprint?", options: ["Blood type", "Unique skin ridge pattern", "Hair sample", "DNA sample"], correctIndex: 1 },
    { text: "What is ballistics?", options: ["Study of ballet", "Study of firearms and bullets", "Study of balance", "Study of chemicals"], correctIndex: 1 },
    { text: "What is livor mortis?", options: ["Stiffening", "Blood pooling after death", "Decomposition", "Time of death"], correctIndex: 1 },
    { text: "What is toxicology?", options: ["Study of taxes", "Study of poisons and drugs", "Study of tools", "Study of textiles"], correctIndex: 1 },
    { text: "What is the Locard Exchange Principle?", options: ["Money exchange", "Every contact leaves a trace", "DNA matching", "Time calculation"], correctIndex: 1 },
    { text: "What is luminol used for?", options: ["Lighting", "Detecting blood", "Finding fingerprints", "DNA extraction"], correctIndex: 1 },
    { text: "What is a chain of custody?", options: ["Prison system", "Evidence documentation trail", "Criminal record", "Court procedure"], correctIndex: 1 },
    { text: "What is entomology in forensics?", options: ["Study of entries", "Study of insects for death investigation", "Study of evidence", "Study of weapons"], correctIndex: 1 },
    { text: "What is questioned document examination?", options: ["Quiz analysis", "Document authenticity analysis", "Reading comprehension", "Translation"], correctIndex: 1 },
    { text: "What is CODIS?", options: ["Code system", "DNA database", "Crime code", "Court system"], correctIndex: 1 },
    { text: "What is blood spatter analysis?", options: ["Blood type", "Pattern interpretation", "DNA testing", "Chemical analysis"], correctIndex: 1 },
    { text: "What is GSR?", options: ["General Search Radius", "Gunshot Residue", "Ground Surface Reading", "Genetic Sample Registry"], correctIndex: 1 },
    { text: "What is algor mortis?", options: ["Stiffening", "Body cooling after death", "Blood pooling", "Decomposition"], correctIndex: 1 },
    { text: "What is a latent fingerprint?", options: ["Visible print", "Hidden print requiring development", "Bloody print", "Molded print"], correctIndex: 1 },
    { text: "What is autopsy?", options: ["Car examination", "Post-mortem examination", "Crime scene analysis", "DNA test"], correctIndex: 1 },
    { text: "What is trace evidence?", options: ["Following suspects", "Small physical evidence", "Witness testimony", "Video footage"], correctIndex: 1 },
    { text: "What is serology?", options: ["Serial numbers", "Body fluid analysis", "Crime series", "Sequence analysis"], correctIndex: 1 },
    { text: "What is anthropology in forensics?", options: ["Study of ants", "Human remains identification", "Cultural studies", "Ancient artifacts"], correctIndex: 1 },
    { text: "What is presumptive testing?", options: ["Assuming guilt", "Preliminary screening test", "Final proof", "DNA analysis"], correctIndex: 1 },
    { text: "What is confirmatory testing?", options: ["Preliminary test", "Definitive verification test", "Witness confirmation", "Alibi check"], correctIndex: 1 },
    { text: "What is a comparison microscope?", options: ["Regular microscope", "Side-by-side specimen comparison", "Digital microscope", "Electron microscope"], correctIndex: 1 },
    { text: "What is striations analysis?", options: ["Road markings", "Bullet/tool mark comparison", "Fabric analysis", "Paper analysis"], correctIndex: 1 },
    { text: "What is odontology in forensics?", options: ["Smell analysis", "Dental identification", "Bone analysis", "Bite analysis only"], correctIndex: 1 },
    { text: "What is AFIS?", options: ["Automated Fire Investigation System", "Automated Fingerprint Identification System", "Advanced Forensic Imaging System", "Analysis of Firearm Identification Standards"], correctIndex: 1 },
    { text: "What is chromatography used for?", options: ["Color analysis only", "Separating mixture components", "Photography", "Time analysis"], correctIndex: 1 },
    { text: "What is a control sample?", options: ["Suspect sample", "Known comparison sample", "Contaminated sample", "Crime scene sample"], correctIndex: 1 },
    { text: "What is putrefaction?", options: ["Preservation", "Decomposition", "Freezing", "Mummification"], correctIndex: 1 },
    { text: "What is voiceprint analysis?", options: ["Fingerprints", "Voice pattern identification", "Printer analysis", "Typewriter analysis"], correctIndex: 1 },
    { text: "What is a forensic pathologist?", options: ["Crime scene investigator", "Medical doctor examining deaths", "Lab technician", "Police detective"], correctIndex: 1 },
    { text: "What is stippling?", options: ["Paint dots", "Gunpowder residue pattern", "Blood drops", "Fingerprint pattern"], correctIndex: 1 },
    { text: "What is forensic botany?", options: ["Garden crimes", "Plant evidence analysis", "Tree dating", "Flower identification"], correctIndex: 1 },
    { text: "What is mitochondrial DNA used for?", options: ["Recent samples", "Degraded/old samples", "Blood typing", "Fingerprinting"], correctIndex: 1 },
    { text: "What is impression evidence?", options: ["Opinions", "Marks left by objects", "Memories", "Photographs"], correctIndex: 1 },
    { text: "What is the primary purpose of crime scene photography?", options: ["Art", "Documenting evidence", "Identification", "Publicity"], correctIndex: 1 },
    { text: "What is superglue fuming?", options: ["Fixing objects", "Developing latent prints", "Drug detection", "Blood detection"], correctIndex: 1 },
    { text: "What is accelerant detection?", options: ["Speed measurement", "Finding fire-starting substances", "Drug testing", "Explosive detection"], correctIndex: 1 },
    { text: "What is a forensic sketch?", options: ["Art project", "Crime scene diagram", "Suspect portrait", "Evidence photo"], correctIndex: 1 },
    { text: "What is hair analysis used for?", options: ["DNA only", "Species/characteristics determination", "Dating only", "Color only"], correctIndex: 1 },
    { text: "What is blood typing?", options: ["Keyboard type", "ABO/Rh classification", "DNA profiling", "Age determination"], correctIndex: 1 },
    { text: "What is digital forensics?", options: ["Finger analysis", "Electronic evidence recovery", "Digital photography", "Number analysis"], correctIndex: 1 },
    { text: "What is a presumptive blood test?", options: ["Definitive test", "Initial screening test", "DNA test", "Type test"], correctIndex: 1 },
    { text: "What is tool mark analysis?", options: ["Tool identification", "Comparing marks to tools", "Tool dating", "Tool quality"], correctIndex: 1 },
    { text: "What is arson investigation?", options: ["Arrow study", "Fire cause determination", "Art theft", "Architecture study"], correctIndex: 1 },
    { text: "What is a DNA exclusion?", options: ["Match found", "Sample doesn't match", "Contamination", "Error"], correctIndex: 1 },
    { text: "What is forensic psychology?", options: ["Crime solving", "Applying psychology to legal issues", "Mental health", "Behavior prediction"], correctIndex: 1 },
    { text: "What is time of death estimation based on?", options: ["One factor", "Multiple body changes", "Witness testimony", "Location only"], correctIndex: 1 },
    { text: "What is class evidence?", options: ["School evidence", "Evidence narrowing to group", "Individual evidence", "Best evidence"], correctIndex: 1 },
];
