export const geneticsQuestions = [

    // Genetics (50 questions)
    { text: "What is a gene?", options: ["A cell", "Hereditary unit of DNA", "A chromosome", "A protein"], correctIndex: 1 },
    { text: "What does DNA stand for?", options: ["Deoxyribonucleic acid", "Dinitrogen acid", "Dynamic nucleic acid", "Double nuclear acid"], correctIndex: 0 },
    { text: "What is a dominant allele?", options: ["Recessive gene", "Expressed when present", "Mutation", "Chromosome"], correctIndex: 1 },
    { text: "What is heredity?", options: ["Evolution", "Passing traits to offspring", "Mutation", "Adaptation"], correctIndex: 1 },
    { text: "Who is the father of genetics?", options: ["Darwin", "Gregor Mendel", "Watson", "Crick"], correctIndex: 1 },
    { text: "What is a genotype?", options: ["Physical appearance", "Genetic makeup", "Mutation", "Chromosome number"], correctIndex: 1 },
    { text: "What is a phenotype?", options: ["Genetic code", "Observable traits", "DNA sequence", "Gene location"], correctIndex: 1 },
    { text: "How many chromosomes do humans have?", options: ["23", "46", "48", "44"], correctIndex: 1 },
    { text: "What is a recessive allele?", options: ["Always expressed", "Expressed only with two copies", "Dominant", "Mutation"], correctIndex: 1 },
    { text: "What is a mutation?", options: ["Normal variation", "Change in DNA", "Evolution", "Reproduction"], correctIndex: 1 },
    { text: "What determines biological sex in humans?", options: ["Environment", "X and Y chromosomes", "Age", "Diet"], correctIndex: 1 },
    { text: "What is RNA?", options: ["A protein", "Ribonucleic acid", "A lipid", "A carbohydrate"], correctIndex: 1 },
    { text: "What is a Punnett square used for?", options: ["Measuring DNA", "Predicting offspring traits", "Counting chromosomes", "Sequencing genes"], correctIndex: 1 },
    { text: "What is genetic variation?", options: ["Identical genetics", "Differences in DNA among individuals", "Mutation only", "Extinction"], correctIndex: 1 },
    { text: "What is an allele?", options: ["A chromosome", "Version of a gene", "A cell", "A protein"], correctIndex: 1 },
    { text: "What is genetic engineering?", options: ["Natural selection", "Deliberate DNA modification", "Evolution", "Inheritance"], correctIndex: 1 },
    { text: "What is a karyotype?", options: ["Cell type", "Visual chromosome arrangement", "Gene sequence", "Protein structure"], correctIndex: 1 },
    { text: "What is co-dominance?", options: ["One allele dominates", "Both alleles expressed equally", "Recessive only", "No expression"], correctIndex: 1 },
    { text: "What is incomplete dominance?", options: ["Full dominance", "Blended expression", "No expression", "Recessive only"], correctIndex: 1 },
    { text: "What is a carrier?", options: ["Person with disease", "Person with one recessive allele", "Chromosome", "Gene"], correctIndex: 1 },
    { text: "What is gene expression?", options: ["DNA replication", "Gene information being used", "Mutation", "Inheritance"], correctIndex: 1 },
    { text: "What is a chromosome?", options: ["A protein", "DNA package", "A cell", "An enzyme"], correctIndex: 1 },
    { text: "What is hereditary?", options: ["Learned behavior", "Genetically passed", "Environmental", "Random"], correctIndex: 1 },
    { text: "What is genetic drift?", options: ["Natural selection", "Random genetic changes", "Mutation", "Migration"], correctIndex: 1 },
    { text: "What is a genome?", options: ["One gene", "Complete set of DNA", "One chromosome", "A protein"], correctIndex: 1 },
    { text: "What is PCR?", options: ["Protein creation", "DNA amplification technique", "Cell division", "Gene deletion"], correctIndex: 1 },
    { text: "What is a genetic disorder?", options: ["Infection", "Disease caused by genetic abnormality", "Injury", "Virus"], correctIndex: 1 },
    { text: "What is crossing over?", options: ["Cell division", "Exchange of DNA between chromosomes", "Mutation", "Replication"], correctIndex: 1 },
    { text: "What is homozygous?", options: ["Different alleles", "Two identical alleles", "One allele", "No alleles"], correctIndex: 1 },
    { text: "What is heterozygous?", options: ["Identical alleles", "Different alleles", "No alleles", "Three alleles"], correctIndex: 1 },
    { text: "What is a pedigree in genetics?", options: ["Dog breed", "Family genetic history diagram", "Gene sequence", "Chromosome map"], correctIndex: 1 },
    { text: "What is cloning?", options: ["Sexual reproduction", "Creating genetic copy", "Mutation", "Evolution"], correctIndex: 1 },
    { text: "What is gene therapy?", options: ["Exercise", "Treating disease by modifying genes", "Surgery", "Medication"], correctIndex: 1 },
    { text: "What is linkage in genetics?", options: ["Genes far apart", "Genes close on chromosome inherited together", "Mutation", "Dominance"], correctIndex: 1 },
    { text: "What is a nucleotide?", options: ["Protein", "DNA/RNA building block", "Cell", "Chromosome"], correctIndex: 1 },
    { text: "What is the Human Genome Project?", options: ["Cloning humans", "Mapping human DNA", "Gene therapy", "Evolution study"], correctIndex: 1 },
    { text: "What is epigenetics?", options: ["Mutation", "Gene expression changes without DNA changes", "Evolution", "Inheritance"], correctIndex: 1 },
    { text: "What is a codon?", options: ["Protein", "Three nucleotide sequence", "Chromosome", "Cell"], correctIndex: 1 },
    { text: "What is transcription in genetics?", options: ["Translation", "DNA to RNA", "RNA to protein", "Cell division"], correctIndex: 1 },
    { text: "What is translation in genetics?", options: ["DNA to RNA", "RNA to protein", "Replication", "Mutation"], correctIndex: 1 },
    { text: "What is CRISPR?", options: ["Protein", "Gene editing tool", "Chromosome", "Cell type"], correctIndex: 1 },
    { text: "What is a point mutation?", options: ["Large deletion", "Single nucleotide change", "Chromosome duplication", "No change"], correctIndex: 1 },
    { text: "What is polyploidy?", options: ["One chromosome set", "Extra chromosome sets", "Missing chromosomes", "Normal chromosomes"], correctIndex: 1 },
    { text: "What is genetic recombination?", options: ["No change", "Mixing of genetic material", "Mutation only", "Deletion"], correctIndex: 1 },
    { text: "What is Down syndrome caused by?", options: ["Missing chromosome", "Extra chromosome 21", "Mutation", "Deletion"], correctIndex: 1 },
    { text: "What is a sex-linked trait?", options: ["Autosomal", "Gene on sex chromosome", "Always dominant", "No inheritance"], correctIndex: 1 },
    { text: "What is the central dogma of molecular biology?", options: ["Protein to DNA", "DNA to RNA to protein", "RNA to DNA", "Protein to RNA"], correctIndex: 1 },
    { text: "What is a frameshift mutation?", options: ["Point mutation", "Insertion/deletion changing reading frame", "Silent mutation", "No effect"], correctIndex: 1 },
    { text: "What is genetic counseling?", options: ["Therapy", "Advising on genetic risks", "Gene editing", "Cloning"], correctIndex: 1 },
    { text: "What is a transgenic organism?", options: ["Natural hybrid", "Organism with foreign DNA", "Mutant", "Clone"], correctIndex: 1 },
];
