export const geographyQuestions = [

    // Geography
    { text: "What is the capital of Japan?", options: ["Seoul", "Beijing", "Tokyo", "Bangkok"], correctIndex: 2 },
    { text: "Which is the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correctIndex: 3 },
    { text: "In which country is Mount Everest located?", options: ["India", "Nepal", "China", "Bhutan"], correctIndex: 1 },
    { text: "What is the longest river in the world?", options: ["Amazon", "Nile", "Yangtze", "Mississippi"], correctIndex: 1 },
    { text: "Which continent has the most countries?", options: ["Asia", "Africa", "Europe", "South America"], correctIndex: 1 },
    { text: "What is the largest desert in the world?", options: ["Sahara", "Gobi", "Antarctic Desert", "Arabian Desert"], correctIndex: 2 },
    { text: "Which country is known as the Land of the Rising Sun?", options: ["China", "South Korea", "Japan", "Vietnam"], correctIndex: 2 },
    { text: "What is the smallest country in the world by area?", options: ["Monaco", "Nauru", "Vatican City", "San Marino"], correctIndex: 2 },
    { text: "Which river flows through Paris?", options: ["Rhône", "Seine", "Loire", "Garonne"], correctIndex: 1 },
    { text: "What is the largest island in the world?", options: ["Greenland", "New Guinea", "Borneo", "Madagascar"], correctIndex: 0 },
    { text: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Canberra", "Brisbane"], correctIndex: 2 },
    { text: "What is the largest country in the world by land area?", options: ["Canada", "Russia", "China", "United States"], correctIndex: 1 },
    { text: "Which country does the Amazon River primarily flow through?", options: ["Colombia", "Brazil", "Peru", "Venezuela"], correctIndex: 1 },
    { text: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Montreal", "Ottawa"], correctIndex: 3 },
    { text: "Which mountain range forms the natural border between Europe and Asia?", options: ["Alps", "Himalayas", "Ural Mountains", "Caucasus"], correctIndex: 2 },
    { text: "What is the capital of Brazil?", options: ["Rio de Janeiro", "São Paulo", "Brasília", "Salvador"], correctIndex: 2 },
    { text: "Which sea separates Europe from Africa?", options: ["Red Sea", "Black Sea", "Mediterranean Sea", "Caspian Sea"], correctIndex: 2 },
    { text: "What is the capital of Argentina?", options: ["Lima", "Santiago", "Bogotá", "Buenos Aires"], correctIndex: 3 },
    { text: "Which country has the most natural lakes?", options: ["Russia", "USA", "Finland", "Canada"], correctIndex: 3 },
    { text: "What is the longest mountain range in the world?", options: ["Rocky Mountains", "Alps", "Himalayas", "Andes"], correctIndex: 3 },
    { text: "Which African country has the largest population?", options: ["South Africa", "Egypt", "Ethiopia", "Nigeria"], correctIndex: 3 },
    { text: "What is the capital of Egypt?", options: ["Alexandria", "Luxor", "Cairo", "Giza"], correctIndex: 2 },
    { text: "In which country is Machu Picchu located?", options: ["Bolivia", "Peru", "Ecuador", "Colombia"], correctIndex: 1 },
    { text: "What is the deepest lake in the world?", options: ["Lake Baikal", "Lake Superior", "Caspian Sea", "Lake Tanganyika"], correctIndex: 0 },
    { text: "What is the capital of India?", options: ["Mumbai", "New Delhi", "Kolkata", "Chennai"], correctIndex: 1 },
    { text: "Which ocean is the smallest?", options: ["Pacific", "Atlantic", "Southern", "Arctic"], correctIndex: 3 },
    { text: "What is the name of the strait that connects the Atlantic and Pacific oceans?", options: ["Bosphorus", "Strait of Hormuz", "Strait of Gibraltar", "Strait of Magellan"], correctIndex: 3 },
    { text: "Which country is the largest in Africa by area?", options: ["Nigeria", "Algeria", "South Africa", "Democratic Republic of Congo"], correctIndex: 1 },
    { text: "What is the capital of Mexico?", options: ["Guadalajara", "Monterrey", "Tijuana", "Mexico City"], correctIndex: 3 },
    { text: "Which river is the longest in Europe?", options: ["Rhine", "Danube", "Volga", "Thames"], correctIndex: 2 },
    { text: "What is the capital of Russia?", options: ["St. Petersburg", "Moscow", "Novosibirsk", "Vladivostok"], correctIndex: 1 },
    { text: "Which country is home to the Great Barrier Reef?", options: ["Australia", "New Zealand", "Philippines", "Indonesia"], correctIndex: 0 },
    { text: "What is the capital of Germany?", options: ["Munich", "Hamburg", "Frankfurt", "Berlin"], correctIndex: 3 },
    { text: "Which continent is the smallest by land area?", options: ["Europe", "Australia", "Antarctica", "South America"], correctIndex: 1 },
    { text: "Which country has the longest coastline in the world?", options: ["Russia", "Australia", "Norway", "Canada"], correctIndex: 3 },
    { text: "What is the capital of South Korea?", options: ["Busan", "Incheon", "Seoul", "Daegu"], correctIndex: 2 },
    { text: "What is the capital of Turkey?", options: ["Istanbul", "Izmir", "Antalya", "Ankara"], correctIndex: 3 },
    { text: "Which is the highest waterfall in the world?", options: ["Niagara Falls", "Victoria Falls", "Angel Falls", "Iguazu Falls"], correctIndex: 2 },
    { text: "What is the capital of Spain?", options: ["Barcelona", "Madrid", "Seville", "Valencia"], correctIndex: 1 },
    { text: "What is the official language of Brazil?", options: ["Spanish", "Portuguese", "French", "English"], correctIndex: 1 },
    { text: "Which mountain is the highest peak in North America?", options: ["Mount Logan", "Pikes Peak", "Denali", "Mount Whitney"], correctIndex: 2 },
    { text: "What is the capital of Italy?", options: ["Milan", "Naples", "Venice", "Rome"], correctIndex: 3 },
    { text: "Which body of water is the saltiest in the world?", options: ["Dead Sea", "Red Sea", "Mediterranean Sea", "Caspian Sea"], correctIndex: 0 },
    { text: "What is the capital of France?", options: ["Lyon", "Marseille", "Paris", "Bordeaux"], correctIndex: 2 },
    { text: "What is the capital of Greece?", options: ["Thessaloniki", "Athens", "Heraklion", "Corfu"], correctIndex: 1 },
    { text: "Which country is considered both part of Europe and Asia?", options: ["Georgia", "Azerbaijan", "Kazakhstan", "Turkey"], correctIndex: 3 },
    { text: "What is the name of the world's largest tropical rainforest?", options: ["Congo Rainforest", "Amazon Rainforest", "Daintree Rainforest", "Tongass Rainforest"], correctIndex: 1 },
    { text: "Which country is home to the Serengeti National Park?", options: ["Kenya", "Tanzania", "South Africa", "Botswana"], correctIndex: 1 },
    { text: "What is the capital of South Africa's executive government?", options: ["Cape Town", "Johannesburg", "Durban", "Pretoria"], correctIndex: 3 },
    { text: "Which Scandinavian country is the largest by area?", options: ["Denmark", "Finland", "Norway", "Sweden"], correctIndex: 2 },
];
