export const geometryQuestions = [

    // Geometry (50 questions)
    { text: "What is the sum of angles in a triangle?", options: ["90°", "180°", "360°", "270°"], correctIndex: 1 },
    { text: "What is the area formula for a circle?", options: ["πr", "2πr", "πr²", "2πr²"], correctIndex: 2 },
    { text: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "What is the Pythagorean theorem?", options: ["a + b = c", "a² + b² = c²", "a² - b² = c²", "ab = c²"], correctIndex: 1 },
    { text: "What is the perimeter of a square with side length 5?", options: ["10", "25", "20", "15"], correctIndex: 2 },
    { text: "What is the volume of a cube with side length 3?", options: ["9", "18", "27", "6"], correctIndex: 2 },
    { text: "How many degrees are in a right angle?", options: ["45°", "90°", "180°", "60°"], correctIndex: 1 },
    { text: "What is the area of a triangle with base 6 and height 4?", options: ["24", "10", "12", "20"], correctIndex: 2 },
    { text: "What is the circumference formula for a circle?", options: ["πr²", "2πr", "πd", "Both 2πr and πd"], correctIndex: 3 },
    { text: "How many faces does a cube have?", options: ["4", "6", "8", "12"], correctIndex: 1 },
    { text: "What is a polygon with 5 sides called?", options: ["Pentagon", "Hexagon", "Heptagon", "Octagon"], correctIndex: 0 },
    { text: "What is the sum of angles in a quadrilateral?", options: ["180°", "270°", "360°", "540°"], correctIndex: 2 },
    { text: "What is the area of a rectangle with length 8 and width 3?", options: ["11", "22", "24", "16"], correctIndex: 2 },
    { text: "What type of triangle has all sides equal?", options: ["Isosceles", "Scalene", "Equilateral", "Right"], correctIndex: 2 },
    { text: "What is the diagonal of a square with side length 5?", options: ["5", "10", "5√2", "25"], correctIndex: 2 },
    { text: "How many vertices does a cube have?", options: ["6", "8", "12", "4"], correctIndex: 1 },
    { text: "What is the volume formula for a sphere?", options: ["4πr²", "4/3πr³", "πr³", "2/3πr³"], correctIndex: 1 },
    { text: "What is a line segment that connects two points on a circle?", options: ["Radius", "Diameter", "Chord", "Arc"], correctIndex: 2 },
    { text: "What is the area of a parallelogram with base 7 and height 5?", options: ["12", "35", "70", "25"], correctIndex: 1 },
    { text: "How many edges does a cube have?", options: ["6", "8", "12", "10"], correctIndex: 2 },
    { text: "What is an angle greater than 90° but less than 180° called?", options: ["Acute", "Right", "Obtuse", "Straight"], correctIndex: 2 },
    { text: "What is the surface area of a cube with side length 4?", options: ["64", "96", "48", "16"], correctIndex: 1 },
    { text: "What are two angles that add up to 90° called?", options: ["Supplementary", "Complementary", "Vertical", "Adjacent"], correctIndex: 1 },
    { text: "What is the area of a trapezoid with bases 5 and 9 and height 4?", options: ["28", "56", "14", "36"], correctIndex: 0 },
    { text: "How many sides does an octagon have?", options: ["6", "7", "8", "9"], correctIndex: 2 },
    { text: "What is the volume of a cylinder with radius 3 and height 5?", options: ["15π", "30π", "45π", "75π"], correctIndex: 2 },
    { text: "What is a 180° angle called?", options: ["Right", "Straight", "Obtuse", "Reflex"], correctIndex: 1 },
    { text: "What is the longest side of a right triangle called?", options: ["Base", "Height", "Hypotenuse", "Leg"], correctIndex: 2 },
    { text: "What is the area of a circle with radius 4?", options: ["4π", "8π", "16π", "2π"], correctIndex: 2 },
    { text: "What are angles on opposite sides of intersecting lines called?", options: ["Adjacent", "Complementary", "Vertical", "Supplementary"], correctIndex: 2 },
    { text: "What is the perimeter of a rectangle with length 7 and width 3?", options: ["10", "21", "20", "14"], correctIndex: 2 },
    { text: "How many degrees in a complete circle?", options: ["180°", "270°", "360°", "90°"], correctIndex: 2 },
    { text: "What is the volume of a cone with radius 3 and height 4?", options: ["12π", "36π", "9π", "16π"], correctIndex: 0 },
    { text: "What is a polygon with 10 sides called?", options: ["Nonagon", "Decagon", "Hendecagon", "Dodecagon"], correctIndex: 1 },
    { text: "What is the surface area formula for a sphere?", options: ["2πr²", "4πr²", "πr²", "4/3πr³"], correctIndex: 1 },
    { text: "What are two angles that add up to 180° called?", options: ["Complementary", "Supplementary", "Vertical", "Acute"], correctIndex: 1 },
    { text: "What is the area of an equilateral triangle with side length 6?", options: ["18", "9√3", "18√3", "36"], correctIndex: 1 },
    { text: "What is a quadrilateral with exactly one pair of parallel sides?", options: ["Parallelogram", "Rectangle", "Trapezoid", "Rhombus"], correctIndex: 2 },
    { text: "What is the radius of a circle with diameter 10?", options: ["20", "5", "10", "2.5"], correctIndex: 1 },
    { text: "What is the sum of interior angles in a pentagon?", options: ["360°", "540°", "720°", "900°"], correctIndex: 1 },
    { text: "What is a parallelogram with all sides equal called?", options: ["Rectangle", "Square", "Rhombus", "Trapezoid"], correctIndex: 2 },
    { text: "What is the midpoint of a line segment from (0,0) to (6,8)?", options: ["(3,4)", "(6,8)", "(4,6)", "(2,2)"], correctIndex: 0 },
    { text: "What is the volume of a rectangular prism with dimensions 2×3×4?", options: ["9", "24", "12", "20"], correctIndex: 1 },
    { text: "What is an angle less than 90° called?", options: ["Right", "Obtuse", "Acute", "Straight"], correctIndex: 2 },
    { text: "What is the distance formula between points (x₁,y₁) and (x₂,y₂)?", options: ["√[(x₂-x₁) + (y₂-y₁)]", "√[(x₂-x₁)² + (y₂-y₁)²]", "(x₂-x₁)² + (y₂-y₁)²", "√[(x₂+x₁)² + (y₂+y₁)²]"], correctIndex: 1 },
    { text: "How many diagonals does a pentagon have?", options: ["3", "5", "7", "10"], correctIndex: 1 },
    { text: "What is the area of a square with diagonal 10?", options: ["100", "50", "25", "75"], correctIndex: 1 },
    { text: "What is the measure of each interior angle in a regular hexagon?", options: ["90°", "108°", "120°", "135°"], correctIndex: 2 },
    { text: "What is a line that touches a circle at exactly one point?", options: ["Secant", "Chord", "Tangent", "Radius"], correctIndex: 2 },
    { text: "What is the ratio of a circle's circumference to its diameter?", options: ["e", "π", "φ", "2"], correctIndex: 1 },
];
