export const graphic_designQuestions = [

    // Graphic Design (50 questions)
    { text: "What does CMYK stand for?", options: ["Color My Yellow Key", "Cyan Magenta Yellow Key", "Create Mix Yellow Kit", "Color Mode Year Kelvin"], correctIndex: 1 },
    { text: "What does RGB stand for?", options: ["Red Green Blue", "Real Good Bright", "Radiant Graphic Blend", "Red Gray Black"], correctIndex: 0 },
    { text: "What is kerning?", options: ["Corner rounding", "Space between letters", "Font size", "Line height"], correctIndex: 1 },
    { text: "What is a vector graphic?", options: ["Bitmap image", "Scalable mathematical graphic", "Low resolution", "3D model"], correctIndex: 1 },
    { text: "What does DPI stand for?", options: ["Dots Per Inch", "Digital Pixel Input", "Design Print Interface", "Data Point Identifier"], correctIndex: 0 },
    { text: "What is leading?", options: ["Letter spacing", "Space between lines", "Margin size", "Font weight"], correctIndex: 1 },
    { text: "What is a serif font?", options: ["Sans decorative strokes", "Font with decorative strokes", "Script font", "Monospace font"], correctIndex: 1 },
    { text: "What is negative space?", options: ["Dark areas", "Empty space around objects", "Shadows", "Background color"], correctIndex: 1 },
    { text: "Who designed the 'I ❤ NY' logo?", options: ["Paul Rand", "Milton Glaser", "Saul Bass", "Massimo Vignelli"], correctIndex: 1 },
    { text: "What is the golden ratio approximately?", options: ["1.414", "1.618", "2.0", "3.14"], correctIndex: 1 },
    { text: "What is tracking in typography?", options: ["Line spacing", "Overall letter spacing", "Word spacing", "Paragraph spacing"], correctIndex: 1 },
    { text: "What does UI stand for?", options: ["Universal Interface", "User Interface", "Uniform Integration", "Unique Input"], correctIndex: 1 },
    { text: "What does UX stand for?", options: ["User Extension", "User Experience", "Unique Execution", "Universal Export"], correctIndex: 1 },
    { text: "Who designed the IBM logo?", options: ["Milton Glaser", "Paul Rand", "Saul Bass", "Herb Lubalin"], correctIndex: 1 },
    { text: "What is a mood board?", options: ["Calendar", "Visual inspiration collection", "Color palette", "Font list"], correctIndex: 1 },
    { text: "What is hierarchy in design?", options: ["Rank of designers", "Visual importance arrangement", "File organization", "Color order"], correctIndex: 1 },
    { text: "What is lorem ipsum?", options: ["Latin font", "Placeholder text", "Design style", "Color system"], correctIndex: 1 },
    { text: "What is a monogram?", options: ["Single color", "Combined initials design", "One font design", "Single page layout"], correctIndex: 1 },
    { text: "Who designed the FedEx logo (with hidden arrow)?", options: ["Paul Rand", "Lindon Leader", "Milton Glaser", "Saul Bass"], correctIndex: 1 },
    { text: "What is the Pantone Matching System?", options: ["Font system", "Standardized color system", "Layout grid", "Print method"], correctIndex: 1 },
    { text: "What is bleed in printing?", options: ["Ink smudge", "Extended print area", "Color mixing", "Paper type"], correctIndex: 1 },
    { text: "What does PDF stand for?", options: ["Print Document File", "Portable Document Format", "Public Design Format", "Perfect Digital File"], correctIndex: 1 },
    { text: "What is gestalt in design?", options: ["German font", "Perception principles", "Color theory", "Grid system"], correctIndex: 1 },
    { text: "Who designed the Coca-Cola script logo?", options: ["Paul Rand", "Frank Mason Robinson", "Milton Glaser", "Saul Bass"], correctIndex: 1 },
    { text: "What is a glyph?", options: ["Symbol or character", "Font family", "Color code", "Design style"], correctIndex: 0 },
    { text: "What is contrast in design?", options: ["Color only", "Difference between elements", "Brightness", "Size"], correctIndex: 1 },
    { text: "What is a favicon?", options: ["Favorite design", "Website icon", "File format", "Font style"], correctIndex: 1 },
    { text: "Who founded the Bauhaus school?", options: ["Le Corbusier", "Walter Gropius", "Ludwig Mies van der Rohe", "Josef Albers"], correctIndex: 1 },
    { text: "What is rasterization?", options: ["Vector creation", "Converting to pixels", "Color adjustment", "Resizing"], correctIndex: 1 },
    { text: "What is the rule of odds?", options: ["Odd numbers more appealing", "Page numbers", "Color mixing", "Font sizing"], correctIndex: 0 },
    { text: "What is a style guide?", options: ["Fashion guide", "Brand consistency document", "Font catalog", "Color wheel"], correctIndex: 1 },
    { text: "Who designed the NBC peacock logo?", options: ["Paul Rand", "John J. Graham", "Milton Glaser", "Saul Bass"], correctIndex: 1 },
    { text: "What is white space also called?", options: ["Empty space", "Negative space", "Void space", "Clean space"], correctIndex: 1 },
    { text: "What is a ligature in typography?", options: ["Letter connection", "Connected characters", "Font weight", "Line style"], correctIndex: 1 },
    { text: "What does EPS stand for?", options: ["Electronic Print System", "Encapsulated PostScript", "Extended Pixel Standard", "Enhanced Photo Size"], correctIndex: 1 },
    { text: "Who designed the Apple logo?", options: ["Steve Jobs", "Rob Janoff", "Paul Rand", "Milton Glaser"], correctIndex: 1 },
    { text: "What is complementary color?", options: ["Similar colors", "Opposite on color wheel", "Matching colors", "Primary colors"], correctIndex: 1 },
    { text: "What is a widow in typography?", options: ["Missing character", "Single word on last line", "Font error", "Spacing issue"], correctIndex: 1 },
    { text: "What is the Fibonacci sequence used for in design?", options: ["Color mixing", "Proportions and composition", "Font sizing", "Page numbering"], correctIndex: 1 },
    { text: "Who designed the Peace symbol?", options: ["Milton Glaser", "Gerald Holtom", "Paul Rand", "Saul Bass"], correctIndex: 1 },
    { text: "What is an orphan in typography?", options: ["Missing font", "Single word starting new page", "Spacing error", "Character issue"], correctIndex: 1 },
    { text: "What is a swatch?", options: ["Design sample", "Color sample", "Font sample", "Layout sample"], correctIndex: 1 },
    { text: "What does TIFF stand for?", options: ["Total Image File Format", "Tagged Image File Format", "Technical Interface For Files", "Transparent Image For Formats"], correctIndex: 1 },
    { text: "Who designed movie posters for Hitchcock films?", options: ["Milton Glaser", "Saul Bass", "Paul Rand", "Massimo Vignelli"], correctIndex: 1 },
    { text: "What is the primary use of CMYK?", options: ["Web design", "Print design", "Animation", "Photography"], correctIndex: 1 },
    { text: "What is a drop cap?", options: ["Lowercase letter", "Large first letter", "Font style", "Spacing method"], correctIndex: 1 },
    { text: "What is the primary use of RGB?", options: ["Print", "Digital screens", "Photography only", "Painting"], correctIndex: 1 },
    { text: "What is visual weight?", options: ["File size", "Perceived importance", "Color brightness", "Font size"], correctIndex: 1 },
    { text: "What is a grid system?", options: ["Color palette", "Layout structure framework", "Font collection", "Image gallery"], correctIndex: 1 },
    { text: "Who designed the Swiss International Style?", options: ["Paul Rand", "Josef Müller-Brockmann and others", "Milton Glaser", "Saul Bass"], correctIndex: 1 },
];
