export const historyQuestions = [

    // History
    { text: "In what year did World War II end?", options: ["1943", "1944", "1945", "1946"], correctIndex: 2 },
    { text: "Who was the first president of the United States?", options: ["Thomas Jefferson", "John Adams", "George Washington", "Benjamin Franklin"], correctIndex: 2 },
    { text: "The French Revolution began in which year?", options: ["1776", "1789", "1799", "1815"], correctIndex: 1 },
    { text: "Which ancient wonder was said to have been in Babylon?", options: ["Pyramids of Giza", "Colossus of Rhodes", "Hanging Gardens", "Lighthouse of Alexandria"], correctIndex: 2 },
    { text: "Who wrote the 95 Theses that sparked the Protestant Reformation?", options: ["John Calvin", "Martin Luther", "Ulrich Zwingli", "Henry VIII"], correctIndex: 1 },
    { text: "What was the primary cause of the American Civil War?", options: ["Taxation without representation", "Slavery", "Religious differences", "Territorial disputes"], correctIndex: 1 },
    { text: "In which year did the Titanic sink?", options: ["1912", "1914", "1916", "1918"], correctIndex: 0 },
    { text: "Who was the first emperor of Rome?", options: ["Julius Caesar", "Nero", "Augustus", "Constantine"], correctIndex: 2 },
    { text: "Which empire was known for its terracotta warriors?", options: ["Han Dynasty", "Tang Dynasty", "Qin Dynasty", "Ming Dynasty"], correctIndex: 2 },
    { text: "What was the primary language of the Byzantine Empire?", options: ["Latin", "Greek", "Syriac", "Coptic"], correctIndex: 1 },
    { text: "Who was the last ruling pharaoh of Ancient Egypt?", options: ["Hatshepsut", "Tutankhamun", "Cleopatra VII", "Ramesses II"], correctIndex: 2 },
    { text: "Which explorer is credited with leading the first expedition to circumnavigate the globe?", options: ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "James Cook"], correctIndex: 2 },
    { text: "What was the primary cause of the Hundred Years' War?", options: ["Religious differences", "Territorial disputes", "Trade disagreements", "Succession to the French throne"], correctIndex: 3 },
    { text: "Who was the first woman to fly solo across the Atlantic Ocean?", options: ["Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"], correctIndex: 0 },
    { text: "What was the main commodity traded along the Silk Road?", options: ["Spices", "Silk", "Tea", "Porcelain"], correctIndex: 1 },
    { text: "Which empire was the largest in history by land area?", options: ["British Empire", "Mongol Empire", "Roman Empire", "Spanish Empire"], correctIndex: 0 },
    { text: "Who was the first woman to win a Nobel Prize?", options: ["Marie Curie", "Rosalind Franklin", "Ada Lovelace", "Florence Nightingale"], correctIndex: 0 },
    { text: "In which year did the Berlin Wall fall?", options: ["1987", "1989", "1991", "1993"], correctIndex: 1 },
    { text: "Who was the primary author of the Declaration of Independence?", options: ["George Washington", "Benjamin Franklin", "Thomas Jefferson", "John Adams"], correctIndex: 2 },
    { text: "What was the name of the first manned mission to land on the Moon?", options: ["Apollo 10", "Apollo 11", "Apollo 12", "Apollo 13"], correctIndex: 1 },
    { text: "Who was the leader of Nazi Germany during World War II?", options: ["Joseph Stalin", "Benito Mussolini", "Francisco Franco", "Adolf Hitler"], correctIndex: 3 },
    { text: "In which year did the United States declare independence?", options: ["1774", "1775", "1776", "1777"], correctIndex: 2 },
    { text: "Which ancient Greek philosopher was the teacher of Alexander the Great?", options: ["Socrates", "Plato", "Aristotle", "Pythagoras"], correctIndex: 2 },
    { text: "Which dynasty built most of the Great Wall of China that stands today?", options: ["Han Dynasty", "Tang Dynasty", "Ming Dynasty", "Qing Dynasty"], correctIndex: 2 },
    { text: "Who was the first to sail around Africa to reach Asia by sea?", options: ["Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama", "Bartholomeu Dias"], correctIndex: 2 },
    { text: "In which city was Abraham Lincoln assassinated?", options: ["New York", "Philadelphia", "Washington D.C.", "Richmond"], correctIndex: 2 },
    { text: "What was the name of the ship that carried the Pilgrims to America in 1620?", options: ["Santa Maria", "Mayflower", "Discovery", "Pinta"], correctIndex: 1 },
    { text: "Which country was the first to grant women the right to vote?", options: ["United States", "United Kingdom", "France", "New Zealand"], correctIndex: 3 },
    { text: "Who invented the printing press?", options: ["Leonardo da Vinci", "Galileo Galilei", "Johannes Gutenberg", "Isaac Newton"], correctIndex: 2 },
    { text: "Which battle marked the final defeat of Napoleon Bonaparte?", options: ["Battle of Trafalgar", "Battle of Austerlitz", "Battle of Waterloo", "Battle of Leipzig"], correctIndex: 2 },
    { text: "What year did World War I begin?", options: ["1912", "1914", "1916", "1918"], correctIndex: 1 },
    { text: "Which country was the first to industrialize during the Industrial Revolution?", options: ["France", "Germany", "United States", "Great Britain"], correctIndex: 3 },
    { text: "Who led India's independence movement through nonviolent resistance?", options: ["Jawaharlal Nehru", "Subhas Chandra Bose", "Mahatma Gandhi", "Bal Gangadhar Tilak"], correctIndex: 2 },
    { text: "In which year did the Soviet Union collapse?", options: ["1989", "1990", "1991", "1992"], correctIndex: 2 },
    { text: "Who was the first African American to serve as U.S. President?", options: ["Barack Obama", "Colin Powell", "Frederick Douglass", "Thurgood Marshall"], correctIndex: 0 },
    { text: "What was the name of the first atomic bomb dropped on Japan?", options: ["Fat Man", "Big Boy", "Little Boy", "Thin Man"], correctIndex: 2 },
    { text: "Which country launched the first artificial satellite, Sputnik 1?", options: ["United States", "China", "Soviet Union", "Germany"], correctIndex: 2 },
    { text: "Who was the longest-reigning monarch in British history?", options: ["King George III", "Queen Victoria", "King Edward VII", "Queen Elizabeth II"], correctIndex: 3 },
    { text: "Which ancient Roman city was destroyed by the eruption of Mount Vesuvius?", options: ["Athens", "Carthage", "Pompeii", "Alexandria"], correctIndex: 2 },
    { text: "Which war ended with the signing of the Treaty of Versailles?", options: ["World War I", "World War II", "Korean War", "Franco-Prussian War"], correctIndex: 0 },
    { text: "Who was the first female Prime Minister of the United Kingdom?", options: ["Margaret Thatcher", "Theresa May", "Jacinda Ardern", "Angela Merkel"], correctIndex: 0 },
    { text: "In which country were the first modern Olympic Games held in 1896?", options: ["Italy", "Greece", "France", "Germany"], correctIndex: 1 },
    { text: "Who led the Cuban Revolution?", options: ["Che Guevara", "Raúl Castro", "Fidel Castro", "José Martí"], correctIndex: 2 },
    { text: "Which ancient civilization developed the first known writing system?", options: ["Egyptian", "Sumerian", "Greek", "Chinese"], correctIndex: 1 },
    { text: "What event triggered the start of World War I?", options: ["Invasion of Poland", "Assassination of Archduke Franz Ferdinand", "Sinking of the Lusitania", "Russian Revolution"], correctIndex: 1 },
    { text: "Who was the Roman general who crossed the Rubicon and triggered a civil war?", options: ["Pompey", "Crassus", "Mark Antony", "Julius Caesar"], correctIndex: 3 },
    { text: "Which document, signed in 1215, limited the power of the English king?", options: ["The Domesday Book", "The Bill of Rights", "Magna Carta", "The Petition of Right"], correctIndex: 2 },
    { text: "What was the name of the economic policy adopted by the Soviet Union in the 1920s?", options: ["The Five-Year Plan", "Glasnost", "New Economic Policy", "Perestroika"], correctIndex: 2 },
    { text: "In which decade did Nelson Mandela become President of South Africa?", options: ["1980s", "1990s", "2000s", "2010s"], correctIndex: 1 },
    { text: "Which country dropped atomic bombs on Japan in 1945?", options: ["United Kingdom", "Soviet Union", "France", "United States"], correctIndex: 3 },
];
