export const human_anatomyQuestions = [

    // Human Anatomy (50 questions)
    { text: "What is the largest organ in the human body?", options: ["Liver", "Skin", "Brain", "Heart"], correctIndex: 1 },
    { text: "How many bones are in the adult human body?", options: ["186", "206", "226", "246"], correctIndex: 1 },
    { text: "What is the strongest muscle in the human body?", options: ["Bicep", "Masseter (jaw)", "Quadriceps", "Heart"], correctIndex: 1 },
    { text: "What is the smallest bone in the human body?", options: ["Stapes (in ear)", "Pinky bone", "Toe bone", "Wrist bone"], correctIndex: 0 },
    { text: "What is the body's largest artery?", options: ["Pulmonary artery", "Aorta", "Carotid artery", "Femoral artery"], correctIndex: 1 },
    { text: "How many chambers does the heart have?", options: ["2", "4", "3", "5"], correctIndex: 1 },
    { text: "What is the femur?", options: ["Arm bone", "Thigh bone", "Skull bone", "Rib"], correctIndex: 1 },
    { text: "What organ produces insulin?", options: ["Liver", "Pancreas", "Kidney", "Spleen"], correctIndex: 1 },
    { text: "What is the main function of red blood cells?", options: ["Fight infection", "Carry oxygen", "Clot blood", "Digest food"], correctIndex: 1 },
    { text: "What is the cerebrum?", options: ["Heart chamber", "Largest brain part", "Bone", "Muscle"], correctIndex: 1 },
    { text: "What connects muscle to bone?", options: ["Ligaments", "Tendons", "Cartilage", "Nerves"], correctIndex: 1 },
    { text: "What connects bone to bone?", options: ["Tendons", "Ligaments", "Muscles", "Cartilage"], correctIndex: 1 },
    { text: "What is the trachea?", options: ["Food pipe", "Windpipe", "Blood vessel", "Nerve"], correctIndex: 1 },
    { text: "What is the smallest functional unit of the kidney?", options: ["Neuron", "Nephron", "Alveolus", "Villus"], correctIndex: 1 },
    { text: "What is the mandible?", options: ["Skull top", "Jawbone", "Cheekbone", "Nose bone"], correctIndex: 1 },
    { text: "What is the function of the liver?", options: ["Pump blood", "Detoxification and metabolism", "Breathe", "Digest only"], correctIndex: 1 },
    { text: "What are alveoli?", options: ["Blood cells", "Air sacs in lungs", "Bone cells", "Muscle fibers"], correctIndex: 1 },
    { text: "What is the spinal cord part of?", options: ["Digestive system", "Nervous system", "Circulatory system", "Respiratory system"], correctIndex: 1 },
    { text: "What is the pituitary gland called?", options: ["Kidney gland", "Master gland", "Liver gland", "Heart gland"], correctIndex: 1 },
    { text: "What are the three types of blood vessels?", options: ["Red, white, blue", "Arteries, veins, capillaries", "Large, medium, small", "Fast, slow, stopped"], correctIndex: 1 },
    { text: "What is the diaphragm?", options: ["Heart valve", "Breathing muscle", "Brain part", "Bone"], correctIndex: 1 },
    { text: "What is the retina?", options: ["Ear part", "Light-sensitive eye layer", "Nose part", "Tongue part"], correctIndex: 1 },
    { text: "What is the esophagus?", options: ["Windpipe", "Food tube to stomach", "Intestine", "Blood vessel"], correctIndex: 1 },
    { text: "What is cartilage?", options: ["Bone", "Flexible connective tissue", "Muscle", "Nerve"], correctIndex: 1 },
    { text: "What is the function of white blood cells?", options: ["Carry oxygen", "Fight infection", "Clot blood", "Transport nutrients"], correctIndex: 1 },
    { text: "What is the scapula?", options: ["Kneecap", "Shoulder blade", "Collarbone", "Breastbone"], correctIndex: 1 },
    { text: "What is the cornea?", options: ["Ear part", "Clear front eye layer", "Brain part", "Nose part"], correctIndex: 1 },
    { text: "What is the largest internal organ?", options: ["Heart", "Liver", "Stomach", "Brain"], correctIndex: 1 },
    { text: "What is the clavicle?", options: ["Shoulder blade", "Collarbone", "Breastbone", "Rib"], correctIndex: 1 },
    { text: "What produces bile?", options: ["Pancreas", "Liver", "Gallbladder", "Stomach"], correctIndex: 1 },
    { text: "What is the medulla oblongata?", options: ["Bone", "Brain stem part", "Muscle", "Organ"], correctIndex: 1 },
    { text: "What are the three types of muscle tissue?", options: ["Red, white, pink", "Skeletal, cardiac, smooth", "Fast, slow, medium", "Strong, weak, normal"], correctIndex: 1 },
    { text: "What is the patella?", options: ["Elbow", "Kneecap", "Ankle", "Wrist"], correctIndex: 1 },
    { text: "What is the cochlea?", options: ["Eye part", "Inner ear spiral", "Nose part", "Throat part"], correctIndex: 1 },
    { text: "What is plasma?", options: ["Red blood cells", "Liquid part of blood", "White blood cells", "Platelets"], correctIndex: 1 },
    { text: "What is the sternum?", options: ["Rib", "Breastbone", "Collarbone", "Shoulder blade"], correctIndex: 1 },
    { text: "What are the meninges?", options: ["Muscles", "Brain/spinal cord membranes", "Bones", "Organs"], correctIndex: 1 },
    { text: "What is the function of platelets?", options: ["Carry oxygen", "Blood clotting", "Fight infection", "Digest food"], correctIndex: 1 },
    { text: "What is the epiglottis?", options: ["Bone", "Flap covering windpipe when swallowing", "Muscle", "Organ"], correctIndex: 1 },
    { text: "What are nephrons?", options: ["Brain cells", "Kidney filtering units", "Muscle fibers", "Bone cells"], correctIndex: 1 },
    { text: "What is the cerebellum responsible for?", options: ["Breathing", "Coordination and balance", "Digestion", "Hearing"], correctIndex: 1 },
    { text: "What is the iris?", options: ["Pupil", "Colored eye part", "White of eye", "Retina"], correctIndex: 1 },
    { text: "What are the tonsils?", options: ["Bones", "Lymphatic tissue", "Muscles", "Nerves"], correctIndex: 1 },
    { text: "What is the hypothalamus?", options: ["Bone", "Brain region regulating body", "Muscle", "Organ"], correctIndex: 1 },
    { text: "What are villi?", options: ["Blood cells", "Small intestine projections", "Lung sacs", "Brain cells"], correctIndex: 1 },
    { text: "What is the radius?", options: ["Leg bone", "Forearm bone", "Skull bone", "Rib"], correctIndex: 1 },
    { text: "What produces red blood cells?", options: ["Liver", "Bone marrow", "Spleen", "Kidneys"], correctIndex: 1 },
    { text: "What is the uvula?", options: ["Tongue part", "Hanging tissue in throat", "Tooth", "Gum"], correctIndex: 1 },
    { text: "What are bronchi?", options: ["Blood vessels", "Airways to lungs", "Nerves", "Bones"], correctIndex: 1 },
    { text: "What is the thyroid gland function?", options: ["Digestion", "Metabolism regulation", "Breathing", "Circulation"], correctIndex: 1 },
];
