export const impressionismQuestions = [
    // Impressionism (50 questions)
    { text: "Who is considered the father of Impressionism?", options: ["Vincent van Gogh", "Claude Monet", "Pablo Picasso", "Leonardo da Vinci"], correctIndex: 1 },
    { text: "What does Impressionism focus on?", options: ["Religious themes", "Light and color effects", "Abstract shapes", "Political statements"], correctIndex: 1 },
    { text: "Where did Impressionism originate?", options: ["Italy", "France", "Spain", "Germany"], correctIndex: 1 },
    { text: "What painting gave Impressionism its name?", options: ["Water Lilies", "Impression, Sunrise", "Starry Night", "The Scream"], correctIndex: 1 },
    { text: "Who painted 'Water Lilies'?", options: ["Renoir", "Monet", "Degas", "Manet"], correctIndex: 1 },
    { text: "What technique involves small brush strokes of color?", options: ["Sfumato", "Pointillism", "Chiaroscuro", "Impasto"], correctIndex: 1 },
    { text: "Which artist is famous for ballet dancer paintings?", options: ["Monet", "Degas", "Renoir", "Pissarro"], correctIndex: 1 },
    { text: "What did Impressionists prefer to paint?", options: ["Studio scenes", "Outdoor scenes", "Religious icons", "Abstract concepts"], correctIndex: 1 },
    { text: "Who painted 'Luncheon of the Boating Party'?", options: ["Monet", "Renoir", "Degas", "Cézanne"], correctIndex: 1 },
    { text: "What time period did Impressionism emerge?", options: ["1600s", "1870s", "1920s", "1950s"], correctIndex: 1 },
    { text: "Which artist painted 'Olympia'?", options: ["Monet", "Manet", "Degas", "Renoir"], correctIndex: 1 },
    { text: "What was the Salon des Refusés?", options: ["Art school", "Exhibition for rejected works", "Museum", "Art supply store"], correctIndex: 1 },
    { text: "Who painted 'The Dance Class'?", options: ["Monet", "Degas", "Renoir", "Morisot"], correctIndex: 1 },
    { text: "What influenced Impressionist color use?", options: ["Photography", "Scientific color theory", "Religious texts", "Ancient art"], correctIndex: 1 },
    { text: "Who was a prominent female Impressionist?", options: ["Frida Kahlo", "Berthe Morisot", "Georgia O'Keeffe", "Mary Cassatt"], correctIndex: 1 },
    { text: "What did Impressionists avoid using?", options: ["Bright colors", "Black for shadows", "Canvas", "Oil paint"], correctIndex: 1 },
    { text: "Who painted 'A Bar at the Folies-Bergère'?", options: ["Monet", "Manet", "Degas", "Renoir"], correctIndex: 1 },
    { text: "What was plein air painting?", options: ["Indoor painting", "Outdoor painting", "Night painting", "Abstract painting"], correctIndex: 1 },
    { text: "Who painted the Rouen Cathedral series?", options: ["Renoir", "Monet", "Pissarro", "Sisley"], correctIndex: 1 },
    { text: "What city was the center of Impressionism?", options: ["London", "Paris", "Rome", "Vienna"], correctIndex: 1 },
    { text: "Who painted 'The Swing'?", options: ["Monet", "Renoir", "Degas", "Cézanne"], correctIndex: 1 },
    { text: "What subjects did Mary Cassatt often paint?", options: ["Landscapes", "Mothers and children", "Battles", "Still lifes"], correctIndex: 1 },
    { text: "Who painted 'Boulevard Montmartre' series?", options: ["Monet", "Pissarro", "Renoir", "Sisley"], correctIndex: 1 },
    { text: "What was revolutionary about Impressionist exhibitions?", options: ["Free admission", "Independent from official Salon", "Outdoor venues", "Digital catalogs"], correctIndex: 1 },
    { text: "Who painted 'Haystacks' series?", options: ["Renoir", "Monet", "Degas", "Morisot"], correctIndex: 1 },
    { text: "What aspect of nature fascinated Impressionists?", options: ["Storms", "Changing light", "Mountains", "Deserts"], correctIndex: 1 },
    { text: "Who was Monet's first wife and model?", options: ["Berthe Morisot", "Camille Doncieux", "Mary Cassatt", "Suzanne Valadon"], correctIndex: 1 },
    { text: "What garden did Monet famously paint?", options: ["Versailles", "Giverny", "Tuileries", "Luxembourg"], correctIndex: 1 },
    { text: "Who painted 'The Absinthe Drinker' (Impressionist version)?", options: ["Monet", "Degas", "Manet", "Toulouse-Lautrec"], correctIndex: 1 },
    { text: "What movement followed Impressionism?", options: ["Renaissance", "Post-Impressionism", "Baroque", "Realism"], correctIndex: 1 },
    { text: "Who painted 'The Cradle'?", options: ["Cassatt", "Berthe Morisot", "Renoir", "Monet"], correctIndex: 1 },
    { text: "What was criticized about Impressionist works?", options: ["Too detailed", "Unfinished appearance", "Too realistic", "Too large"], correctIndex: 1 },
    { text: "Who painted 'Poppies' (1873)?", options: ["Renoir", "Monet", "Pissarro", "Sisley"], correctIndex: 1 },
    { text: "What Japanese art form influenced Impressionists?", options: ["Origami", "Woodblock prints", "Calligraphy", "Pottery"], correctIndex: 1 },
    { text: "Who organized the first Impressionist exhibition?", options: ["Degas", "Group of artists including Monet", "The Louvre", "Napoleon III"], correctIndex: 1 },
    { text: "What year was the first Impressionist exhibition?", options: ["1863", "1874", "1885", "1900"], correctIndex: 1 },
    { text: "Who painted 'Gare Saint-Lazare' series?", options: ["Degas", "Monet", "Renoir", "Caillebotte"], correctIndex: 1 },
    { text: "What was unusual about Impressionist compositions?", options: ["Centered subjects", "Cropped, snapshot-like views", "Perfect symmetry", "Religious themes"], correctIndex: 1 },
    { text: "Who painted 'Paris Street, Rainy Day'?", options: ["Monet", "Caillebotte", "Pissarro", "Sisley"], correctIndex: 1 },
    { text: "What did Impressionists capture?", options: ["Historical events", "Fleeting moments", "Mythology", "Portraits only"], correctIndex: 1 },
    { text: "Who painted 'The Bellelli Family'?", options: ["Monet", "Degas", "Renoir", "Manet"], correctIndex: 1 },
    { text: "What medium did Degas also work in extensively?", options: ["Watercolor only", "Pastel", "Fresco", "Mosaic"], correctIndex: 1 },
    { text: "Who painted 'Impression, Soleil Levant'?", options: ["Manet", "Monet", "Renoir", "Pissarro"], correctIndex: 1 },
    { text: "What aspect of modern life did Impressionists document?", options: ["Warfare", "Leisure and urban life", "Industry only", "Rural poverty"], correctIndex: 1 },
    { text: "Who painted 'Young Girl at a Window'?", options: ["Monet", "Berthe Morisot", "Cassatt", "Renoir"], correctIndex: 1 },
    { text: "What was the critical reception initially?", options: ["Universally praised", "Largely negative", "Ignored", "Government supported"], correctIndex: 1 },
    { text: "Who painted 'The Floor Scrapers'?", options: ["Monet", "Caillebotte", "Degas", "Renoir"], correctIndex: 1 },
    { text: "What innovation helped Impressionists paint outdoors?", options: ["Easels", "Portable paint tubes", "Canvas", "Brushes"], correctIndex: 1 },
    { text: "Who painted 'Le Moulin de la Galette'?", options: ["Monet", "Renoir", "Degas", "Toulouse-Lautrec"], correctIndex: 1 },
    { text: "What element did Impressionists emphasize over line?", options: ["Form", "Color and light", "Texture", "Perspective"], correctIndex: 1 },
];
