export const industrial_revolutionQuestions = [

    // Industrial Revolution (50 questions)
    { text: "When did the Industrial Revolution begin?", options: ["Early 1600s", "Mid-1700s", "Early 1800s", "Late 1800s"], correctIndex: 1 },
    { text: "Where did the Industrial Revolution start?", options: ["France", "Britain", "Germany", "United States"], correctIndex: 1 },
    { text: "What was the steam engine used for?", options: ["Cooking", "Power for machinery", "Lighting", "Communication"], correctIndex: 1 },
    { text: "Who improved the steam engine?", options: ["Thomas Edison", "James Watt", "Henry Ford", "George Stephenson"], correctIndex: 1 },
    { text: "What industry was first to industrialize?", options: ["Steel", "Textile", "Automotive", "Chemical"], correctIndex: 1 },
    { text: "What was the spinning jenny?", options: ["Train", "Textile machine", "Steam engine", "Telegraph"], correctIndex: 1 },
    { text: "What powered early factories?", options: ["Electricity", "Water and steam", "Oil", "Nuclear energy"], correctIndex: 1 },
    { text: "What was urbanization?", options: ["Rural growth", "Movement to cities", "Factory decline", "Agricultural expansion"], correctIndex: 1 },
    { text: "Who invented the cotton gin?", options: ["Samuel Morse", "Eli Whitney", "Alexander Graham Bell", "Thomas Edison"], correctIndex: 1 },
    { text: "What were working conditions like in early factories?", options: ["Comfortable", "Dangerous and harsh", "Well-regulated", "Part-time only"], correctIndex: 1 },
    { text: "What was the Luddite movement?", options: ["Pro-technology", "Workers destroying machines", "Government policy", "Factory owners' group"], correctIndex: 1 },
    { text: "What transformed transportation?", options: ["Airplanes", "Railroads", "Helicopters", "Subways"], correctIndex: 1 },
    { text: "Who built the first successful railroad locomotive?", options: ["James Watt", "George Stephenson", "Eli Whitney", "Henry Bessemer"], correctIndex: 1 },
    { text: "What was the main source of energy in the Industrial Revolution?", options: ["Solar", "Coal", "Oil", "Natural gas"], correctIndex: 1 },
    { text: "What was child labor?", options: ["Children in school", "Children working in factories", "Children's education", "Children's healthcare"], correctIndex: 1 },
    { text: "What was the Bessemer process?", options: ["Textile production", "Steel production", "Coal mining", "Railroad building"], correctIndex: 1 },
    { text: "What economic system grew during industrialization?", options: ["Feudalism", "Capitalism", "Socialism only", "Mercantilism"], correctIndex: 1 },
    { text: "What was a factory system?", options: ["Home production", "Centralized production", "Agricultural work", "Craft guilds"], correctIndex: 1 },
    { text: "Who invented the telegraph?", options: ["Alexander Graham Bell", "Samuel Morse", "Thomas Edison", "Nikola Tesla"], correctIndex: 1 },
    { text: "What was mass production?", options: ["Custom goods", "Large-scale standardized goods", "Agricultural output", "Handmade items"], correctIndex: 1 },
    { text: "What were slums?", options: ["Wealthy neighborhoods", "Poor urban housing", "Factory buildings", "Rural areas"], correctIndex: 1 },
    { text: "What did the Factory Act of 1833 address?", options: ["Wages", "Child labor", "Taxation", "Exports"], correctIndex: 1 },
    { text: "Who wrote 'The Communist Manifesto'?", options: ["Adam Smith", "Karl Marx and Friedrich Engels", "Charles Dickens", "John Stuart Mill"], correctIndex: 1 },
    { text: "What was the enclosure movement?", options: ["Factory building", "Consolidating farmland", "City planning", "Railroad expansion"], correctIndex: 1 },
    { text: "What was interchangeable parts?", options: ["Custom pieces", "Identical replaceable components", "Broken machinery", "Factory tools"], correctIndex: 1 },
    { text: "Who is associated with the assembly line?", options: ["Thomas Edison", "Henry Ford", "Andrew Carnegie", "John Rockefeller"], correctIndex: 1 },
    { text: "What was the main social change during industrialization?", options: ["Rural growth", "Rise of middle and working classes", "Decline of cities", "Return to agriculture"], correctIndex: 1 },
    { text: "What did Thomas Edison invent?", options: ["Telegraph", "Light bulb", "Telephone", "Radio"], correctIndex: 1 },
    { text: "What were labor unions?", options: ["Factory owners", "Worker organizations", "Government agencies", "Trade companies"], correctIndex: 1 },
    { text: "What was the Second Industrial Revolution characterized by?", options: ["Textiles", "Electricity and chemicals", "Agriculture", "Sailing ships"], correctIndex: 1 },
    { text: "What did Alexander Graham Bell invent?", options: ["Telegraph", "Telephone", "Radio", "Television"], correctIndex: 1 },
    { text: "What was laissez-faire economics?", options: ["Heavy regulation", "Minimal government intervention", "Government ownership", "Trade restrictions"], correctIndex: 1 },
    { text: "What was the main impact on agriculture?", options: ["Decline", "Mechanization", "Elimination", "No change"], correctIndex: 1 },
    { text: "What was the spinning mule?", options: ["Animal", "Textile machine", "Transport", "Mining tool"], correctIndex: 1 },
    { text: "Who wrote 'The Wealth of Nations'?", options: ["Karl Marx", "Adam Smith", "David Ricardo", "Thomas Malthus"], correctIndex: 1 },
    { text: "What was pollution a result of?", options: ["Agriculture", "Industrialization", "Forestry", "Fishing"], correctIndex: 1 },
    { text: "What were tenements?", options: ["Factories", "Crowded apartment buildings", "Warehouses", "Offices"], correctIndex: 1 },
    { text: "What was the main energy source before coal?", options: ["Oil", "Water and wind", "Nuclear", "Solar"], correctIndex: 1 },
    { text: "What did the Transcontinental Railroad connect?", options: ["North and South", "East and West US", "Europe and Asia", "Canada and Mexico"], correctIndex: 1 },
    { text: "What was a monopoly?", options: ["Competition", "Control of industry by one entity", "Government ownership", "Worker cooperative"], correctIndex: 1 },
    { text: "Who was a famous steel magnate?", options: ["Henry Ford", "Andrew Carnegie", "Thomas Edison", "Cornelius Vanderbilt"], correctIndex: 1 },
    { text: "What was the primary goal of labor unions?", options: ["Increase profits", "Improve worker conditions", "Reduce production", "Eliminate factories"], correctIndex: 1 },
    { text: "What was the typical factory work day?", options: ["4-6 hours", "12-16 hours", "8 hours", "Variable"], correctIndex: 1 },
    { text: "What was urban sprawl?", options: ["Rural growth", "City expansion", "Factory closure", "Population decline"], correctIndex: 1 },
    { text: "What innovation improved agriculture?", options: ["Telegraph", "Mechanical reaper", "Steam engine", "Telephone"], correctIndex: 1 },
    { text: "What was the main British export during early industrialization?", options: ["Coal", "Textiles", "Steel", "Food"], correctIndex: 1 },
    { text: "What was the impact on family structure?", options: ["No change", "Separation of work and home", "Return to farms", "Larger families"], correctIndex: 1 },
    { text: "What were robber barons?", options: ["Criminals", "Wealthy industrialists", "Government officials", "Workers"], correctIndex: 1 },
    { text: "What was the main benefit of canals?", options: ["Defense", "Transportation of goods", "Recreation", "Fishing"], correctIndex: 1 },
    { text: "What was the Gilded Age?", options: ["Medieval period", "Period of industrial growth and wealth disparity", "Colonial era", "Agricultural age"], correctIndex: 1 },
];
