export const islandsQuestions = [

    // Islands (50 questions)
    { text: "What is the largest island in the world?", options: ["New Guinea", "Greenland", "Borneo", "Madagascar"], correctIndex: 1 },
    { text: "What island country is located south of India?", options: ["Maldives", "Sri Lanka", "Indonesia", "Madagascar"], correctIndex: 1 },
    { text: "What island is home to the famous Moai statues?", options: ["Fiji", "Easter Island", "Tahiti", "Samoa"], correctIndex: 1 },
    { text: "What is the largest island in the Mediterranean?", options: ["Sardinia", "Sicily", "Cyprus", "Crete"], correctIndex: 1 },
    { text: "What island group includes Maui and Oahu?", options: ["Samoa", "Hawaii", "Fiji", "Cook Islands"], correctIndex: 1 },
    { text: "What island is shared by Indonesia, Malaysia, and Brunei?", options: ["Sumatra", "Borneo", "Java", "Sulawesi"], correctIndex: 1 },
    { text: "What Caribbean island is divided between two countries?", options: ["Jamaica", "Hispaniola", "Cuba", "Puerto Rico"], correctIndex: 1 },
    { text: "What is the most populous island in the world?", options: ["Honshu", "Java", "Great Britain", "Luzon"], correctIndex: 1 },
    { text: "What island nation is known for lemurs?", options: ["Sri Lanka", "Madagascar", "Mauritius", "Seychelles"], correctIndex: 1 },
    { text: "What island is New York City located on?", options: ["Staten Island", "Manhattan", "Long Island", "Roosevelt Island"], correctIndex: 1 },
    { text: "What island country is located east of Africa?", options: ["Maldives", "Madagascar", "Seychelles", "Mauritius"], correctIndex: 1 },
    { text: "What is the largest island in the Caribbean?", options: ["Hispaniola", "Cuba", "Jamaica", "Puerto Rico"], correctIndex: 1 },
    { text: "What island is known for the Galápagos tortoise?", options: ["Madagascar", "Galápagos Islands", "Komodo", "Tasmania"], correctIndex: 1 },
    { text: "What UK island group includes Lewis and Harris?", options: ["Orkney", "Outer Hebrides", "Shetland", "Isle of Man"], correctIndex: 1 },
    { text: "What island nation is located in the Indian Ocean and known for tourism?", options: ["Sri Lanka", "Maldives", "Fiji", "Seychelles"], correctIndex: 1 },
    { text: "What is the main island of Japan?", options: ["Kyushu", "Honshu", "Hokkaido", "Shikoku"], correctIndex: 1 },
    { text: "What volcanic island is part of Italy?", options: ["Sardinia", "Sicily", "Corsica", "Malta"], correctIndex: 1 },
    { text: "What island is the southernmost point of Argentina?", options: ["Falkland Islands", "Tierra del Fuego", "South Georgia", "Staten Island"], correctIndex: 1 },
    { text: "What island country consists of over 7,000 islands?", options: ["Indonesia", "Philippines", "Japan", "Maldives"], correctIndex: 1 },
    { text: "What is the largest island in Canada?", options: ["Vancouver Island", "Baffin Island", "Newfoundland", "Victoria Island"], correctIndex: 1 },
    { text: "What Mediterranean island belongs to France?", options: ["Sardinia", "Corsica", "Sicily", "Malta"], correctIndex: 1 },
    { text: "What island is known for giant tortoises and unique wildlife?", options: ["Madagascar", "Galápagos", "Tasmania", "Komodo"], correctIndex: 1 },
    { text: "What island state is Australia's south?", options: ["New Zealand", "Tasmania", "Fiji", "Papua New Guinea"], correctIndex: 1 },
    { text: "What is the third largest island in the world?", options: ["Madagascar", "Borneo", "New Guinea", "Sumatra"], correctIndex: 1 },
    { text: "What Caribbean island is a US territory?", options: ["Jamaica", "Puerto Rico", "Cuba", "Haiti"], correctIndex: 1 },
    { text: "What Greek island is famous for white buildings and blue domes?", options: ["Crete", "Santorini", "Mykonos", "Rhodes"], correctIndex: 1 },
    { text: "What is the largest island in the Philippines?", options: ["Mindanao", "Luzon", "Palawan", "Cebu"], correctIndex: 1 },
    { text: "What island is known for its dragons?", options: ["Madagascar", "Komodo", "Bali", "Java"], correctIndex: 1 },
    { text: "What island group is known for its blue lagoons?", options: ["Maldives", "Fiji", "Seychelles", "Tahiti"], correctIndex: 0 },
    { text: "What is the largest island in Indonesia?", options: ["Java", "Sumatra", "Borneo", "Sulawesi"], correctIndex: 1 },
    { text: "What island is home to Barcelona?", options: ["None - Barcelona is on mainland", "Mallorca", "Ibiza", "Menorca"], correctIndex: 0 },
    { text: "What island was Napoleon exiled to?", options: ["Corsica", "Elba", "St. Helena", "Both B and C"], correctIndex: 3 },
    { text: "What is the largest of the Greek islands?", options: ["Rhodes", "Crete", "Corfu", "Santorini"], correctIndex: 1 },
    { text: "What Caribbean island nation was formerly called Ceylon?", options: ["It's not Caribbean - Sri Lanka", "Maldives", "Mauritius", "Seychelles"], correctIndex: 0 },
    { text: "What is the northernmost island of Japan?", options: ["Honshu", "Hokkaido", "Kyushu", "Okinawa"], correctIndex: 1 },
    { text: "What island is known for its famous prison?", options: ["Ellis Island", "Alcatraz", "Rikers Island", "Devil's Island"], correctIndex: 1 },
    { text: "What is New Zealand's South Island known for?", options: ["Cities", "Mountains and fjords", "Beaches only", "Deserts"], correctIndex: 1 },
    { text: "What island is part of Denmark but geographically near North America?", options: ["Iceland", "Greenland", "Faroe Islands", "Jan Mayen"], correctIndex: 1 },
    { text: "What island is famous for its beaches and nightlife in Spain?", options: ["Mallorca", "Ibiza", "Tenerife", "Gran Canaria"], correctIndex: 1 },
    { text: "What Indonesian island is known for its Hindu culture?", options: ["Java", "Bali", "Sumatra", "Lombok"], correctIndex: 1 },
    { text: "What island is off the coast of Venezuela?", options: ["Trinidad", "Aruba", "Curaçao", "All of these"], correctIndex: 3 },
    { text: "What island nation is in the Gulf of Guinea?", options: ["Mauritius", "São Tomé and Príncipe", "Cape Verde", "Seychelles"], correctIndex: 1 },
    { text: "What is the largest island in Europe?", options: ["Iceland", "Great Britain", "Ireland", "Sicily"], correctIndex: 1 },
    { text: "What Pacific island is a US state?", options: ["Guam", "Hawaii", "American Samoa", "Puerto Rico"], correctIndex: 1 },
    { text: "What island is known for its active volcano Eyjafjallajökull?", options: ["Greenland", "Iceland", "Faroe Islands", "Svalbard"], correctIndex: 1 },
    { text: "What is the second largest island in the Mediterranean?", options: ["Sicily", "Sardinia", "Cyprus", "Corsica"], correctIndex: 1 },
    { text: "What island country is located between India and the Maldives?", options: ["Mauritius", "Sri Lanka", "Seychelles", "Madagascar"], correctIndex: 1 },
    { text: "What island is the setting for Robinson Crusoe?", options: ["Fiji", "Juan Fernández Islands", "Easter Island", "Tahiti"], correctIndex: 1 },
    { text: "What island is divided between Haiti and Dominican Republic?", options: ["Cuba", "Hispaniola", "Jamaica", "Puerto Rico"], correctIndex: 1 },
    { text: "What islands are known for their penguins and located near Antarctica?", options: ["Galápagos", "Falkland Islands", "Tasmania", "South Georgia"], correctIndex: 1 },
];
