export const mathQuestions = [

    // Math
    { text: "What is 15% of 200?", options: ["20", "25", "30", "35"], correctIndex: 2 },
    { text: "What is the square root of 144?", options: ["10", "11", "12", "13"], correctIndex: 2 },
    { text: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "What is 7 × 8?", options: ["54", "56", "58", "64"], correctIndex: 1 },
    { text: "What is the value of π (pi) to two decimal places?", options: ["3.12", "3.14", "3.16", "3.18"], correctIndex: 1 },
    { text: "What is the sum of the interior angles in a triangle?", options: ["90°", "180°", "270°", "360°"], correctIndex: 1 },
    { text: "What is the value of x in the equation 2x + 5 = 15?", options: ["5", "7", "10", "20"], correctIndex: 0 },
    { text: "What is the area of a circle with radius 5?", options: ["10π", "25π", "50π", "100π"], correctIndex: 1 },
    { text: "What is the probability of rolling a 6 on a standard die?", options: ["1/6", "1/4", "1/3", "1/2"], correctIndex: 0 },
    { text: "What is the median of the numbers 1, 2, 3, 4, 5?", options: ["1", "2", "3", "4"], correctIndex: 2 },
    { text: "What is the value of x in the equation 3x − 7 = 14?", options: ["5", "7", "10", "20"], correctIndex: 1 },
    { text: "What is the area of a rectangle with length 5 and width 4?", options: ["10", "15", "20", "25"], correctIndex: 2 },
    { text: "What is 2³?", options: ["4", "6", "8", "16"], correctIndex: 2 },
    { text: "What is the perimeter of a square with side length 6?", options: ["24", "12", "36", "18"], correctIndex: 0 },
    { text: "What is the least common multiple of 4 and 6?", options: ["12", "8", "24", "6"], correctIndex: 0 },
    { text: "What is the greatest common factor of 18 and 24?", options: ["4", "6", "8", "12"], correctIndex: 1 },
    { text: "What is 20% of 150?", options: ["25", "30", "35", "20"], correctIndex: 1 },
    { text: "What is the next prime number after 13?", options: ["14", "15", "16", "17"], correctIndex: 3 },
    { text: "How many degrees are in a right angle?", options: ["45°", "60°", "90°", "180°"], correctIndex: 2 },
    { text: "What is 5! (5 factorial)?", options: ["20", "60", "100", "120"], correctIndex: 3 },
    { text: "What is the slope of a horizontal line?", options: ["1", "−1", "Undefined", "0"], correctIndex: 3 },
    { text: "How many edges does a cube have?", options: ["6", "8", "10", "12"], correctIndex: 3 },
    { text: "What is the square root of 225?", options: ["12", "13", "14", "15"], correctIndex: 3 },
    { text: "What is 0.25 expressed as a fraction?", options: ["1/2", "1/3", "1/4", "1/5"], correctIndex: 2 },
    { text: "Which of the following is an irrational number?", options: ["1/3", "√4", "π", "0.5"], correctIndex: 2 },
    { text: "What is the sum of the interior angles of a quadrilateral?", options: ["180°", "270°", "360°", "540°"], correctIndex: 2 },
    { text: "What is 12 squared?", options: ["124", "132", "140", "144"], correctIndex: 3 },
    { text: "In statistics, what does the 'mean' refer to?", options: ["Most frequent value", "Middle value", "Arithmetic average", "Difference between max and min"], correctIndex: 2 },
    { text: "What is the volume of a cube with side length 3?", options: ["9", "18", "27", "81"], correctIndex: 2 },
    { text: "What is the reciprocal of 4?", options: ["2", "1/2", "4", "1/4"], correctIndex: 3 },
    { text: "What is 3/4 + 1/4?", options: ["2/4", "3/8", "1", "1/2"], correctIndex: 2 },
    { text: "What is the absolute value of −15?", options: ["15", "−15", "0", "1/15"], correctIndex: 0 },
    { text: "If a triangle has angles of 60° and 80°, what is the third angle?", options: ["30°", "40°", "50°", "60°"], correctIndex: 1 },
    { text: "What is the square root of 64?", options: ["6", "7", "8", "9"], correctIndex: 2 },
    { text: "How many sides does a pentagon have?", options: ["4", "5", "6", "7"], correctIndex: 1 },
    { text: "What is 3² + 4²?", options: ["10", "14", "25", "50"], correctIndex: 2 },
    { text: "What is the formula for the area of a triangle?", options: ["base × height", "½ × base × height", "½ × (base + height)", "2 × base × height"], correctIndex: 1 },
    { text: "What is 7/8 as a decimal?", options: ["0.75", "0.7", "0.875", "0.825"], correctIndex: 2 },
    { text: "What is the mode of: 1, 2, 2, 3, 4?", options: ["1", "2", "3", "4"], correctIndex: 1 },
    { text: "What is 64 ÷ 8?", options: ["6", "7", "8", "9"], correctIndex: 2 },
    { text: "What is the perimeter of a rectangle with length 8 and width 3?", options: ["11", "22", "24", "33"], correctIndex: 1 },
    { text: "Which of these numbers is prime?", options: ["9", "15", "21", "23"], correctIndex: 3 },
    { text: "What is 1/8 as a decimal?", options: ["0.10", "0.125", "0.15", "0.25"], correctIndex: 1 },
    { text: "What is the area of a square with side length 7?", options: ["14", "28", "42", "49"], correctIndex: 3 },
    { text: "What is the circumference of a circle with diameter 10?", options: ["10π", "20π", "5π", "100π"], correctIndex: 0 },
    { text: "What is 15 mod 4 (the remainder when 15 is divided by 4)?", options: ["0", "1", "2", "3"], correctIndex: 3 },
    { text: "How many faces does a cube have?", options: ["4", "5", "6", "8"], correctIndex: 2 },
    { text: "What is 4² − 3²?", options: ["1", "5", "7", "9"], correctIndex: 2 },
    { text: "What is the formula for compound interest?", options: ["A = P + rt", "A = P(1 + r)^t", "A = Prt", "A = P / (1 + r)^t"], correctIndex: 1 },
    { text: "How many degrees are in a full rotation?", options: ["90°", "180°", "270°", "360°"], correctIndex: 3 },
];
