export const meteorologyQuestions = [

    // Meteorology (50 questions)
    { text: "What is meteorology?", options: ["Study of meteors", "Study of weather and atmosphere", "Study of oceans", "Study of rocks"], correctIndex: 1 },
    { text: "What instrument measures air pressure?", options: ["Thermometer", "Barometer", "Anemometer", "Hygrometer"], correctIndex: 1 },
    { text: "What is a cold front?", options: ["Warm air mass", "Cold air replacing warm air", "Stationary air", "High pressure"], correctIndex: 1 },
    { text: "What causes wind?", options: ["Earth's rotation only", "Pressure differences", "Gravity", "Ocean currents"], correctIndex: 1 },
    { text: "What is humidity?", options: ["Temperature", "Water vapor in air", "Air pressure", "Wind speed"], correctIndex: 1 },
    { text: "What is a hurricane called in the Pacific?", options: ["Cyclone", "Typhoon", "Monsoon", "Tornado"], correctIndex: 1 },
    { text: "What cloud type brings thunderstorms?", options: ["Cirrus", "Cumulonimbus", "Stratus", "Cumulus"], correctIndex: 1 },
    { text: "What is the dew point?", options: ["Freezing point", "Temperature when air saturates", "Boiling point", "Melting point"], correctIndex: 1 },
    { text: "What measures wind speed?", options: ["Barometer", "Anemometer", "Thermometer", "Hygrometer"], correctIndex: 1 },
    { text: "What is precipitation?", options: ["Evaporation", "Water falling from clouds", "Condensation", "Humidity"], correctIndex: 1 },
    { text: "What is an isobar?", options: ["Temperature line", "Pressure line on map", "Wind direction", "Humidity level"], correctIndex: 1 },
    { text: "What is the jet stream?", options: ["Ocean current", "High-altitude wind current", "Surface wind", "Cloud type"], correctIndex: 1 },
    { text: "What scale measures tornado intensity?", options: ["Richter", "Enhanced Fujita", "Beaufort", "Saffir-Simpson"], correctIndex: 1 },
    { text: "What is a warm front?", options: ["Cold air replacing warm", "Warm air replacing cold", "Stationary air", "High pressure"], correctIndex: 1 },
    { text: "What are cirrus clouds?", options: ["Low, dark clouds", "High, wispy clouds", "Puffy clouds", "Storm clouds"], correctIndex: 1 },
    { text: "What is the Coriolis effect?", options: ["Ocean waves", "Deflection of moving objects on Earth", "Cloud formation", "Temperature change"], correctIndex: 1 },
    { text: "What is an occluded front?", options: ["Two warm fronts", "Cold front overtaking warm front", "Stationary front", "No front"], correctIndex: 1 },
    { text: "What is convection in weather?", options: ["Horizontal movement", "Vertical air circulation", "Cloud type", "Pressure system"], correctIndex: 1 },
    { text: "What is a microburst?", options: ["Small tornado", "Strong downdraft", "Updraft", "Light rain"], correctIndex: 1 },
    { text: "What are stratus clouds?", options: ["High clouds", "Low, layered clouds", "Puffy clouds", "Wispy clouds"], correctIndex: 1 },
    { text: "What is the eye of a hurricane?", options: ["Strongest part", "Calm center", "Outer edge", "Cloud wall"], correctIndex: 1 },
    { text: "What is virga?", options: ["Cloud type", "Rain that evaporates before hitting ground", "Wind pattern", "Snow"], correctIndex: 1 },
    { text: "What is atmospheric pressure at sea level?", options: ["1013 mb", "500 mb", "2000 mb", "100 mb"], correctIndex: 0 },
    { text: "What is a derecho?", options: ["Tornado", "Widespread windstorm", "Hurricane", "Hailstorm"], correctIndex: 1 },
    { text: "What are cumulus clouds?", options: ["Wispy", "Puffy, white", "Flat, gray", "Dark, stormy"], correctIndex: 1 },
    { text: "What is the tropopause?", options: ["Ground level", "Boundary between troposphere and stratosphere", "Ocean surface", "Mountain top"], correctIndex: 1 },
    { text: "What is a squall line?", options: ["Single storm", "Line of severe thunderstorms", "Tornado path", "Wind direction"], correctIndex: 1 },
    { text: "What is advection?", options: ["Vertical movement", "Horizontal heat/moisture transfer", "Cloud formation", "Precipitation"], correctIndex: 1 },
    { text: "What is graupel?", options: ["Hail", "Soft snow pellets", "Rain", "Sleet"], correctIndex: 1 },
    { text: "What is an inversion in meteorology?", options: ["Low pressure", "Temperature increase with altitude", "High winds", "Heavy rain"], correctIndex: 1 },
    { text: "What is the sublimation process?", options: ["Liquid to gas", "Solid to gas", "Gas to liquid", "Liquid to solid"], correctIndex: 1 },
    { text: "What is CAPE?", options: ["Cloud type", "Convective Available Potential Energy", "Wind speed", "Pressure"], correctIndex: 1 },
    { text: "What is a gust front?", options: ["Warm air", "Leading edge of cold downdraft", "Cloud formation", "Calm air"], correctIndex: 1 },
    { text: "What is the stratosphere?", options: ["Ground level", "Atmospheric layer above troposphere", "Ocean layer", "Earth's core"], correctIndex: 1 },
    { text: "What is a mesocyclone?", options: ["Small tornado", "Rotating updraft in thunderstorm", "Hurricane eye", "Wind pattern"], correctIndex: 1 },
    { text: "What is latent heat?", options: ["Surface temperature", "Energy in phase changes", "Air pressure", "Wind energy"], correctIndex: 1 },
    { text: "What is the planetary boundary layer?", options: ["Space boundary", "Lowest atmosphere layer affected by Earth's surface", "Stratosphere", "Mesosphere"], correctIndex: 1 },
    { text: "What is a haboob?", options: ["Tornado", "Dust storm", "Snowstorm", "Hurricane"], correctIndex: 1 },
    { text: "What is orographic lifting?", options: ["Sun heating", "Air rising over mountains", "Ocean effect", "Wind pattern"], correctIndex: 1 },
    { text: "What is a ridge in meteorology?", options: ["Low pressure", "High pressure elongation", "Mountain", "Cloud type"], correctIndex: 1 },
    { text: "What is a trough in meteorology?", options: ["High pressure", "Low pressure elongation", "Valley", "Cloud type"], correctIndex: 1 },
    { text: "What is the lapse rate?", options: ["Time rate", "Temperature decrease with altitude", "Pressure change", "Wind speed"], correctIndex: 1 },
    { text: "What is a waterspout?", options: ["Water fountain", "Tornado over water", "Ocean wave", "Rain burst"], correctIndex: 1 },
    { text: "What is albedo?", options: ["Cloud type", "Surface reflectivity", "Wind speed", "Temperature"], correctIndex: 1 },
    { text: "What is a supercell?", options: ["Large cell tower", "Rotating severe thunderstorm", "Hurricane", "Blizzard"], correctIndex: 1 },
    { text: "What is the mesosphere?", options: ["Ground level", "Atmospheric layer above stratosphere", "Ocean layer", "Space"], correctIndex: 1 },
    { text: "What is radiosonde?", options: ["Radio station", "Weather balloon instrument", "Satellite", "Radar"], correctIndex: 1 },
    { text: "What is the thermosphere?", options: ["Cold layer", "Hot upper atmospheric layer", "Ground level", "Ocean layer"], correctIndex: 1 },
    { text: "What is a vortex?", options: ["Straight line", "Rotating air mass", "Cloud type", "Calm air"], correctIndex: 1 },
    { text: "What is nucleation in weather?", options: ["Nuclear reaction", "Water vapor condensing on particles", "Wind formation", "Pressure change"], correctIndex: 1 },
];
