export const national_parksQuestions = [

    // National Parks (50 questions)
    { text: "What is the oldest national park in the United States?", options: ["Yosemite", "Yellowstone", "Grand Canyon", "Sequoia"], correctIndex: 1 },
    { text: "Which national park is home to Half Dome?", options: ["Sequoia", "Yosemite", "Kings Canyon", "Joshua Tree"], correctIndex: 1 },
    { text: "What national park features Old Faithful geyser?", options: ["Grand Teton", "Yellowstone", "Glacier", "Rocky Mountain"], correctIndex: 1 },
    { text: "Which national park is located in Utah and known for red rock formations?", options: ["Bryce Canyon", "Zion", "Arches", "All of these"], correctIndex: 3 },
    { text: "What is the largest national park in the United States?", options: ["Death Valley", "Wrangell-St. Elias", "Yellowstone", "Glacier Bay"], correctIndex: 1 },
    { text: "Which national park is famous for the General Sherman Tree?", options: ["Redwood", "Sequoia", "Yosemite", "Olympic"], correctIndex: 1 },
    { text: "What national park features the deepest lake in the US?", options: ["Glacier", "Crater Lake", "Yellowstone", "Grand Teton"], correctIndex: 1 },
    { text: "Which national park is located in Florida?", options: ["Big Bend", "Everglades", "Congaree", "Hot Springs"], correctIndex: 1 },
    { text: "What national park is known for its ancient cliff dwellings?", options: ["Canyonlands", "Mesa Verde", "Petrified Forest", "Badlands"], correctIndex: 1 },
    { text: "Which national park is home to Mount Rainier?", options: ["North Cascades", "Mount Rainier", "Olympic", "Crater Lake"], correctIndex: 1 },
    { text: "What national park features the scenic Going-to-the-Sun Road?", options: ["Rocky Mountain", "Glacier", "Grand Teton", "Yellowstone"], correctIndex: 1 },
    { text: "Which national park is located in Maine?", options: ["Shenandoah", "Acadia", "Cuyahoga Valley", "Congaree"], correctIndex: 1 },
    { text: "What national park is known for its sand dunes?", options: ["Joshua Tree", "Great Sand Dunes", "Death Valley", "White Sands"], correctIndex: 1 },
    { text: "Which national park features the famous Delicate Arch?", options: ["Canyonlands", "Arches", "Capitol Reef", "Bryce Canyon"], correctIndex: 1 },
    { text: "What national park is home to the highest peak in North America?", options: ["Olympic", "Denali", "Glacier", "North Cascades"], correctIndex: 1 },
    { text: "Which national park features colorful hoodoos?", options: ["Zion", "Bryce Canyon", "Capitol Reef", "Arches"], correctIndex: 1 },
    { text: "What national park is located in the Virgin Islands?", options: ["Dry Tortugas", "Virgin Islands", "Biscayne", "Channel Islands"], correctIndex: 1 },
    { text: "Which national park is known for bear watching?", options: ["Yellowstone", "Katmai", "Denali", "Glacier"], correctIndex: 1 },
    { text: "What national park features the Narrows hiking trail?", options: ["Grand Canyon", "Zion", "Canyonlands", "Capitol Reef"], correctIndex: 1 },
    { text: "Which national park is located in South Dakota?", options: ["Theodore Roosevelt", "Badlands", "Wind Cave", "Both B and C"], correctIndex: 3 },
    { text: "What national park is famous for wildflower meadows and mountain views?", options: ["Glacier", "Mount Rainier", "North Cascades", "Olympic"], correctIndex: 1 },
    { text: "Which national park is located in American Samoa?", options: ["Virgin Islands", "National Park of American Samoa", "Channel Islands", "Haleakalā"], correctIndex: 1 },
    { text: "What national park features the Bright Angel Trail?", options: ["Zion", "Grand Canyon", "Bryce Canyon", "Canyonlands"], correctIndex: 1 },
    { text: "Which national park protects the tallest trees on Earth?", options: ["Sequoia", "Redwood", "Olympic", "Muir Woods"], correctIndex: 1 },
    { text: "What national park is known for its volcanic landscape in Hawaii?", options: ["Haleakalā", "Hawaiʻi Volcanoes", "American Samoa", "Channel Islands"], correctIndex: 1 },
    { text: "Which national park features Cadillac Mountain?", options: ["Shenandoah", "Acadia", "Great Smoky Mountains", "Cuyahoga Valley"], correctIndex: 1 },
    { text: "What national park is located in Texas?", options: ["Carlsbad Caverns", "Big Bend", "Guadalupe Mountains", "Both B and C"], correctIndex: 3 },
    { text: "Which national park is the most visited?", options: ["Yellowstone", "Great Smoky Mountains", "Grand Canyon", "Yosemite"], correctIndex: 1 },
    { text: "What national park features the Biscayne Bay?", options: ["Everglades", "Biscayne", "Dry Tortugas", "Virgin Islands"], correctIndex: 1 },
    { text: "Which national park is known for petrified wood?", options: ["Badlands", "Petrified Forest", "Theodore Roosevelt", "Saguaro"], correctIndex: 1 },
    { text: "What national park features Angel's Landing trail?", options: ["Grand Canyon", "Zion", "Yosemite", "Sequoia"], correctIndex: 1 },
    { text: "Which national park is located in Washington state and features rainforests?", options: ["Mount Rainier", "Olympic", "North Cascades", "Crater Lake"], correctIndex: 1 },
    { text: "What national park is known for its cave systems?", options: ["Sequoia", "Carlsbad Caverns", "Death Valley", "Joshua Tree"], correctIndex: 1 },
    { text: "Which national park features the Continental Divide?", options: ["Glacier", "Rocky Mountain", "Grand Teton", "All of these"], correctIndex: 3 },
    { text: "What national park is located in Kentucky?", options: ["Great Smoky Mountains", "Mammoth Cave", "Shenandoah", "Congaree"], correctIndex: 1 },
    { text: "Which national park features the Teton Range?", options: ["Rocky Mountain", "Grand Teton", "Glacier", "Yellowstone"], correctIndex: 1 },
    { text: "What national park is known for giant saguaro cacti?", options: ["Joshua Tree", "Saguaro", "Big Bend", "Death Valley"], correctIndex: 1 },
    { text: "Which national park features the Mist Trail?", options: ["Sequoia", "Yosemite", "Kings Canyon", "Death Valley"], correctIndex: 1 },
    { text: "What national park is located in Montana?", options: ["Yellowstone", "Glacier", "Grand Teton", "Theodore Roosevelt"], correctIndex: 1 },
    { text: "Which national park features Inspiration Point?", options: ["Yosemite", "Bryce Canyon", "Grand Canyon", "Zion"], correctIndex: 1 },
    { text: "What national park is known for its geothermal features?", options: ["Crater Lake", "Yellowstone", "Mount Rainier", "Lassen Volcanic"], correctIndex: 1 },
    { text: "Which national park is located in Alaska and features glaciers?", options: ["Denali", "Glacier Bay", "Kenai Fjords", "All of these"], correctIndex: 3 },
    { text: "What national park features Zabriskie Point?", options: ["Joshua Tree", "Death Valley", "Mojave", "Saguaro"], correctIndex: 1 },
    { text: "Which national park is located in North Dakota?", options: ["Badlands", "Theodore Roosevelt", "Wind Cave", "Voyageurs"], correctIndex: 1 },
    { text: "What national park features the Trail of Ten Falls?", options: ["Olympic", "Crater Lake", "Silver Falls State Park", "Mount Rainier"], correctIndex: 1 },
    { text: "Which national park is known for its Mesa formations?", options: ["Grand Canyon", "Canyonlands", "Mesa Verde", "Capitol Reef"], correctIndex: 2 },
    { text: "What national park is located in Arkansas?", options: ["Mammoth Cave", "Hot Springs", "Congaree", "Gateway Arch"], correctIndex: 1 },
    { text: "Which national park features Lake McDonald?", options: ["Yellowstone", "Glacier", "Grand Teton", "Crater Lake"], correctIndex: 1 },
    { text: "What national park is known for its desert landscape and Joshua trees?", options: ["Death Valley", "Joshua Tree", "Saguaro", "Big Bend"], correctIndex: 1 },
    { text: "Which national park features the Skyline Drive?", options: ["Great Smoky Mountains", "Shenandoah", "Acadia", "Cuyahoga Valley"], correctIndex: 1 },
];
