export const oceans_seasQuestions = [

    // Oceans & Seas (50 questions)
    { text: "What is the largest ocean?", options: ["Atlantic", "Pacific", "Indian", "Arctic"], correctIndex: 1 },
    { text: "What is the deepest point in the ocean?", options: ["Puerto Rico Trench", "Mariana Trench", "Java Trench", "Tonga Trench"], correctIndex: 1 },
    { text: "What ocean is between Africa and Australia?", options: ["Atlantic", "Indian", "Pacific", "Southern"], correctIndex: 1 },
    { text: "What is the saltiest sea?", options: ["Mediterranean", "Dead Sea", "Red Sea", "Black Sea"], correctIndex: 1 },
    { text: "What sea separates Europe and Africa?", options: ["Adriatic", "Mediterranean", "Black", "Aegean"], correctIndex: 1 },
    { text: "What is the smallest ocean?", options: ["Southern", "Arctic", "Indian", "Atlantic"], correctIndex: 1 },
    { text: "What sea is located between Saudi Arabia and Africa?", options: ["Arabian", "Red Sea", "Persian Gulf", "Mediterranean"], correctIndex: 1 },
    { text: "What is the largest sea?", options: ["Mediterranean", "Philippine Sea", "Caribbean", "Coral Sea"], correctIndex: 1 },
    { text: "What body of water connects the Mediterranean to the Atlantic?", options: ["Suez Canal", "Strait of Gibraltar", "Bosphorus", "Dardanelles"], correctIndex: 1 },
    { text: "What sea is between Italy and the Balkans?", options: ["Tyrrhenian", "Adriatic", "Ionian", "Aegean"], correctIndex: 1 },
    { text: "What ocean surrounds Antarctica?", options: ["Arctic", "Southern", "Atlantic", "Indian"], correctIndex: 1 },
    { text: "What sea is bordered by Russia, Ukraine, and Turkey?", options: ["Caspian", "Black Sea", "Aegean", "Baltic"], correctIndex: 1 },
    { text: "What body of water separates Asia and North America?", options: ["Pacific Ocean", "Bering Strait", "Arctic Ocean", "Aleutian Islands"], correctIndex: 1 },
    { text: "What sea is between Greece and Turkey?", options: ["Adriatic", "Aegean", "Ionian", "Mediterranean"], correctIndex: 1 },
    { text: "What is the warmest ocean?", options: ["Atlantic", "Indian", "Pacific", "Arctic"], correctIndex: 1 },
    { text: "What sea is connected to the Atlantic by the Suez Canal?", options: ["Black Sea", "Red Sea", "Arabian Sea", "Mediterranean"], correctIndex: 1 },
    { text: "What sea borders Scandinavia?", options: ["North Sea", "Baltic Sea", "Norwegian Sea", "All of these"], correctIndex: 3 },
    { text: "What is the Gulf Stream?", options: ["River", "Warm ocean current", "Sea", "Canal"], correctIndex: 1 },
    { text: "What sea is between Alaska and Russia?", options: ["Bering Sea", "Chukchi Sea", "Beaufort Sea", "Sea of Okhotsk"], correctIndex: 0 },
    { text: "What body of water is between Iran and Saudi Arabia?", options: ["Red Sea", "Persian Gulf", "Arabian Sea", "Gulf of Oman"], correctIndex: 1 },
    { text: "What sea is part of the Arctic Ocean north of Russia?", options: ["Baltic", "Barents Sea", "White Sea", "Kara Sea"], correctIndex: 1 },
    { text: "What is the second largest ocean?", options: ["Indian", "Atlantic", "Pacific", "Southern"], correctIndex: 1 },
    { text: "What sea is between Japan and Korea?", options: ["Yellow Sea", "Sea of Japan", "East China Sea", "Philippine Sea"], correctIndex: 1 },
    { text: "What sea is famous for the Bermuda Triangle?", options: ["Caribbean", "Sargasso Sea", "Gulf of Mexico", "Atlantic Ocean"], correctIndex: 1 },
    { text: "What is the Ring of Fire?", options: ["Desert", "Volcanic zone around Pacific", "Ocean current", "Island chain"], correctIndex: 1 },
    { text: "What sea borders Israel and Egypt?", options: ["Red Sea", "Mediterranean Sea", "Dead Sea", "Both A and B"], correctIndex: 3 },
    { text: "What is the Coral Sea known for?", options: ["Coral reefs", "Great Barrier Reef", "Marine life", "All of these"], correctIndex: 3 },
    { text: "What strait connects the Black Sea and Mediterranean?", options: ["Gibraltar", "Bosphorus and Dardanelles", "Hormuz", "Malacca"], correctIndex: 1 },
    { text: "What sea is between China and Korean Peninsula?", options: ["Sea of Japan", "Yellow Sea", "East China Sea", "South China Sea"], correctIndex: 1 },
    { text: "What is the abyssal zone?", options: ["Surface", "Deep ocean floor", "Continental shelf", "Mid-ocean"], correctIndex: 1 },
    { text: "What sea is bordered by several Southeast Asian countries?", options: ["Arabian Sea", "South China Sea", "Philippine Sea", "Coral Sea"], correctIndex: 1 },
    { text: "What is a gyre?", options: ["Fish", "Circular ocean current", "Island", "Trench"], correctIndex: 1 },
    { text: "What sea is west of Italy?", options: ["Adriatic", "Tyrrhenian", "Ionian", "Mediterranean"], correctIndex: 1 },
    { text: "What is the continental shelf?", options: ["Ocean trench", "Shallow ocean floor near continents", "Mid-ocean ridge", "Deep sea"], correctIndex: 1 },
    { text: "What sea is between Australia and New Zealand?", options: ["Coral Sea", "Tasman Sea", "Arafura Sea", "Timor Sea"], correctIndex: 1 },
    { text: "What is upwelling?", options: ["Waves", "Nutrient-rich water rising", "Tide", "Current"], correctIndex: 1 },
    { text: "What body of water is between India and Myanmar?", options: ["Arabian Sea", "Bay of Bengal", "Andaman Sea", "Indian Ocean"], correctIndex: 1 },
    { text: "What is the thermocline?", options: ["Surface water", "Temperature transition layer", "Ocean floor", "Ice layer"], correctIndex: 1 },
    { text: "What sea is between Saudi Arabia and Iran?", options: ["Red Sea", "Persian Gulf", "Arabian Sea", "Gulf of Aden"], correctIndex: 1 },
    { text: "What is a seamount?", options: ["Island", "Underwater mountain", "Trench", "Reef"], correctIndex: 1 },
    { text: "What sea borders Somalia?", options: ["Mediterranean", "Arabian Sea", "Red Sea", "Indian Ocean"], correctIndex: 1 },
    { text: "What is the hadal zone?", options: ["Surface", "Deepest ocean trenches", "Continental shelf", "Mid-ocean"], correctIndex: 1 },
    { text: "What sea is north of Norway?", options: ["Baltic", "Barents Sea", "North Sea", "Norwegian Sea"], correctIndex: 3 },
    { text: "What is the Great Pacific Garbage Patch?", options: ["Island", "Plastic debris accumulation", "Reef", "Current"], correctIndex: 1 },
    { text: "What body of water is between Mexico and Cuba?", options: ["Caribbean", "Gulf of Mexico", "Pacific", "Atlantic"], correctIndex: 1 },
    { text: "What is bioluminescence in the ocean?", options: ["Pollution", "Light produced by organisms", "Reflection", "Volcanic activity"], correctIndex: 1 },
    { text: "What sea is between Denmark and Sweden?", options: ["North Sea", "Baltic Sea", "Norwegian Sea", "Kattegat"], correctIndex: 1 },
    { text: "What is a tsunami?", options: ["Tide", "Large wave from underwater disturbance", "Current", "Storm"], correctIndex: 1 },
    { text: "What is the Sargasso Sea known for?", options: ["Ice", "Floating seaweed", "Volcanic activity", "Glaciers"], correctIndex: 1 },
    { text: "What is ocean acidification?", options: ["Saltiness increasing", "pH decreasing from CO2 absorption", "Temperature rising", "Pollution"], correctIndex: 1 },
];
