export const photographyQuestions = [

    // Photography (50 questions)
    { text: "What does ISO control in photography?", options: ["Focus", "Light sensitivity", "Color", "Zoom"], correctIndex: 1 },
    { text: "What does aperture control?", options: ["Shutter speed", "Light entering lens", "Zoom level", "ISO"], correctIndex: 1 },
    { text: "What is the rule of thirds?", options: ["Three exposures", "Composition guideline", "Three lenses", "Printing rule"], correctIndex: 1 },
    { text: "What does DSLR stand for?", options: ["Digital Single Lens Reflex", "Direct Simple Light Recorder", "Digital Standard Light Receiver", "Double Sensor Light Reflector"], correctIndex: 0 },
    { text: "Who is credited with taking the first photograph?", options: ["Ansel Adams", "Nicéphore Niépce", "Louis Daguerre", "George Eastman"], correctIndex: 1 },
    { text: "What is bokeh?", options: ["Camera brand", "Blurred background effect", "Type of lens", "Editing software"], correctIndex: 1 },
    { text: "What does RAW format preserve?", options: ["Compressed data", "All unprocessed image data", "Thumbnails only", "Metadata only"], correctIndex: 1 },
    { text: "What is the golden hour?", options: ["Noon", "Hour after sunrise/before sunset", "Midnight", "Any time"], correctIndex: 1 },
    { text: "Who founded Magnum Photos?", options: ["Ansel Adams", "Robert Capa and others", "Diane Arbus", "Richard Avedon"], correctIndex: 1 },
    { text: "What is a prime lens?", options: ["Expensive lens", "Fixed focal length", "Zoom lens", "Wide angle"], correctIndex: 1 },
    { text: "What does exposure triangle consist of?", options: ["ISO, aperture, focus", "ISO, aperture, shutter speed", "Zoom, ISO, aperture", "Color, light, shadow"], correctIndex: 1 },
    { text: "Who photographed 'Migrant Mother'?", options: ["Ansel Adams", "Dorothea Lange", "Walker Evans", "Margaret Bourke-White"], correctIndex: 1 },
    { text: "What is HDR?", options: ["High Definition Recording", "High Dynamic Range", "Heavy Duty Reflex", "Hybrid Digital Resolution"], correctIndex: 1 },
    { text: "What does f-stop measure?", options: ["Shutter speed", "Aperture size", "ISO sensitivity", "Focal length"], correctIndex: 1 },
    { text: "Who is known for black and white landscape photography?", options: ["Henri Cartier-Bresson", "Ansel Adams", "Diane Arbus", "Robert Frank"], correctIndex: 1 },
    { text: "What is the decisive moment?", options: ["Sunset", "Perfect timing to capture", "Noon", "Flash moment"], correctIndex: 1 },
    { text: "What does macro photography capture?", options: ["Landscapes", "Close-up small subjects", "Wide vistas", "Portraits"], correctIndex: 1 },
    { text: "Who photographed 'Afghan Girl'?", options: ["Annie Leibovitz", "Steve McCurry", "Sebastião Salgado", "James Nachtwey"], correctIndex: 1 },
    { text: "What is depth of field?", options: ["Camera weight", "Area in focus", "Zoom range", "Sensor size"], correctIndex: 1 },
    { text: "What company introduced the Kodak camera?", options: ["Canon", "George Eastman/Kodak", "Nikon", "Leica"], correctIndex: 1 },
    { text: "What is white balance?", options: ["Exposure level", "Color temperature adjustment", "Contrast setting", "Brightness control"], correctIndex: 1 },
    { text: "Who coined the term 'decisive moment'?", options: ["Ansel Adams", "Henri Cartier-Bresson", "Robert Capa", "Diane Arbus"], correctIndex: 1 },
    { text: "What is panning in photography?", options: ["Zooming in", "Following moving subject", "Tilting up", "Focusing"], correctIndex: 1 },
    { text: "What does TTL stand for?", options: ["Time To Light", "Through The Lens", "Total Tonal Level", "Timed Technical Lighting"], correctIndex: 1 },
    { text: "Who photographed 'V-J Day in Times Square' (kissing sailor)?", options: ["Robert Capa", "Alfred Eisenstaedt", "Weegee", "W. Eugene Smith"], correctIndex: 1 },
    { text: "What is chromatic aberration?", options: ["Color fringing", "Correct colors", "Black and white", "Sepia tone"], correctIndex: 0 },
    { text: "What is the Daguerreotype?", options: ["Camera brand", "Early photographic process", "Lens type", "Film format"], correctIndex: 1 },
    { text: "Who photographed Yosemite extensively?", options: ["Edward Weston", "Ansel Adams", "Imogen Cunningham", "Paul Strand"], correctIndex: 1 },
    { text: "What is fill flash used for?", options: ["Night photography", "Reducing shadows in daylight", "Studio only", "Slow motion"], correctIndex: 1 },
    { text: "What is a histogram in photography?", options: ["Timeline", "Graph of tonal distribution", "Map", "Checklist"], correctIndex: 1 },
    { text: "Who founded the f/64 group?", options: ["Henri Cartier-Bresson", "Ansel Adams and others", "Robert Frank", "Diane Arbus"], correctIndex: 1 },
    { text: "What is vignetting?", options: ["Center brightness", "Darkened corners", "Color shift", "Lens flare"], correctIndex: 1 },
    { text: "What is the sunny 16 rule?", options: ["Composition rule", "Exposure guideline", "Focus technique", "Lighting setup"], correctIndex: 1 },
    { text: "Who photographed 'Moonrise, Hernandez, New Mexico'?", options: ["Edward Weston", "Ansel Adams", "Minor White", "Paul Strand"], correctIndex: 1 },
    { text: "What is bracketing?", options: ["Camera support", "Taking multiple exposures", "Lens attachment", "Editing technique"], correctIndex: 1 },
    { text: "What is the zone system?", options: ["Geographic zones", "Tonal range control method", "Camera zones", "Lens zones"], correctIndex: 1 },
    { text: "Who photographed 'The Americans' series?", options: ["Henri Cartier-Bresson", "Robert Frank", "Walker Evans", "Lee Friedlander"], correctIndex: 1 },
    { text: "What is a lens hood used for?", options: ["Storage", "Reducing flare and glare", "Zooming", "Color correction"], correctIndex: 1 },
    { text: "What is grain in film photography?", options: ["Texture on prints", "Metal particles in film", "Camera shake", "Focus issue"], correctIndex: 0 },
    { text: "Who is known for fashion and portrait photography?", options: ["Ansel Adams", "Richard Avedon", "Edward Weston", "Walker Evans"], correctIndex: 1 },
    { text: "What is reciprocity in photography?", options: ["Camera exchange", "Relationship between aperture and shutter", "Lens reciprocity", "Flash sync"], correctIndex: 1 },
    { text: "What is the difference between JPEG and RAW?", options: ["Size only", "Compression and data retention", "Color only", "No difference"], correctIndex: 1 },
    { text: "Who photographed Civil War scenes extensively?", options: ["Ansel Adams", "Mathew Brady", "Alfred Stieglitz", "Edward Steichen"], correctIndex: 1 },
    { text: "What is lens distortion?", options: ["Dirt on lens", "Image warping", "Color shift", "Focus problem"], correctIndex: 1 },
    { text: "What is chimping?", options: ["Flash technique", "Reviewing photos on LCD immediately", "Lens cleaning", "Tripod adjustment"], correctIndex: 1 },
    { text: "Who founded Photo-Secession?", options: ["Edward Weston", "Alfred Stieglitz", "Ansel Adams", "Man Ray"], correctIndex: 1 },
    { text: "What is a neutral density filter?", options: ["Color correction", "Reduces light entering lens", "Adds contrast", "Sharpens image"], correctIndex: 1 },
    { text: "What is the difference between optical and digital zoom?", options: ["No difference", "Optical uses lens, digital crops", "Speed", "Color accuracy"], correctIndex: 1 },
    { text: "Who photographed 'Pepper No. 30'?", options: ["Ansel Adams", "Edward Weston", "Imogen Cunningham", "Paul Strand"], correctIndex: 1 },
    { text: "What is hyperfocal distance?", options: ["Minimum focus", "Focus for maximum depth of field", "Maximum zoom", "Sensor distance"], correctIndex: 1 },
];
