export const scienceQuestions = [

    // Science
    { text: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], correctIndex: 2 },
    { text: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], correctIndex: 1 },
    { text: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"], correctIndex: 2 },
    { text: "What is the speed of light in vacuum (approximately)?", options: ["299,792 km/s", "150,000 km/s", "500,000 km/s", "100,000 km/s"], correctIndex: 0 },
    { text: "Which gas do plants absorb from the air for photosynthesis?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correctIndex: 2 },
    { text: "What is the atomic number of carbon?", options: ["6", "8", "12", "14"], correctIndex: 0 },
    { text: "What is the chemical formula for water?", options: ["H2O2", "H2O", "HO2", "H3O"], correctIndex: 1 },
    { text: "What type of bond forms when electrons are shared between atoms?", options: ["Ionic", "Covalent", "Metallic", "Hydrogen"], correctIndex: 1 },
    { text: "What does Newton's first law of motion state?", options: ["F = ma", "Objects at rest stay at rest unless acted upon by a force", "Energy is always conserved", "Every action has an equal and opposite reaction"], correctIndex: 1 },
    { text: "What is the SI unit of electric current?", options: ["Volt", "Watt", "Ampere", "Ohm"], correctIndex: 2 },
    { text: "Which gas makes up the majority of Earth's atmosphere?", options: ["Oxygen", "Carbon dioxide", "Argon", "Nitrogen"], correctIndex: 3 },
    { text: "What is the process by which a liquid turns into a gas?", options: ["Condensation", "Sublimation", "Evaporation", "Precipitation"], correctIndex: 2 },
    { text: "What is the SI unit of force?", options: ["Joule", "Newton", "Pascal", "Watt"], correctIndex: 1 },
    { text: "What is the chemical formula for table salt?", options: ["NaCl", "KCl", "CaCl2", "MgCl2"], correctIndex: 0 },
    { text: "What type of rock is formed from cooled lava or magma?", options: ["Sedimentary", "Metamorphic", "Igneous", "Limestone"], correctIndex: 2 },
    { text: "What is the approximate speed of sound in air?", options: ["343 m/s", "150 m/s", "1,500 m/s", "5,000 m/s"], correctIndex: 0 },
    { text: "Which organ in the body produces insulin?", options: ["Liver", "Pancreas", "Kidney", "Thyroid"], correctIndex: 1 },
    { text: "What is the hardest natural substance on Earth?", options: ["Gold", "Quartz", "Diamond", "Titanium"], correctIndex: 2 },
    { text: "How many chromosomes does a typical human cell contain?", options: ["23", "46", "92", "64"], correctIndex: 1 },
    { text: "What is the chemical symbol for iron?", options: ["Ir", "In", "Fe", "Fr"], correctIndex: 2 },
    { text: "What is the pH of pure water?", options: ["5", "7", "9", "11"], correctIndex: 1 },
    { text: "What force opposes motion between two surfaces in contact?", options: ["Gravity", "Friction", "Tension", "Normal force"], correctIndex: 1 },
    { text: "What is the chemical symbol for sodium?", options: ["So", "Sa", "Na", "Nm"], correctIndex: 2 },
    { text: "What is the primary function of red blood cells?", options: ["Fighting infection", "Carrying oxygen", "Clotting blood", "Producing hormones"], correctIndex: 1 },
    { text: "What type of energy does a moving object possess?", options: ["Potential energy", "Thermal energy", "Kinetic energy", "Chemical energy"], correctIndex: 2 },
    { text: "What is the boiling point of water at sea level?", options: ["90°C", "100°C", "110°C", "80°C"], correctIndex: 1 },
    { text: "What is the name of the process by which cells divide to produce identical copies?", options: ["Meiosis", "Mitosis", "Fission", "Budding"], correctIndex: 1 },
    { text: "Which particle has a negative charge?", options: ["Proton", "Neutron", "Electron", "Positron"], correctIndex: 2 },
    { text: "What is the chemical formula for carbon dioxide?", options: ["CO", "CO2", "C2O", "CO3"], correctIndex: 1 },
    { text: "Which vitamin is produced by the skin when exposed to sunlight?", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], correctIndex: 3 },
    { text: "What is the term for organisms that produce their own food through photosynthesis?", options: ["Heterotrophs", "Autotrophs", "Decomposers", "Parasites"], correctIndex: 1 },
    { text: "What type of wave is sound?", options: ["Transverse", "Longitudinal", "Electromagnetic", "Standing"], correctIndex: 1 },
    { text: "How many bones are in the adult human body?", options: ["196", "206", "216", "226"], correctIndex: 1 },
    { text: "What does the law of conservation of energy state?", options: ["Energy can be created from nothing", "Energy can be permanently destroyed", "Energy cannot be created or destroyed", "Energy equals mass times speed of light"], correctIndex: 2 },
    { text: "What is the smallest unit of life?", options: ["Atom", "Molecule", "Cell", "Organ"], correctIndex: 2 },
    { text: "Which type of electromagnetic radiation has the highest energy?", options: ["Radio waves", "Visible light", "X-rays", "Gamma rays"], correctIndex: 3 },
    { text: "What is the chemical formula for glucose?", options: ["C6H12O6", "C12H22O11", "C2H5OH", "CH4"], correctIndex: 0 },
    { text: "What is the measure of the amount of matter in an object?", options: ["Weight", "Density", "Mass", "Volume"], correctIndex: 2 },
    { text: "What is the primary function of the nucleus in a cell?", options: ["Energy production", "Protein synthesis", "Storing and transmitting DNA", "Cell movement"], correctIndex: 2 },
    { text: "What is the SI unit of energy?", options: ["Newton", "Watt", "Joule", "Pascal"], correctIndex: 2 },
    { text: "Which gas is produced as a byproduct of photosynthesis?", options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"], correctIndex: 2 },
    { text: "What is the term for an organism that eats only plants?", options: ["Carnivore", "Herbivore", "Omnivore", "Detritivore"], correctIndex: 1 },
    { text: "What is the atomic number of hydrogen?", options: ["1", "2", "3", "4"], correctIndex: 0 },
    { text: "What type of lens curves inward at the center?", options: ["Convex", "Concave", "Bifocal", "Plano-convex"], correctIndex: 1 },
    { text: "Which element is most abundant in Earth's crust?", options: ["Silicon", "Aluminum", "Iron", "Oxygen"], correctIndex: 3 },
    { text: "What is the term for the force that keeps electrons orbiting the nucleus?", options: ["Gravity", "Magnetic force", "Electromagnetic force", "Strong nuclear force"], correctIndex: 2 },
    { text: "How many chambers does the human heart have?", options: ["2", "3", "4", "5"], correctIndex: 2 },
    { text: "What is the chemical symbol for helium?", options: ["H", "He", "Hi", "Hl"], correctIndex: 1 },
    { text: "What process breaks down food to release energy in cells?", options: ["Photosynthesis", "Fermentation", "Cellular respiration", "Transpiration"], correctIndex: 2 },
    { text: "Which layer of the atmosphere contains the ozone layer?", options: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"], correctIndex: 1 },
];
