export const sportsQuestions = [

    // Sports
    { text: "How many players are on a soccer team on the field?", options: ["9", "10", "11", "12"], correctIndex: 2 },
    { text: "Which country has won the most FIFA World Cups?", options: ["Germany", "Italy", "Brazil", "Argentina"], correctIndex: 2 },
    { text: "In tennis, what is the term for a score of zero?", options: ["Nil", "Love", "Zip", "Nothing"], correctIndex: 1 },
    { text: "How many Grand Slam tennis tournaments are held each year?", options: ["2", "3", "4", "5"], correctIndex: 2 },
    { text: "Which sport is often called 'The Beautiful Game'?", options: ["Basketball", "Soccer", "Cricket", "Baseball"], correctIndex: 1 },
    { text: "How many players are on a basketball team on the court at one time?", options: ["4", "5", "6", "7"], correctIndex: 1 },
    { text: "What is the maximum score in a single frame of bowling?", options: ["20", "24", "30", "36"], correctIndex: 2 },
    { text: "In which sport would you perform a slam dunk?", options: ["Volleyball", "Basketball", "Handball", "Water Polo"], correctIndex: 1 },
    { text: "How many holes are in a standard round of golf?", options: ["9", "18", "27", "36"], correctIndex: 1 },
    { text: "What is the term for three consecutive strikes in bowling?", options: ["Strike", "Spare", "Turkey", "Double"], correctIndex: 2 },
    { text: "Which sport uses a shuttlecock?", options: ["Tennis", "Badminton", "Squash", "Racquetball"], correctIndex: 1 },
    { text: "How many players are on a baseball team in the field?", options: ["8", "9", "10", "11"], correctIndex: 1 },
    { text: "Both ice hockey and lacrosse are official national sports of which country?", options: ["United States", "Sweden", "Canada", "Finland"], correctIndex: 2 },
    { text: "In which sport do players use a puck?", options: ["Field hockey", "Lacrosse", "Ice hockey", "Polo"], correctIndex: 2 },
    { text: "How far is a standard marathon race?", options: ["25.0 miles", "26.2 miles", "27.0 miles", "24.5 miles"], correctIndex: 1 },
    { text: "Who invented the sport of basketball?", options: ["James Naismith", "Walter Camp", "Abner Doubleday", "William Morgan"], correctIndex: 0 },
    { text: "In Olympic swimming, how many different strokes are used in an individual medley?", options: ["2", "3", "4", "5"], correctIndex: 2 },
    { text: "What color is the highest-value ball in snooker?", options: ["Red", "Black", "Pink", "Yellow"], correctIndex: 1 },
    { text: "How many rounds are in a standard world championship professional boxing match?", options: ["10", "12", "15", "20"], correctIndex: 1 },
    { text: "How many players are on a volleyball team on the court?", options: ["4", "5", "6", "7"], correctIndex: 2 },
    { text: "Which country hosted the first modern Olympic Games in 1896?", options: ["Italy", "Greece", "France", "England"], correctIndex: 1 },
    { text: "How many sets are in a standard men's Grand Slam tennis match?", options: ["3", "4", "5", "7"], correctIndex: 2 },
    { text: "How many points is a touchdown worth in American football?", options: ["3", "6", "7", "8"], correctIndex: 1 },
    { text: "In which sport would you find a birdie, eagle, and bogey?", options: ["Cricket", "Tennis", "Golf", "Archery"], correctIndex: 2 },
    { text: "How many points is a field goal worth in American football?", options: ["1", "2", "3", "4"], correctIndex: 2 },
    { text: "What is the term for winning all four Grand Slam titles in a single calendar year?", options: ["Grand Slam", "Calendar Grand Slam", "Super Slam", "Golden Slam"], correctIndex: 1 },
    { text: "How many players are on a rugby union team?", options: ["13", "14", "15", "16"], correctIndex: 2 },
    { text: "Which country won the first FIFA World Cup in 1930?", options: ["Brazil", "Argentina", "Italy", "Uruguay"], correctIndex: 3 },
    { text: "How many minutes are in a regulation NBA basketball game?", options: ["40", "48", "50", "60"], correctIndex: 1 },
    { text: "What is the length of a standard Olympic swimming pool?", options: ["25m", "50m", "75m", "100m"], correctIndex: 1 },
    { text: "How many balls are in a standard cricket over?", options: ["4", "5", "6", "7"], correctIndex: 2 },
    { text: "What color flag is waved at the end of a Formula 1 race?", options: ["Red", "Black and white checkered", "White", "Yellow"], correctIndex: 1 },
    { text: "How many players are on an ice hockey team on the ice?", options: ["4", "5", "6", "7"], correctIndex: 2 },
    { text: "What is the maximum possible break in snooker?", options: ["147", "155", "160", "180"], correctIndex: 0 },
    { text: "Which major golf tournament is played at Augusta National?", options: ["The Open Championship", "The Masters", "US Open", "PGA Championship"], correctIndex: 1 },
    { text: "How many rings are on the Olympic flag?", options: ["4", "5", "6", "7"], correctIndex: 1 },
    { text: "In which sport would you take a 'free throw'?", options: ["Soccer", "Rugby", "Basketball", "Handball"], correctIndex: 2 },
    { text: "What sport does Usain Bolt compete in?", options: ["Swimming", "Cycling", "Track and field", "Decathlon"], correctIndex: 2 },
    { text: "How many events make up a decathlon?", options: ["8", "9", "10", "12"], correctIndex: 2 },
    { text: "In what year were the first modern Olympic Games held?", options: ["1892", "1896", "1900", "1904"], correctIndex: 1 },
    { text: "How many players are on a field hockey team?", options: ["9", "10", "11", "12"], correctIndex: 2 },
    { text: "What is the term for a score of 2 under par in golf?", options: ["Birdie", "Eagle", "Albatross", "Bogey"], correctIndex: 1 },
    { text: "In which sport would you use a pommel horse?", options: ["Swimming", "Track and field", "Gymnastics", "Weightlifting"], correctIndex: 2 },
    { text: "What is the highest-scoring single play possible in American football?", options: ["Touchdown (6 points)", "Safety (2 points)", "Field goal (3 points)", "Two-point conversion"], correctIndex: 0 },
    { text: "In tennis, what is a 'deuce'?", options: ["A 2-0 lead", "A score of 40-40", "Winning 6-0", "A fault on second serve"], correctIndex: 1 },
    { text: "Which country has hosted the most Summer Olympic Games?", options: ["France", "United States", "Great Britain", "Greece"], correctIndex: 1 },
    { text: "How far apart are the wickets in cricket?", options: ["18 yards", "20 yards", "22 yards", "24 yards"], correctIndex: 2 },
    { text: "In boxing, what is it called when a fighter is knocked down and cannot rise before the count of 10?", options: ["Technical knockout", "Knockout", "Disqualification", "Submission"], correctIndex: 1 },
    { text: "Which gymnastic apparatus involves swinging on two hanging rings?", options: ["Parallel bars", "Horizontal bar", "Still rings", "Balance beam"], correctIndex: 2 },
    { text: "How many players are on each side in a polo match?", options: ["2", "3", "4", "6"], correctIndex: 2 },
];
