export const statisticsQuestions = [

    // Statistics (50 questions)
    { text: "What is the mean of 2, 4, 6, 8, 10?", options: ["5", "6", "7", "8"], correctIndex: 1 },
    { text: "What is the median of 3, 7, 2, 9, 5?", options: ["3", "5", "7", "9"], correctIndex: 1 },
    { text: "What is the mode of 2, 3, 3, 4, 5?", options: ["2", "3", "4", "5"], correctIndex: 1 },
    { text: "What does standard deviation measure?", options: ["Central tendency", "Spread of data", "Probability", "Frequency"], correctIndex: 1 },
    { text: "What is the range of 5, 10, 15, 20?", options: ["5", "10", "15", "20"], correctIndex: 2 },
    { text: "What is probability of flipping heads on a fair coin?", options: ["0.25", "0.5", "0.75", "1"], correctIndex: 1 },
    { text: "What is the sum of all probabilities in a distribution?", options: ["0", "0.5", "1", "100"], correctIndex: 2 },
    { text: "What does correlation measure?", options: ["Causation", "Relationship strength", "Variance", "Mean"], correctIndex: 1 },
    { text: "What is the median of an even number of values?", options: ["Middle value", "Average of two middle values", "Highest value", "Mode"], correctIndex: 1 },
    { text: "What is variance?", options: ["Standard deviation squared", "Square root of standard deviation", "Mean squared", "Range divided by 2"], correctIndex: 0 },
    { text: "What is a population in statistics?", options: ["Sample group", "Entire group being studied", "Random selection", "Data set"], correctIndex: 1 },
    { text: "What is a sample?", options: ["Entire population", "Subset of population", "Mean value", "Mode"], correctIndex: 1 },
    { text: "What is the probability of rolling a 6 on a fair die?", options: ["1/2", "1/3", "1/6", "1/12"], correctIndex: 2 },
    { text: "What does the 50th percentile represent?", options: ["Mean", "Median", "Mode", "Range"], correctIndex: 1 },
    { text: "What is a normal distribution also called?", options: ["Uniform distribution", "Bell curve", "Skewed distribution", "Binomial distribution"], correctIndex: 1 },
    { text: "What are the chances of getting tails twice in two coin flips?", options: ["1/2", "1/3", "1/4", "1/8"], correctIndex: 2 },
    { text: "What is the first quartile (Q1)?", options: ["25th percentile", "50th percentile", "75th percentile", "100th percentile"], correctIndex: 0 },
    { text: "What is an outlier?", options: ["The mean", "A data point far from others", "The median", "The mode"], correctIndex: 1 },
    { text: "What does IQR stand for?", options: ["Internal Quality Range", "Interquartile Range", "Interval Query Range", "Independent Quantile Ratio"], correctIndex: 1 },
    { text: "What is the mean of 10, 20, 30?", options: ["10", "15", "20", "25"], correctIndex: 2 },
    { text: "What type of data is height?", options: ["Discrete", "Categorical", "Continuous", "Nominal"], correctIndex: 2 },
    { text: "What is a histogram used for?", options: ["Showing relationships", "Displaying frequency distribution", "Comparing categories", "Showing trends"], correctIndex: 1 },
    { text: "What does a p-value indicate?", options: ["Mean value", "Statistical significance", "Standard deviation", "Correlation"], correctIndex: 1 },
    { text: "What is the mode of 1, 2, 2, 3, 4, 4, 4, 5?", options: ["2", "3", "4", "5"], correctIndex: 2 },
    { text: "What is a z-score?", options: ["Mean value", "Number of standard deviations from mean", "Probability", "Sample size"], correctIndex: 1 },
    { text: "What is the range of probabilities?", options: ["[-1, 1]", "[0, 1]", "[0, 100]", "Any real number"], correctIndex: 1 },
    { text: "What is sampling error?", options: ["Calculation mistake", "Difference between sample and population", "Data entry error", "Measurement error"], correctIndex: 1 },
    { text: "What is central tendency?", options: ["Spread of data", "Center of distribution", "Relationship between variables", "Sample size"], correctIndex: 1 },
    { text: "What is the complement of an event with probability 0.3?", options: ["0.3", "0.5", "0.7", "1"], correctIndex: 2 },
    { text: "What type of graph is best for showing parts of a whole?", options: ["Bar chart", "Line graph", "Pie chart", "Histogram"], correctIndex: 2 },
    { text: "What is regression analysis used for?", options: ["Finding mode", "Predicting relationships", "Calculating mean", "Finding range"], correctIndex: 1 },
    { text: "What is the median of 1, 3, 5, 7, 9?", options: ["3", "5", "7", "9"], correctIndex: 1 },
    { text: "What does a correlation of -1 indicate?", options: ["No relationship", "Perfect positive correlation", "Perfect negative correlation", "Weak correlation"], correctIndex: 2 },
    { text: "What is a confidence interval?", options: ["Range for population parameter", "Mean value", "Standard deviation", "Sample size"], correctIndex: 0 },
    { text: "What is categorical data?", options: ["Numerical measurements", "Data in categories", "Continuous data", "Time series data"], correctIndex: 1 },
    { text: "What is a Type I error?", options: ["Accepting false null hypothesis", "Rejecting true null hypothesis", "Calculation error", "Sampling error"], correctIndex: 1 },
    { text: "What is the third quartile (Q3)?", options: ["25th percentile", "50th percentile", "75th percentile", "100th percentile"], correctIndex: 2 },
    { text: "What does it mean if data is bimodal?", options: ["Has one mode", "Has two modes", "Has no mode", "Is normally distributed"], correctIndex: 1 },
    { text: "What is random sampling?", options: ["Selecting specific individuals", "Every member has equal chance", "Convenience sampling", "Purposive sampling"], correctIndex: 1 },
    { text: "What is the coefficient of variation?", options: ["Mean/SD", "SD/Mean", "Variance/Mean", "Mean/Variance"], correctIndex: 1 },
    { text: "What is expected value?", options: ["Most likely outcome", "Long-run average", "Maximum value", "Minimum value"], correctIndex: 1 },
    { text: "What is a box plot used for?", options: ["Showing frequency", "Displaying five-number summary", "Comparing means", "Showing correlation"], correctIndex: 1 },
    { text: "What does skewness measure?", options: ["Center", "Spread", "Asymmetry", "Correlation"], correctIndex: 2 },
    { text: "What is the null hypothesis typically?", options: ["Alternative claim", "No effect or difference", "Research hypothesis", "Positive result"], correctIndex: 1 },
    { text: "What is statistical inference?", options: ["Describing data", "Drawing conclusions about populations", "Calculating means", "Creating graphs"], correctIndex: 1 },
    { text: "What is a scatter plot used for?", options: ["Showing frequency", "Displaying relationship between two variables", "Comparing categories", "Showing time series"], correctIndex: 1 },
    { text: "What is the law of large numbers?", options: ["Larger samples always better", "Sample mean approaches population mean", "Probabilities always equal", "Larger variance is better"], correctIndex: 1 },
    { text: "What is a frequency distribution?", options: ["Mean of data", "How often values occur", "Spread of data", "Correlation"], correctIndex: 1 },
    { text: "What does mutually exclusive mean?", options: ["Events can occur together", "Events cannot occur together", "Independent events", "Dependent events"], correctIndex: 1 },
    { text: "What is the 68-95-99.7 rule for?", options: ["Uniform distribution", "Normal distribution", "Binomial distribution", "Poisson distribution"], correctIndex: 1 },
];
