export const technologyQuestions = [

    // Technology
    { text: "What does CPU stand for?", options: ["Central Processing Unit", "Central Processor Unit", "Computer Processing Unit", "Central Processing Unit"], correctIndex: 0 },
    { text: "What does GPU stand for?", options: ["Graphics Processing Unit", "Good Parnter Unit", "Computer Processing Unit", "Central Processing Unit"], correctIndex: 0 },
    { text: "What does RAM stand for?", options: ["Random Access Memory", "Random Processor Unit", "Computer Processing Unit", "Central Processing Unit"], correctIndex: 0 },
    { text: "What does ROM stand for?", options: ["Read Only Memory", "Random Processor Unit", "Computer Processing Unit", "Central Processing Unit"], correctIndex: 0 },
    { text: "What does HTML stand for?", options: ["Hyper Text Markup Language", "Hyper Processor Unit", "Computer Processing Unit", "Central Processing Unit"], correctIndex: 0 },

    // Technology (50 questions)
    { text: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Processing Unit"], correctIndex: 0 },
    { text: "What does RAM stand for?", options: ["Random Access Memory", "Rapid Application Memory", "Read Access Module", "Remote Access Memory"], correctIndex: 0 },
    { text: "What is the binary number system based on?", options: ["0 and 1", "1 and 2", "0 and 2", "1 and 10"], correctIndex: 0 },
    { text: "Who is credited with inventing the World Wide Web?", options: ["Bill Gates", "Tim Berners-Lee", "Steve Jobs", "Mark Zuckerberg"], correctIndex: 1 },
    { text: "What does USB stand for?", options: ["Universal Serial Bus", "United System Base", "Universal System Board", "Unified Serial Base"], correctIndex: 0 },
    { text: "What is an algorithm?", options: ["A type of code", "Step-by-step procedure", "Programming language", "Computer hardware"], correctIndex: 1 },
    { text: "What does HTML stand for?", options: ["HyperText Markup Language", "HighTech Modern Language", "Hyper Transfer Markup Language", "Home Tool Markup Language"], correctIndex: 0 },
    { text: "What is cloud computing?", options: ["Weather prediction", "Internet-based computing services", "Sky photography", "Satellite technology"], correctIndex: 1 },
    { text: "What is artificial intelligence?", options: ["Fake technology", "Machine intelligence", "Robot building", "Computer gaming"], correctIndex: 1 },
    { text: "What does Wi-Fi stand for?", options: ["Wireless Fidelity", "Wide Fiber", "Wired Fidelity", "Web Interface"], correctIndex: 0 },
    { text: "What is a byte?", options: ["1 bit", "8 bits", "16 bits", "4 bits"], correctIndex: 1 },
    { text: "Who co-founded Apple?", options: ["Bill Gates", "Steve Jobs and Steve Wozniak", "Mark Zuckerberg", "Elon Musk"], correctIndex: 1 },
    { text: "What is encryption?", options: ["Data deletion", "Data protection/encoding", "Data storage", "Data transfer"], correctIndex: 1 },
    { text: "What does GPU stand for?", options: ["General Processing Unit", "Graphics Processing Unit", "Game Performance Unit", "Global Processing Utility"], correctIndex: 1 },
    { text: "What is blockchain?", options: ["Building blocks", "Distributed ledger technology", "Video game", "Social media"], correctIndex: 1 },
    { text: "What does VPN stand for?", options: ["Virtual Private Network", "Very Private Network", "Visual Program Network", "Verified Public Network"], correctIndex: 0 },
    { text: "What is malware?", options: ["Male software", "Malicious software", "Mail software", "Main software"], correctIndex: 1 },
    { text: "What does SSD stand for?", options: ["Super Speed Drive", "Solid State Drive", "System Storage Device", "Special Storage Disk"], correctIndex: 1 },
    { text: "What is the Internet of Things (IoT)?", options: ["Online shopping", "Connected smart devices", "Internet history", "Web hosting"], correctIndex: 1 },
    { text: "What programming language is known for web development?", options: ["C++", "JavaScript", "Assembly", "COBOL"], correctIndex: 1 },
    { text: "What is open source software?", options: ["Expensive software", "Publicly accessible code", "Closed software", "Microsoft only"], correctIndex: 1 },
    { text: "What does API stand for?", options: ["Application Programming Interface", "Advanced Program Integration", "Automated Processing Interface", "Applied Program Interaction"], correctIndex: 0 },
    { text: "What is phishing?", options: ["Fishing game", "Fraudulent attempt to obtain information", "Internet speed", "File sharing"], correctIndex: 1 },
    { text: "What is machine learning?", options: ["Teaching robots", "AI learning from data", "Factory automation", "Computer repair"], correctIndex: 1 },
    { text: "What does URL stand for?", options: ["Universal Resource Locator", "Uniform Resource Locator", "United Reference Link", "Unique Resource Locator"], correctIndex: 1 },
    { text: "What is a firewall?", options: ["Fire protection", "Network security system", "Wall material", "Heating system"], correctIndex: 1 },
    { text: "What is virtual reality (VR)?", options: ["Real environment", "Simulated 3D environment", "2D images", "Television"], correctIndex: 1 },
    { text: "What does BIOS stand for?", options: ["Basic Input/Output System", "Binary Internal Operating System", "Base Internet Operating System", "Built-In Output System"], correctIndex: 0 },
    { text: "What is cryptocurrency?", options: ["Secret code", "Digital currency", "Credit card", "Bank account"], correctIndex: 1 },
    { text: "What does HTTP stand for?", options: ["HyperText Transfer Protocol", "High Transfer Text Protocol", "Hyper Transfer Type Protocol", "Home Text Transfer Protocol"], correctIndex: 0 },
    { text: "What is a server?", options: ["Waiter", "Computer providing services/resources", "Software only", "Monitor"], correctIndex: 1 },
    { text: "What is augmented reality (AR)?", options: ["Virtual world", "Real world with digital overlay", "3D movies", "Video games"], correctIndex: 1 },
    { text: "What does SQL stand for?", options: ["Structured Query Language", "Simple Question Language", "System Quality Language", "Standard Query Logic"], correctIndex: 0 },
    { text: "What is a router?", options: ["Road direction", "Device directing network traffic", "Power supply", "Storage device"], correctIndex: 1 },
    { text: "What is quantum computing?", options: ["Fast regular computing", "Computing using quantum mechanics", "Cloud computing", "Mobile computing"], correctIndex: 1 },
    { text: "What does OS stand for?", options: ["Online System", "Operating System", "Optical Service", "Open Source"], correctIndex: 1 },
    { text: "What is 5G?", options: ["5 gigabytes", "Fifth generation cellular network", "5 computers", "Game version"], correctIndex: 1 },
    { text: "What is a cookie in web terms?", options: ["Snack", "Small data file", "Virus", "Hardware"], correctIndex: 1 },
    { text: "What does CAPTCHA stand for?", options: ["Capture", "Completely Automated Public Turing test", "Computer And Program Test", "Code Access Protocol"], correctIndex: 1 },
    { text: "What is bandwidth?", options: ["Music frequency", "Data transfer capacity", "Band width", "Radio station"], correctIndex: 1 },
    { text: "What is debugging?", options: ["Removing insects", "Finding and fixing code errors", "Deleting programs", "Cleaning computer"], correctIndex: 1 },
    { text: "What does LAN stand for?", options: ["Long Area Network", "Local Area Network", "Large Application Network", "Linear Access Network"], correctIndex: 1 },
    { text: "What is biometric authentication?", options: ["Password only", "Biological characteristic identification", "Two-factor only", "PIN code"], correctIndex: 1 },
    { text: "What is a pixel?", options: ["Picture element", "Point element", "Pixel fairy", "Photo inch"], correctIndex: 0 },
    { text: "What does PDF stand for?", options: ["Pretty Document Format", "Portable Document Format", "Print Document File", "Public Digital Format"], correctIndex: 1 },
    { text: "What is the dark web?", options: ["Night mode", "Hidden internet requiring special access", "Black websites", "Broken internet"], correctIndex: 1 },
    { text: "What is Moore's Law?", options: ["Legal regulation", "Transistor count doubles periodically", "Internet speed law", "Data storage law"], correctIndex: 1 },
    { text: "What is a botnet?", options: ["Robot network", "Network of infected computers", "Bot game", "AI network"], correctIndex: 1 },
    { text: "What does GUI stand for?", options: ["General User Interface", "Graphical User Interface", "Global Unified Interface", "Generated User Interaction"], correctIndex: 1 },
    { text: "What is nanotechnology?", options: ["Nano iPods", "Technology at atomic scale", "Small computers", "Miniature phones"], correctIndex: 1 },
];
