export const trigonometryQuestions = [

    // Trigonometry (50 questions)
    { text: "What is sin(90°)?", options: ["0", "1", "√2/2", "1/2"], correctIndex: 1 },
    { text: "What is cos(0°)?", options: ["0", "1", "-1", "1/2"], correctIndex: 1 },
    { text: "What is tan(45°)?", options: ["0", "1", "√3", "1/√3"], correctIndex: 1 },
    { text: "What is the reciprocal of sine?", options: ["Cosine", "Tangent", "Cosecant", "Secant"], correctIndex: 2 },
    { text: "What is sin²θ + cos²θ equal to?", options: ["0", "1", "2", "tan²θ"], correctIndex: 1 },
    { text: "What is the period of sin(x)?", options: ["π", "2π", "π/2", "4π"], correctIndex: 1 },
    { text: "What is sin(30°)?", options: ["1/2", "√2/2", "√3/2", "1"], correctIndex: 0 },
    { text: "What is cos(60°)?", options: ["1", "√3/2", "1/2", "0"], correctIndex: 2 },
    { text: "What is tan(θ) in terms of sin and cos?", options: ["sin/cos", "cos/sin", "sin×cos", "1/cos"], correctIndex: 0 },
    { text: "What is the range of sin(x)?", options: ["[0, 1]", "[-1, 1]", "All real numbers", "[0, ∞)"], correctIndex: 1 },
    { text: "What is sin(0°)?", options: ["1", "0", "-1", "1/2"], correctIndex: 1 },
    { text: "What is the reciprocal of cosine?", options: ["Sine", "Secant", "Cosecant", "Cotangent"], correctIndex: 1 },
    { text: "What is cos(90°)?", options: ["1", "0", "-1", "1/2"], correctIndex: 1 },
    { text: "In a right triangle, what is sin(θ)?", options: ["adjacent/hypotenuse", "opposite/hypotenuse", "opposite/adjacent", "hypotenuse/opposite"], correctIndex: 1 },
    { text: "What is the amplitude of y = 3sin(x)?", options: ["1", "2", "3", "π"], correctIndex: 2 },
    { text: "What is sin(60°)?", options: ["1/2", "√2/2", "√3/2", "1"], correctIndex: 2 },
    { text: "What is cos(45°)?", options: ["1", "1/2", "√2/2", "√3/2"], correctIndex: 2 },
    { text: "What is the period of tan(x)?", options: ["2π", "π", "π/2", "4π"], correctIndex: 1 },
    { text: "What is 1 + tan²θ equal to?", options: ["sin²θ", "cos²θ", "sec²θ", "csc²θ"], correctIndex: 2 },
    { text: "What is the reciprocal of tangent?", options: ["Sine", "Cosine", "Cotangent", "Secant"], correctIndex: 2 },
    { text: "In a right triangle, what is cos(θ)?", options: ["opposite/hypotenuse", "adjacent/hypotenuse", "opposite/adjacent", "hypotenuse/adjacent"], correctIndex: 1 },
    { text: "What is sin(-θ)?", options: ["sin(θ)", "-sin(θ)", "cos(θ)", "-cos(θ)"], correctIndex: 1 },
    { text: "What is cos(180°)?", options: ["0", "1", "-1", "1/2"], correctIndex: 2 },
    { text: "What is the domain of tan(x)?", options: ["All real numbers", "All reals except odd multiples of π/2", "[-1, 1]", "[0, π]"], correctIndex: 1 },
    { text: "What is sin(45°)?", options: ["1", "1/2", "√2/2", "√3/2"], correctIndex: 2 },
    { text: "What is tan(60°)?", options: ["1", "√2", "√3", "2"], correctIndex: 2 },
    { text: "What is cos(-θ)?", options: ["cos(θ)", "-cos(θ)", "sin(θ)", "-sin(θ)"], correctIndex: 0 },
    { text: "What is the range of cos(x)?", options: ["[0, 1]", "[-1, 1]", "All real numbers", "[0, ∞)"], correctIndex: 1 },
    { text: "What is sin(180°)?", options: ["1", "-1", "0", "1/2"], correctIndex: 2 },
    { text: "What is cos(30°)?", options: ["1/2", "√2/2", "√3/2", "1"], correctIndex: 2 },
    { text: "What is tan(30°)?", options: ["1/√3", "√3", "1", "1/2"], correctIndex: 0 },
    { text: "What is the period of cos(x)?", options: ["π", "2π", "π/2", "4π"], correctIndex: 1 },
    { text: "What is sec(θ)?", options: ["1/sin(θ)", "1/cos(θ)", "1/tan(θ)", "sin(θ)/cos(θ)"], correctIndex: 1 },
    { text: "What is sin(270°)?", options: ["0", "1", "-1", "1/2"], correctIndex: 2 },
    { text: "What is cos(270°)?", options: ["1", "-1", "0", "1/2"], correctIndex: 2 },
    { text: "What is the Pythagorean identity?", options: ["sin²θ + cos²θ = 1", "sin²θ - cos²θ = 1", "tan²θ + 1 = sec²θ", "Both A and C"], correctIndex: 3 },
    { text: "In which quadrant is sin positive and cos negative?", options: ["I", "II", "III", "IV"], correctIndex: 1 },
    { text: "What is csc(θ)?", options: ["1/sin(θ)", "1/cos(θ)", "1/tan(θ)", "cos(θ)/sin(θ)"], correctIndex: 0 },
    { text: "What is the amplitude of y = -2cos(x)?", options: ["-2", "2", "1", "-1"], correctIndex: 1 },
    { text: "What is sin(π)?", options: ["1", "-1", "0", "1/2"], correctIndex: 2 },
    { text: "What is cos(π)?", options: ["0", "1", "-1", "1/2"], correctIndex: 2 },
    { text: "What is tan(0°)?", options: ["0", "1", "Undefined", "-1"], correctIndex: 0 },
    { text: "What is the reference angle for 150°?", options: ["30°", "60°", "45°", "150°"], correctIndex: 0 },
    { text: "What is cot(θ)?", options: ["sin(θ)/cos(θ)", "cos(θ)/sin(θ)", "1/sin(θ)", "1/cos(θ)"], correctIndex: 1 },
    { text: "In which quadrant are both sin and cos negative?", options: ["I", "II", "III", "IV"], correctIndex: 2 },
    { text: "What is the period of y = sin(2x)?", options: ["2π", "π", "π/2", "4π"], correctIndex: 1 },
    { text: "What is sin(π/2)?", options: ["0", "1", "-1", "1/2"], correctIndex: 1 },
    { text: "What is the law of sines?", options: ["a/sin A = b/sin B", "a² = b² + c²", "sin A = cos B", "tan A = sin A/cos A"], correctIndex: 0 },
    { text: "What is cos(2π)?", options: ["0", "1", "-1", "2"], correctIndex: 1 },
    { text: "What is the range of tan(x)?", options: ["[-1, 1]", "[0, ∞)", "All real numbers", "(-π/2, π/2)"], correctIndex: 2 },
];
