export const us_statesQuestions = [

    // US States (50 questions)
    { text: "What is the largest US state by area?", options: ["Texas", "Alaska", "California", "Montana"], correctIndex: 1 },
    { text: "What state is known as the Sunshine State?", options: ["California", "Florida", "Hawaii", "Arizona"], correctIndex: 1 },
    { text: "What is the smallest US state?", options: ["Delaware", "Rhode Island", "Connecticut", "Hawaii"], correctIndex: 1 },
    { text: "What state is home to the Grand Canyon?", options: ["Utah", "Arizona", "Nevada", "Colorado"], correctIndex: 1 },
    { text: "What state has the most counties?", options: ["California", "Texas", "Georgia", "Kentucky"], correctIndex: 1 },
    { text: "What is the capital of New York?", options: ["New York City", "Albany", "Buffalo", "Rochester"], correctIndex: 1 },
    { text: "What state is Mount Rushmore in?", options: ["Montana", "South Dakota", "North Dakota", "Wyoming"], correctIndex: 1 },
    { text: "What state is known as the Lone Star State?", options: ["Oklahoma", "Texas", "Arizona", "New Mexico"], correctIndex: 1 },
    { text: "What state has the longest coastline?", options: ["California", "Alaska", "Florida", "Hawaii"], correctIndex: 1 },
    { text: "What is the most populous US state?", options: ["Texas", "California", "Florida", "New York"], correctIndex: 1 },
    { text: "What state is known for potatoes?", options: ["Maine", "Idaho", "Montana", "North Dakota"], correctIndex: 1 },
    { text: "What state is Las Vegas in?", options: ["California", "Nevada", "Arizona", "Utah"], correctIndex: 1 },
    { text: "What state was the last to join the union?", options: ["Alaska", "Hawaii", "Arizona", "New Mexico"], correctIndex: 1 },
    { text: "What state is known as the Peach State?", options: ["Florida", "Georgia", "South Carolina", "Alabama"], correctIndex: 1 },
    { text: "What is the capital of California?", options: ["Los Angeles", "Sacramento", "San Francisco", "San Diego"], correctIndex: 1 },
    { text: "What state is Disney World in?", options: ["California", "Florida", "Texas", "Nevada"], correctIndex: 1 },
    { text: "What state has no state sales tax?", options: ["California", "Oregon", "Washington", "Nevada"], correctIndex: 1 },
    { text: "What state is known for cheese?", options: ["California", "Wisconsin", "Vermont", "New York"], correctIndex: 1 },
    { text: "What state is the Space Needle in?", options: ["Oregon", "Washington", "California", "Alaska"], correctIndex: 1 },
    { text: "What state is known as the First State?", options: ["Virginia", "Delaware", "Pennsylvania", "Massachusetts"], correctIndex: 1 },
    { text: "What state borders the most other states?", options: ["Colorado", "Tennessee", "Missouri", "Kentucky"], correctIndex: 2 },
    { text: "What state is Mount Denali in?", options: ["Washington", "Alaska", "Montana", "Colorado"], correctIndex: 1 },
    { text: "What state is known for maple syrup?", options: ["Maine", "Vermont", "New Hampshire", "Massachusetts"], correctIndex: 1 },
    { text: "What state is the Liberty Bell in?", options: ["New York", "Pennsylvania", "Massachusetts", "Virginia"], correctIndex: 1 },
    { text: "What state has the motto 'Live Free or Die'?", options: ["Vermont", "New Hampshire", "Maine", "Massachusetts"], correctIndex: 1 },
    { text: "What state is Yellowstone mostly in?", options: ["Montana", "Wyoming", "Idaho", "Colorado"], correctIndex: 1 },
    { text: "What state is known as the Show-Me State?", options: ["Kansas", "Missouri", "Oklahoma", "Arkansas"], correctIndex: 1 },
    { text: "What state is the Gateway Arch in?", options: ["Kansas", "Missouri", "Illinois", "Nebraska"], correctIndex: 1 },
    { text: "What state has only one syllable in its name?", options: ["Iowa", "Maine", "Ohio", "Utah"], correctIndex: 1 },
    { text: "What state is known for bourbon?", options: ["Tennessee", "Kentucky", "Virginia", "West Virginia"], correctIndex: 1 },
    { text: "What is the capital of Texas?", options: ["Houston", "Austin", "Dallas", "San Antonio"], correctIndex: 1 },
    { text: "What state is Crater Lake in?", options: ["Washington", "Oregon", "California", "Idaho"], correctIndex: 1 },
    { text: "What state is known as the Beehive State?", options: ["Idaho", "Utah", "Nevada", "Wyoming"], correctIndex: 1 },
    { text: "What state has the most volcanoes?", options: ["Hawaii", "Alaska", "Washington", "California"], correctIndex: 1 },
    { text: "What state is Harvard University in?", options: ["New York", "Massachusetts", "Connecticut", "Rhode Island"], correctIndex: 1 },
    { text: "What state is known for lobster?", options: ["Massachusetts", "Maine", "New Hampshire", "Rhode Island"], correctIndex: 1 },
    { text: "What state is the Alamo in?", options: ["New Mexico", "Texas", "Arizona", "Oklahoma"], correctIndex: 1 },
    { text: "What state has the highest elevation?", options: ["Colorado", "Alaska", "Wyoming", "Montana"], correctIndex: 1 },
    { text: "What state is Nashville in?", options: ["Kentucky", "Tennessee", "Georgia", "Alabama"], correctIndex: 1 },
    { text: "What state is known for jazz and Mardi Gras?", options: ["Mississippi", "Louisiana", "Alabama", "Florida"], correctIndex: 1 },
    { text: "What state borders only one other state?", options: ["Alaska", "Maine", "Florida", "Washington"], correctIndex: 1 },
    { text: "What state is the Mall of America in?", options: ["Wisconsin", "Minnesota", "Iowa", "North Dakota"], correctIndex: 1 },
    { text: "What state is known as the Badger State?", options: ["Minnesota", "Wisconsin", "Michigan", "Illinois"], correctIndex: 1 },
    { text: "What state has four letters in its name?", options: ["Iowa", "Ohio", "Utah", "All of these"], correctIndex: 3 },
    { text: "What state is Mount Rainier in?", options: ["Oregon", "Washington", "Alaska", "Colorado"], correctIndex: 1 },
    { text: "What state is known for country music?", options: ["Kentucky", "Tennessee", "Texas", "Georgia"], correctIndex: 1 },
    { text: "What state is the Outer Banks in?", options: ["Virginia", "North Carolina", "South Carolina", "Georgia"], correctIndex: 1 },
    { text: "What state is Salem witch trials associated with?", options: ["Connecticut", "Massachusetts", "Rhode Island", "New Hampshire"], correctIndex: 1 },
    { text: "What state is the Mayo Clinic in?", options: ["Wisconsin", "Minnesota", "Iowa", "Michigan"], correctIndex: 1 },
    { text: "What state is Pearl Harbor in?", options: ["California", "Hawaii", "Alaska", "Washington"], correctIndex: 1 },
];
