export const video_gamesQuestions = [

    // Video Games
    { text: "In the Mario franchise, what power-up allows Mario to shoot fireballs?", options: ["Super Mushroom", "Fire Flower", "Super Star", "Tanooki Suit"], correctIndex: 1 },
    { text: "What is the name of the main protagonist in the Legend of Zelda series?", options: ["Link", "Zelda", "Ganon", "Saria"], correctIndex: 0 },
    { text: "Which game series features the iconic phrase 'War... war never changes'?", options: ["Call of Duty", "Halo", "Fallout", "Grand Theft Auto"], correctIndex: 2 },
    { text: "What is the primary objective in the game 'Among Us'?", options: ["Complete tasks and identify impostors", "Eliminate all other players", "Build the tallest tower", "Survive for 10 minutes"], correctIndex: 0 },
    { text: "Which company created the 'Sonic the Hedgehog' series?", options: ["Nintendo", "Capcom", "Sega", "Konami"], correctIndex: 2 },
    { text: "What is the name of the currency in the Pokémon games?", options: ["Gold", "Coins", "Pokédollars", "Credits"], correctIndex: 2 },
    { text: "In 'Minecraft', what material is used to craft a diamond sword?", options: ["Iron", "Gold", "Diamond", "Netherite"], correctIndex: 2 },
    { text: "Which game features the characters Kratos and Atreus?", options: ["God of War", "The Last of Us", "Uncharted", "Horizon Zero Dawn"], correctIndex: 0 },
    { text: "Which game series is known for its 'Souls-like' brutal difficulty?", options: ["Dark Souls", "Assassin's Creed", "Final Fantasy", "Resident Evil"], correctIndex: 0 },
    { text: "What is the name of the main antagonist in the 'Five Nights at Freddy's' franchise?", options: ["Springtrap", "The Puppet", "William Afton", "Ballora"], correctIndex: 2 },
    { text: "Which game features the character Lara Croft?", options: ["Tomb Raider", "Uncharted", "Resident Evil", "Metal Gear Solid"], correctIndex: 0 },
    { text: "Which game features the characters Mario, Luigi, and Princess Peach?", options: ["Donkey Kong", "Super Mario Bros.", "Yoshi's Island", "Mario Kart"], correctIndex: 1 },
    { text: "What is the name of the main antagonist in the 'Half-Life' series?", options: ["Dr. Breen", "The G-Man", "Dr. Kleiner", "Barney Calhoun"], correctIndex: 1 },
    { text: "Which game series is known for its fast-paced stylish action and devil-hunting?", options: ["Devil May Cry", "Street Fighter", "Mortal Kombat", "Tekken"], correctIndex: 0 },
    { text: "What is the name of the main protagonist in the 'Metal Gear Solid' series?", options: ["Solid Snake", "Big Boss", "Raiden", "Revolver Ocelot"], correctIndex: 0 },
    { text: "Which game features the characters Sonic, Tails, and Knuckles?", options: ["Streets of Rage", "Sonic the Hedgehog", "Golden Axe", "Phantasy Star"], correctIndex: 1 },
    { text: "What is the name of the main antagonist in the 'Resident Evil' series?", options: ["Albert Wesker", "William Birkin", "Nemesis", "Mr. X"], correctIndex: 0 },
    { text: "Which game series is known for its turn-based combat and epic storytelling?", options: ["Final Fantasy", "Dragon Quest", "Persona", "Chrono Trigger"], correctIndex: 0 },
    { text: "What is the name of the main protagonist in 'Grand Theft Auto V'?", options: ["CJ", "Niko Bellic", "Trevor Philips", "Michael De Santa"], correctIndex: 2 },
    { text: "Which game features the characters Ryu, Ken, and Chun-Li?", options: ["Mortal Kombat", "Street Fighter", "Tekken", "King of Fighters"], correctIndex: 1 },
    { text: "Which game series is known for its open-world exploration and robotic dinosaur hunting?", options: ["Horizon Zero Dawn", "Far Cry Primal", "ARK: Survival Evolved", "The Witcher 3"], correctIndex: 0 },
    { text: "What is the name of the main protagonist in the 'God of War' series?", options: ["Kratos", "Atreus", "Zeus", "Ares"], correctIndex: 0 },
    { text: "Which game features the characters Master Chief, Cortana, and the Covenant?", options: ["Doom", "Halo", "Gears of War", "Mass Effect"], correctIndex: 1 },
    { text: "Which game series is known for its challenging puzzle rooms and portals?", options: ["Portal", "The Witness", "Myst", "Tomb Raider"], correctIndex: 0 },
    { text: "What is the best-selling video game of all time?", options: ["Grand Theft Auto V", "Minecraft", "Tetris", "Mario Kart 8"], correctIndex: 1 },
    { text: "What year was the original PlayStation released in Japan?", options: ["1992", "1993", "1994", "1995"], correctIndex: 2 },
    { text: "Which game features the witcher Geralt of Rivia?", options: ["Dragon Age: Origins", "The Witcher", "Skyrim", "Kingdom Come: Deliverance"], correctIndex: 1 },
    { text: "In 'Grand Theft Auto V', which fictional city is the game set in?", options: ["Liberty City", "Vice City", "Los Santos", "San Fierro"], correctIndex: 2 },
    { text: "Who originally created the Halo franchise before passing it to 343 Industries?", options: ["Infinity Ward", "Rare", "Bungie", "id Software"], correctIndex: 2 },
    { text: "What is the currency used in 'Animal Crossing'?", options: ["Gold", "Nook Points", "Bells", "Coins"], correctIndex: 2 },
    { text: "Which game introduced the 'bullet time' slow-motion mechanic?", options: ["Assassin's Creed", "Grand Theft Auto III", "Max Payne", "Hitman"], correctIndex: 2 },
    { text: "What is the name of Mario's home kingdom?", options: ["Mushroom Kingdom", "Koopa Kingdom", "Peach Kingdom", "Toad Kingdom"], correctIndex: 0 },
    { text: "Including Mew, how many Pokémon were in the original Pokémon Red and Blue?", options: ["150", "151", "152", "153"], correctIndex: 1 },
    { text: "What year was 'Pac-Man' first released in arcades?", options: ["1978", "1980", "1982", "1985"], correctIndex: 1 },
    { text: "Which game by Epic Games features a Battle Royale mode with building mechanics?", options: ["PUBG", "Fortnite", "Apex Legends", "Warzone"], correctIndex: 1 },
    { text: "What is the name of the AI companion in 'Portal 2'?", options: ["GLaDOS", "Wheatley", "Atlas", "Cave Johnson"], correctIndex: 1 },
    { text: "What happens when Mario eats a Super Mushroom in 'Super Mario Bros.'?", options: ["He gains fire powers", "He becomes larger", "He runs faster", "He becomes invincible"], correctIndex: 1 },
    { text: "Which game studio created 'Overwatch'?", options: ["Riot Games", "EA", "Blizzard Entertainment", "Ubisoft"], correctIndex: 2 },
    { text: "What is the in-game currency called in 'The Sims'?", options: ["Credits", "Simoleons", "Coins", "Bucks"], correctIndex: 1 },
    { text: "Which 'Far Cry' game is set in the fictional Himalayan country of Kyrat?", options: ["Far Cry 3", "Far Cry 4", "Far Cry 5", "Far Cry 6"], correctIndex: 1 },
    { text: "What is the name of the player character in 'Cyberpunk 2077'?", options: ["Johnny Silverhand", "V", "Night City", "Panam Palmer"], correctIndex: 1 },
    { text: "Which classic arcade game features a knight fighting while riding an ostrich?", options: ["Joust", "Gauntlet", "Defender", "Tron"], correctIndex: 0 },
    { text: "Which Nintendo console was 'The Legend of Zelda: Breath of the Wild' a launch title for?", options: ["Wii U", "Nintendo Switch", "3DS", "Wii"], correctIndex: 1 },
    { text: "In 'The Legend of Zelda', what is the name of the all-powerful artifact Link seeks?", options: ["Master Sword", "Ocarina of Time", "Triforce", "Hylian Shield"], correctIndex: 2 },
    { text: "What is the name of the training mode in 'Street Fighter II' where you fight a car?", options: ["Bonus Stage", "Arcade Mode", "Challenge Mode", "Versus Stage"], correctIndex: 0 },
    { text: "Which game series features the phrase 'It's dangerous to go alone, take this!'?", options: ["Final Fantasy", "Dragon Quest", "The Legend of Zelda", "Castlevania"], correctIndex: 2 },
    { text: "What does 'RPG' stand for in the context of video games?", options: ["Rapid Progression Game", "Role-Playing Game", "Real-Play Game", "Random Player Generator"], correctIndex: 1 },
    { text: "Which game features a post-apocalyptic wasteland and the Vault-Tec organization?", options: ["Borderlands", "The Last of Us", "Fallout", "Metro 2033"], correctIndex: 2 },
    { text: "In 'Super Smash Bros.', which company developed the series?", options: ["Sega", "Capcom", "Nintendo", "Namco"], correctIndex: 2 },
    { text: "Which game is famous for the line 'Do a barrel roll!'?", options: ["Star Fox", "F-Zero", "Pilotwings", "Ace Combat"], correctIndex: 0 },
];
