export const video_gamesQuestions = [

    // Video Games
    { text: "In the Mario franchise, what power-up allows Mario to shoot fireballs?", options: ["Super Mushroom", "Fire Flower", "Super Star", "Tanooki Suit"], correctIndex: 1 },
    { text: "What is the name of the main protagonist in the Legend of Zelda series?", options: ["Link", "Zelda", "Ganon", "Saria"], correctIndex: 0 },
    { text: "Which game series features the iconic phrase 'War... war never changes'?", options: ["Call of Duty", "Halo", "Fallout", "Grand Theft Auto"], correctIndex: 2 },
    { text: "What is the primary objective in the game 'Among Us'?", options: ["Complete tasks and identify impostors", "Eliminate all other players", "Build the tallest tower", "Survive for 10 minutes"], correctIndex: 0 },
    { text: "Which game developer created the 'Sonic the Hedgehog' series?", options: ["Nintendo", "Capcom", "Sega", "Konami"], correctIndex: 2 },
    { text: "What is the name of the currency in the Pokémon games?", options: ["Gold", "Coins", "Pokedollars", "Credits"], correctIndex: 2 },
    { text: "In 'Minecraft', what material is used to craft a diamond sword?", options: ["Iron", "Gold", "Diamond", "Netherite"], correctIndex: 2 },
    { text: "Which game features the characters Kratos and Atreus?", options: ["God of War", "The Last of Us", "Uncharted", "Horizon Zero Dawn"], correctIndex: 0 },
    { text: "What is the name of the virtual world created by Roblox?", options: ["The Metaverse", "The Grid", "The Sandbox", "The Block"], correctIndex: 2 },
    { text: "Which game series is known for its 'Souls-like' difficulty?", options: ["Dark Souls", "Assassin's Creed", "Final Fantasy", "Resident Evil"], correctIndex: 0 },
    { text: "What is the name of the main antagonist in the 'Five Nights at Freddy's' series?", options: ["Springtrap", "The Puppet", "William Afton", "Ballora"], correctIndex: 2 },
    { text: "Which game features the character Lara Croft?", options: ["Tomb Raider", "Uncharted", "Resident Evil", "Metal Gear Solid"], correctIndex: 0 },
    { text: "What is the primary weapon used by the character Master Chief?", options: ["Assault Rifle", "Energy Sword", "Plasma Pistol", "Battle Rifle"], correctIndex: 0 },
    { text: "Which game series is known for its open-world exploration and crafting?", options: ["Skyrim", "The Witcher", "Red Dead Redemption", "Grand Theft Auto"], correctIndex: 0 },
    { text: "What is the name of the organization that Geralt of Rivia works for?", options: ["Witchers", "The Brotherhood", "The Guild", "The Order"], correctIndex: 0 },
    { text: "Which game features the characters Mario, Luigi, and Princess Peach?", options: ["Donkey Kong", "Super Mario Bros.", "Yoshi's Island", "Mario Kart"], correctIndex: 1 },
    { text: "What is the name of the main antagonist in the 'Half-Life' series?", options: ["Dr. Breen", "The G-Man", "Dr. Kleiner", "Wallace Breen"], correctIndex: 1 },
    { text: "Which game series is known for its fast-paced combat and stylish action?", options: ["Devil May Cry", "Street Fighter", "Mortal Kombat", "Tekken"], correctIndex: 0 },
    { text: "What is the name of the main protagonist in the 'Metal Gear Solid' series?", options: ["Solid Snake", "Big Boss", "Raiden", "Revolver Ocelot"], correctIndex: 0 },
    { text: "Which game features the characters Sonic, Tails, and Knuckles?", options: ["Streets of Rage", "Sonic the Hedgehog", "Golden Axe", "Phantasy Star"], correctIndex: 1 },
    { text: "What is the name of the main antagonist in the 'Resident Evil' series?", options: ["Albert Wesker", "William Birkin", "Nemesis", "Mr. X"], correctIndex: 0 },
    { text: "Which game series is known for its turn-based combat and epic storytelling?", options: ["Final Fantasy", "Dragon Quest", "Persona", "Chrono Trigger"], correctIndex: 0 },
    { text: "What is the name of the main protagonist in the 'Grand Theft Auto V' game?", options: ["CJ", "Niko Bellic", "Trevor Philips", "Michael De Santa"], correctIndex: 2 },
    { text: "Which game features the characters Ryu, Ken, and Chun-Li?", options: ["Mortal Kombat", "Street Fighter", "Tekken", "King of Fighters"], correctIndex: 1 },
    { text: "What is the name of the main antagonist in the 'Uncharted' series?", options: ["Gabriel Roman", "Victor Sullivan", "Nadine Ross", "Rafe Adler"], correctIndex: 3 },
    { text: "Which game series is known for its open-world exploration and dinosaur hunting?", options: ["Horizon Zero Dawn", "Far Cry Primal", "ARK: Survival Evolved", "The Witcher 3"], correctIndex: 0 },
    { text: "What is the name of the main protagonist in the 'God of War' series?", options: ["Kratos", "Atreus", "Zeus", "Ares"], correctIndex: 0 },
    { text: "Which game features the characters Master Chief, Cortana, and the Covenant?", options: ["Doom", "Halo", "Gears of War", "Mass Effect"], correctIndex: 1 },
    { text: "What is the name of the main antagonist in the 'Assassin's Creed' series?", options: ["Rodrigo Borgia", "Haytham Kenway", "Abstergo Industries", "Al Mualim"], correctIndex: 2 },
    { text: "Which game series is known for its puzzle-solving and exploration?", options: ["Portal", "The Witness", "Myst", "Tomb Raider"], correctIndex: 0 },
];
