export const world_war_2Questions = [

    // World War II (50 questions)
    { text: "What year did World War II begin?", options: ["1937", "1939", "1941", "1943"], correctIndex: 1 },
    { text: "Which event started WWII in Europe?", options: ["Pearl Harbor", "Invasion of Poland", "D-Day", "Battle of Britain"], correctIndex: 1 },
    { text: "What year did World War II end?", options: ["1944", "1945", "1946", "1947"], correctIndex: 1 },
    { text: "Who was the leader of Nazi Germany?", options: ["Mussolini", "Hitler", "Stalin", "Hirohito"], correctIndex: 1 },
    { text: "What was D-Day?", options: ["Pearl Harbor attack", "Allied invasion of Normandy", "German surrender", "Atomic bombing"], correctIndex: 1 },
    { text: "Which country was NOT part of the Axis Powers?", options: ["Germany", "Italy", "Soviet Union", "Japan"], correctIndex: 2 },
    { text: "What date was Pearl Harbor attacked?", options: ["December 7, 1941", "December 25, 1941", "November 11, 1941", "January 1, 1942"], correctIndex: 0 },
    { text: "Who was the US President during most of WWII?", options: ["Truman", "Roosevelt", "Eisenhower", "Wilson"], correctIndex: 1 },
    { text: "What was Operation Barbarossa?", options: ["Invasion of France", "Invasion of Soviet Union", "Invasion of Britain", "Invasion of Italy"], correctIndex: 1 },
    { text: "Which battle was the turning point on the Eastern Front?", options: ["Battle of Berlin", "Battle of Stalingrad", "Battle of Kursk", "Battle of Moscow"], correctIndex: 1 },
    { text: "What was the Holocaust?", options: ["Battle name", "Genocide of Jews and others", "Peace treaty", "Military strategy"], correctIndex: 1 },
    { text: "Which two cities were atomic bombed?", options: ["Tokyo and Osaka", "Hiroshima and Nagasaki", "Kyoto and Kobe", "Yokohama and Sapporo"], correctIndex: 1 },
    { text: "Who was the British Prime Minister during most of WWII?", options: ["Chamberlain", "Churchill", "Attlee", "Eden"], correctIndex: 1 },
    { text: "What was the Blitzkrieg?", options: ["Peace treaty", "Lightning war tactics", "Surrender document", "Defensive strategy"], correctIndex: 1 },
    { text: "Which country remained neutral during WWII?", options: ["Poland", "Switzerland", "France", "Belgium"], correctIndex: 1 },
    { text: "What was the Manhattan Project?", options: ["Invasion plan", "Atomic bomb development", "Spy network", "Peace initiative"], correctIndex: 1 },
    { text: "Which battle was the largest naval battle in history?", options: ["Battle of Midway", "Battle of Leyte Gulf", "Battle of Jutland", "Battle of Coral Sea"], correctIndex: 1 },
    { text: "What was Dunkirk?", options: ["German city", "Evacuation of Allied troops", "French victory", "Peace conference"], correctIndex: 1 },
    { text: "Who was the Soviet leader during WWII?", options: ["Lenin", "Stalin", "Khrushchev", "Trotsky"], correctIndex: 1 },
    { text: "What was the name of Hitler's autobiography?", options: ["Das Kapital", "Mein Kampf", "The Prince", "Art of War"], correctIndex: 1 },
    { text: "Which conference divided Germany after the war?", options: ["Versailles", "Yalta", "Paris", "Geneva"], correctIndex: 1 },
    { text: "What was the Battle of Britain?", options: ["Land invasion", "Air campaign", "Naval battle", "Diplomatic crisis"], correctIndex: 1 },
    { text: "Who led Free French forces?", options: ["Pétain", "de Gaulle", "Clemenceau", "Napoleon"], correctIndex: 1 },
    { text: "What was VE Day?", options: ["Victory in Europe", "Victory Everywhere", "Victory Established", "Veterans' Enlistment"], correctIndex: 0 },
    { text: "What was the Enigma machine?", options: ["Tank", "Encryption device", "Aircraft", "Submarine"], correctIndex: 1 },
    { text: "Which country did Italy invade in 1935?", options: ["France", "Ethiopia", "Greece", "Albania"], correctIndex: 1 },
    { text: "What was the Lend-Lease Act?", options: ["Surrender terms", "US aid to Allies", "Draft law", "Peace proposal"], correctIndex: 1 },
    { text: "Who was the Supreme Allied Commander in Europe?", options: ["Patton", "Eisenhower", "MacArthur", "Montgomery"], correctIndex: 1 },
    { text: "What was the Nuremberg Trials?", options: ["Military battles", "War crimes trials", "Peace conference", "Treaty signing"], correctIndex: 1 },
    { text: "Which island campaign was particularly brutal in the Pacific?", options: ["Hawaii", "Iwo Jima", "Guam", "Midway"], correctIndex: 1 },
    { text: "What was Vichy France?", options: ["Free French territory", "German-controlled government", "Italian colony", "British protectorate"], correctIndex: 1 },
    { text: "Who commanded German forces in North Africa?", options: ["Göring", "Rommel", "Himmler", "Goebbels"], correctIndex: 1 },
    { text: "What was Operation Overlord?", options: ["Invasion of Italy", "D-Day invasion", "Battle of Britain", "Pacific campaign"], correctIndex: 1 },
    { text: "Which country switched from Axis to Allies?", options: ["Germany", "Italy", "Japan", "Finland"], correctIndex: 1 },
    { text: "What was the Battle of the Bulge?", options: ["Pacific battle", "German counteroffensive", "Air battle", "Naval engagement"], correctIndex: 1 },
    { text: "What was Anne Frank known for?", options: ["Spy", "Diary writer in hiding", "Resistance fighter", "Pilot"], correctIndex: 1 },
    { text: "Which general said 'I shall return' about the Philippines?", options: ["Eisenhower", "MacArthur", "Patton", "Bradley"], correctIndex: 1 },
    { text: "What was the Molotov-Ribbentrop Pact?", options: ["Peace treaty", "Non-aggression pact", "Trade agreement", "Military alliance"], correctIndex: 1 },
    { text: "What was the primary German fighter plane?", options: ["Spitfire", "Messerschmitt Bf 109", "P-51 Mustang", "Zero"], correctIndex: 1 },
    { text: "Which battle stopped the Japanese advance in the Pacific?", options: ["Pearl Harbor", "Midway", "Guadalcanal", "Coral Sea"], correctIndex: 1 },
    { text: "What was Auschwitz?", options: ["Military base", "Concentration camp", "Battle site", "City"], correctIndex: 1 },
    { text: "Who was Benito Mussolini?", options: ["German leader", "Italian fascist leader", "Japanese emperor", "Soviet general"], correctIndex: 1 },
    { text: "What was the Atlantic Charter?", options: ["Naval treaty", "Allied goals statement", "Surrender document", "Trade agreement"], correctIndex: 1 },
    { text: "Which Allied leader met at Tehran Conference?", options: ["Roosevelt, Churchill, Stalin", "Truman, Attlee, Stalin", "Wilson, Lloyd George, Clemenceau", "Kennedy, Macmillan, Khrushchev"], correctIndex: 0 },
    { text: "What was the Bataan Death March?", options: ["Victory parade", "Forced march of POWs", "Military drill", "Evacuation"], correctIndex: 1 },
    { text: "What date did Germany surrender?", options: ["May 8, 1945", "June 6, 1944", "August 15, 1945", "December 7, 1941"], correctIndex: 0 },
    { text: "What was the Wannsee Conference about?", options: ["Peace terms", "Final Solution planning", "Military strategy", "Post-war division"], correctIndex: 1 },
    { text: "Who piloted the plane that dropped the first atomic bomb?", options: ["Chuck Yeager", "Paul Tibbets", "Jimmy Doolittle", "Eddie Rickenbacker"], correctIndex: 1 },
    { text: "What was VJ Day?", options: ["Victory in Japan", "Veterans' Jubilee", "Versailles Judgment", "Vienna Journey"], correctIndex: 0 },
    { text: "Which country suffered the most casualties in WWII?", options: ["Germany", "Soviet Union", "China", "Poland"], correctIndex: 1 },
];
