export const world_war_1Questions = [
    // World War I (50 questions)
    { text: "What year did World War I begin?", options: ["1912", "1914", "1916", "1918"], correctIndex: 1 },
    { text: "What event triggered the start of World War I?", options: ["Sinking of Lusitania", "Assassination of Archduke Franz Ferdinand", "German invasion of Belgium", "Russian Revolution"], correctIndex: 1 },
    { text: "What were the two main alliance systems before WWI?", options: ["Axis and Allies", "Triple Alliance and Triple Entente", "NATO and Warsaw Pact", "Central and Western Powers"], correctIndex: 1 },
    { text: "Which country was NOT part of the Central Powers?", options: ["Germany", "Austria-Hungary", "France", "Ottoman Empire"], correctIndex: 2 },
    { text: "What year did World War I end?", options: ["1917", "1918", "1919", "1920"], correctIndex: 1 },
    { text: "What was the primary method of warfare on the Western Front?", options: ["Blitzkrieg", "Trench warfare", "Guerrilla warfare", "Naval warfare"], correctIndex: 1 },
    { text: "What treaty officially ended World War I?", options: ["Treaty of Versailles", "Treaty of Paris", "Treaty of Brest-Litovsk", "Treaty of Ghent"], correctIndex: 0 },
    { text: "Which new weapon was first used extensively in WWI?", options: ["Nuclear bombs", "Poison gas", "Cruise missiles", "Submarines"], correctIndex: 1 },
    { text: "What was the name of the area between opposing trenches?", options: ["Dead zone", "No man's land", "The void", "Neutral ground"], correctIndex: 1 },
    { text: "Which US President led America during WWI?", options: ["Theodore Roosevelt", "Woodrow Wilson", "William Taft", "Warren Harding"], correctIndex: 1 },
    { text: "What year did the United States enter WWI?", options: ["1914", "1915", "1917", "1918"], correctIndex: 2 },
    { text: "What was the Zimmermann Telegram?", options: ["Peace proposal", "German proposal to Mexico", "Declaration of war", "Surrender document"], correctIndex: 1 },
    { text: "What nickname was given to WWI?", options: ["The Great War", "The War of Wars", "The Final War", "The Modern War"], correctIndex: 0 },
    { text: "Which battle was one of the bloodiest in WWI?", options: ["Battle of Britain", "Battle of the Somme", "Battle of Midway", "Battle of Stalingrad"], correctIndex: 1 },
    { text: "What was the Schlieffen Plan?", options: ["Peace treaty", "German war strategy", "British naval plan", "French defense plan"], correctIndex: 1 },
    { text: "Which ship's sinking helped bring the US into WWI?", options: ["Titanic", "Lusitania", "Bismarck", "Arizona"], correctIndex: 1 },
    { text: "What was the Red Baron famous for?", options: ["Tank commander", "Fighter pilot", "Naval captain", "Infantry general"], correctIndex: 1 },
    { text: "Which empire collapsed at the end of WWI?", options: ["British Empire", "Austro-Hungarian Empire", "French Empire", "Spanish Empire"], correctIndex: 1 },
    { text: "What was the primary role of tanks in WWI?", options: ["Air defense", "Breaking through trenches", "Naval support", "Communication"], correctIndex: 1 },
    { text: "Which country switched sides during WWI?", options: ["Germany", "Italy", "France", "Russia"], correctIndex: 1 },
    { text: "What was the Christmas Truce?", options: ["Official ceasefire", "Informal truce between soldiers", "Peace treaty attempt", "Religious holiday"], correctIndex: 1 },
    { text: "Which revolution occurred during WWI?", options: ["French Revolution", "American Revolution", "Russian Revolution", "Chinese Revolution"], correctIndex: 2 },
    { text: "What were U-boats?", options: ["American submarines", "German submarines", "British aircraft", "French tanks"], correctIndex: 1 },
    { text: "Which country remained neutral throughout WWI?", options: ["Belgium", "Switzerland", "Italy", "Romania"], correctIndex: 1 },
    { text: "What was the main cause of trench foot?", options: ["Poison gas", "Poor hygiene", "Wet, muddy conditions", "Malnutrition"], correctIndex: 2 },
    { text: "Who was the German Kaiser during WWI?", options: ["Otto von Bismarck", "Wilhelm II", "Frederick III", "Wilhelm I"], correctIndex: 1 },
    { text: "What was the Western Front?", options: ["Pacific theater", "Line through France/Belgium", "Italian border", "Eastern Europe"], correctIndex: 1 },
    { text: "Which gas was commonly used as a weapon in WWI?", options: ["Oxygen", "Chlorine", "Nitrogen", "Helium"], correctIndex: 1 },
    { text: "What was the primary purpose of Wilson's Fourteen Points?", options: ["Declare war", "Outline peace terms", "Form alliances", "Justify neutrality"], correctIndex: 1 },
    { text: "Which battle marked the entry of tanks into warfare?", options: ["Battle of Verdun", "Battle of the Somme", "Battle of Ypres", "Battle of Tannenberg"], correctIndex: 1 },
    { text: "What was the armistice date of WWI?", options: ["November 11, 1918", "December 25, 1918", "January 1, 1919", "May 8, 1918"], correctIndex: 0 },
    { text: "Which country had the largest army at the start of WWI?", options: ["Germany", "France", "Russia", "Britain"], correctIndex: 2 },
    { text: "What was the main goal of the Gallipoli Campaign?", options: ["Invade Germany", "Control Dardanelles", "Capture Paris", "Defend Belgium"], correctIndex: 1 },
    { text: "Which poet wrote 'In Flanders Fields'?", options: ["Wilfred Owen", "Rupert Brooke", "John McCrae", "Siegfried Sassoon"], correctIndex: 2 },
    { text: "What does ANZAC stand for?", options: ["Allied Nations Zealand and Canada", "Australian and New Zealand Army Corps", "Atlantic Naval Zone Alliance Command", "Anglo-New Zealand Armed Coalition"], correctIndex: 1 },
    { text: "Which country suffered the most military casualties in WWI?", options: ["France", "Britain", "Germany", "Russia"], correctIndex: 3 },
    { text: "What was the League of Nations?", options: ["Military alliance", "International peace organization", "Trade agreement", "Cultural exchange"], correctIndex: 1 },
    { text: "Which ace pilot was known as the 'Red Baron'?", options: ["Eddie Rickenbacker", "Manfred von Richthofen", "Billy Bishop", "René Fonck"], correctIndex: 1 },
    { text: "What caused the US to declare war on Germany?", options: ["Pearl Harbor", "Unrestricted submarine warfare", "Invasion of Poland", "Assassination"], correctIndex: 1 },
    { text: "Which front saw fighting between Russia and Germany?", options: ["Western Front", "Eastern Front", "Southern Front", "Italian Front"], correctIndex: 1 },
    { text: "What was mustard gas used for in WWI?", options: ["Fuel", "Chemical weapon", "Medicine", "Signaling"], correctIndex: 1 },
    { text: "Which battle lasted the longest in WWI?", options: ["Battle of the Somme", "Battle of Verdun", "Battle of Ypres", "Battle of Passchendaele"], correctIndex: 1 },
    { text: "What was the main purpose of war bonds?", options: ["Finance the war", "Feed soldiers", "Build weapons", "Train troops"], correctIndex: 0 },
    { text: "Which technology was NOT used in WWI?", options: ["Airplanes", "Tanks", "Atomic bombs", "Submarines"], correctIndex: 2 },
    { text: "What was the Hindenburg Line?", options: ["Airship route", "German defensive position", "Supply line", "Communication system"], correctIndex: 1 },
    { text: "Which country's invasion violated Belgian neutrality?", options: ["France", "Russia", "Germany", "Austria-Hungary"], correctIndex: 2 },
    { text: "What was the primary role of cavalry in WWI?", options: ["Front-line combat", "Reconnaissance", "Air support", "Naval escort"], correctIndex: 1 },
    { text: "Which pandemic occurred during WWI?", options: ["Black Death", "Spanish Flu", "Cholera", "Smallpox"], correctIndex: 1 },
    { text: "What were dreadnoughts?", options: ["Fighter planes", "Battleships", "Tanks", "Submarines"], correctIndex: 1 },
    { text: "Which country did NOT join the League of Nations?", options: ["France", "Britain", "United States", "Italy"], correctIndex: 2 },
];
