export const world_capitalsQuestions = [
    // World Capitals (50 questions)
    { text: "What is the capital of France?", options: ["Lyon", "Paris", "Marseille", "Nice"], correctIndex: 1 },
    { text: "What is the capital of Japan?", options: ["Osaka", "Tokyo", "Kyoto", "Hiroshima"], correctIndex: 1 },
    { text: "What is the capital of Australia?", options: ["Sydney", "Canberra", "Melbourne", "Brisbane"], correctIndex: 1 },
    { text: "What is the capital of Canada?", options: ["Toronto", "Ottawa", "Montreal", "Vancouver"], correctIndex: 1 },
    { text: "What is the capital of Brazil?", options: ["Rio de Janeiro", "Brasília", "São Paulo", "Salvador"], correctIndex: 1 },
    { text: "What is the capital of Egypt?", options: ["Alexandria", "Cairo", "Giza", "Luxor"], correctIndex: 1 },
    { text: "What is the capital of India?", options: ["Mumbai", "New Delhi", "Bangalore", "Kolkata"], correctIndex: 1 },
    { text: "What is the capital of Germany?", options: ["Munich", "Berlin", "Hamburg", "Frankfurt"], correctIndex: 1 },
    { text: "What is the capital of Italy?", options: ["Milan", "Rome", "Venice", "Florence"], correctIndex: 1 },
    { text: "What is the capital of Spain?", options: ["Barcelona", "Madrid", "Valencia", "Seville"], correctIndex: 1 },
    { text: "What is the capital of Russia?", options: ["St. Petersburg", "Moscow", "Kazan", "Sochi"], correctIndex: 1 },
    { text: "What is the capital of China?", options: ["Shanghai", "Beijing", "Hong Kong", "Guangzhou"], correctIndex: 1 },
    { text: "What is the capital of South Korea?", options: ["Busan", "Seoul", "Incheon", "Daegu"], correctIndex: 1 },
    { text: "What is the capital of Argentina?", options: ["Córdoba", "Buenos Aires", "Rosario", "Mendoza"], correctIndex: 1 },
    { text: "What is the capital of Turkey?", options: ["Istanbul", "Ankara", "Izmir", "Antalya"], correctIndex: 1 },
    { text: "What is the capital of Thailand?", options: ["Chiang Mai", "Bangkok", "Phuket", "Pattaya"], correctIndex: 1 },
    { text: "What is the capital of Greece?", options: ["Thessaloniki", "Athens", "Sparta", "Crete"], correctIndex: 1 },
    { text: "What is the capital of Poland?", options: ["Kraków", "Warsaw", "Gdańsk", "Wrocław"], correctIndex: 1 },
    { text: "What is the capital of Mexico?", options: ["Guadalajara", "Mexico City", "Monterrey", "Cancún"], correctIndex: 1 },
    { text: "What is the capital of South Africa?", options: ["Johannesburg", "Pretoria (executive)", "Cape Town", "Durban"], correctIndex: 1 },
    { text: "What is the capital of Netherlands?", options: ["Rotterdam", "Amsterdam", "The Hague", "Utrecht"], correctIndex: 1 },
    { text: "What is the capital of Switzerland?", options: ["Zurich", "Bern", "Geneva", "Basel"], correctIndex: 1 },
    { text: "What is the capital of Sweden?", options: ["Gothenburg", "Stockholm", "Malmö", "Uppsala"], correctIndex: 1 },
    { text: "What is the capital of Norway?", options: ["Bergen", "Oslo", "Trondheim", "Stavanger"], correctIndex: 1 },
    { text: "What is the capital of Finland?", options: ["Tampere", "Helsinki", "Turku", "Espoo"], correctIndex: 1 },
    { text: "What is the capital of Denmark?", options: ["Aarhus", "Copenhagen", "Odense", "Aalborg"], correctIndex: 1 },
    { text: "What is the capital of Portugal?", options: ["Porto", "Lisbon", "Faro", "Coimbra"], correctIndex: 1 },
    { text: "What is the capital of Austria?", options: ["Salzburg", "Vienna", "Innsbruck", "Graz"], correctIndex: 1 },
    { text: "What is the capital of Belgium?", options: ["Antwerp", "Brussels", "Bruges", "Ghent"], correctIndex: 1 },
    { text: "What is the capital of Ireland?", options: ["Cork", "Dublin", "Galway", "Limerick"], correctIndex: 1 },
    { text: "What is the capital of New Zealand?", options: ["Auckland", "Wellington", "Christchurch", "Queenstown"], correctIndex: 1 },
    { text: "What is the capital of Chile?", options: ["Valparaíso", "Santiago", "Concepción", "Viña del Mar"], correctIndex: 1 },
    { text: "What is the capital of Peru?", options: ["Cusco", "Lima", "Arequipa", "Trujillo"], correctIndex: 1 },
    { text: "What is the capital of Colombia?", options: ["Medellín", "Bogotá", "Cartagena", "Cali"], correctIndex: 1 },
    { text: "What is the capital of Venezuela?", options: ["Maracaibo", "Caracas", "Valencia", "Barquisimeto"], correctIndex: 1 },
    { text: "What is the capital of Vietnam?", options: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hue"], correctIndex: 1 },
    { text: "What is the capital of Indonesia?", options: ["Surabaya", "Jakarta", "Bali", "Bandung"], correctIndex: 1 },
    { text: "What is the capital of Philippines?", options: ["Cebu", "Manila", "Davao", "Quezon City"], correctIndex: 1 },
    { text: "What is the capital of Malaysia?", options: ["Penang", "Kuala Lumpur", "Johor Bahru", "Ipoh"], correctIndex: 1 },
    { text: "What is the capital of Singapore?", options: ["Singapore", "Singapore City", "Central Singapore", "Marina Bay"], correctIndex: 0 },
    { text: "What is the capital of Morocco?", options: ["Casablanca", "Rabat", "Marrakech", "Fez"], correctIndex: 1 },
    { text: "What is the capital of Kenya?", options: ["Mombasa", "Nairobi", "Kisumu", "Nakuru"], correctIndex: 1 },
    { text: "What is the capital of Nigeria?", options: ["Lagos", "Abuja", "Kano", "Ibadan"], correctIndex: 1 },
    { text: "What is the capital of Saudi Arabia?", options: ["Jeddah", "Riyadh", "Mecca", "Medina"], correctIndex: 1 },
    { text: "What is the capital of United Arab Emirates?", options: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"], correctIndex: 1 },
    { text: "What is the capital of Israel?", options: ["Tel Aviv", "Jerusalem", "Haifa", "Eilat"], correctIndex: 1 },
    { text: "What is the capital of Pakistan?", options: ["Karachi", "Islamabad", "Lahore", "Rawalpindi"], correctIndex: 1 },
    { text: "What is the capital of Bangladesh?", options: ["Chittagong", "Dhaka", "Khulna", "Sylhet"], correctIndex: 1 },
    { text: "What is the capital of Czech Republic?", options: ["Brno", "Prague", "Ostrava", "Plzeň"], correctIndex: 1 },
    { text: "What is the capital of Hungary?", options: ["Debrecen", "Budapest", "Szeged", "Pécs"], correctIndex: 1 },
];
